import { cloneJsonValue, stringifyJsonValue } from './json-data.js?v=0.26.0';
import { validateOccurrences } from './event-data.js?v=0.26.0';
import { own, plain, freeze } from '../record-data.js?v=0.26.0';
import { artifactVisibility, preserveArtifactPrivacy, validVisibilityMetadata } from '../artifact-privacy.js?v=0.26.0';
import { validateRecallScope, validateRecallArmProposal } from '../recall-state.js?v=0.26.0';
const fail=(code,message)=>({ok:false,error:{code,message}}),id=value=>typeof value==='string'&&!!value.trim()&&value.length<=256;
const eventId=value=>typeof value==='string'&&!!value.trim()&&value.length<=2048;
const exact=(value,keys,required=keys)=>plain(value)&&Object.keys(value).every(key=>keys.includes(key))&&required.every(key=>Object.hasOwn(value,key));
const canonical=value=>{const result=stringifyJsonValue(value);return result.ok?result.data.text:null;};
const pin=(id,kind,direction,required=false)=>({id,label:id,kind,direction,required,cardinality:'one'});
const control=(type,value,extra={})=>({type,default:value,...extra});
const hotkey={code:'KeyR',ctrl:true,alt:false,shift:true,meta:false};
const common={actorId:'',memorySetId:'',target:'both'};
const commonControls={actorId:control('string','',{maxLength:256}),memorySetId:control('string','',{maxLength:256}),target:control('enum','both',{values:['reply','swipe','both']})};
const registration=(id,title,defaults,controls,output)=>({id,title,family:'Recall',phase:'both',minimumSchema:3,minimumRuntime:2,operationVersion:1,input:'data',output,defaults,controls:Object.keys(defaults),controlDescriptors:controls,requestBound:0,modelRole:null,terminal:false,dynamicPorts:true,rootOnly:true,hostOperation:true});
export const RECALL_OPERATIONS={
 recall:registration('recall','Recall',{...common,activation:'armed',keywords:[],caseSensitive:false,eventTypes:[],partnerIds:[],tags:[],recordIds:[],limit:8,maxCharacters:12000,maxTokens:2048,title:'Recalled memories'},
 {...commonControls,activation:control('enum','armed',{values:['armed','keyword','event','character','armed-or-keyword','armed-or-event','armed-or-character']}),keywords:control('array',[],{items:'string',max:32}),caseSensitive:control('boolean',false),eventTypes:control('array',[],{items:'string',max:32}),partnerIds:control('array',[],{items:'string',max:32}),tags:control('array',[],{items:'string',max:32}),recordIds:control('array',[],{items:'string',max:64}),limit:control('integer',8,{min:1,max:64}),maxCharacters:control('integer',12000,{min:1,max:100000}),maxTokens:control('integer',2048,{min:1,max:8192}),title:control('string','Recalled memories',{maxLength:256})},'guidance'),
 'hotkey-arm':registration('hotkey-arm','Hotkey Arm',{...common,uses:'next-match',consumeOn:'accepted',hotkey},
 {...commonControls,uses:control('enum','next-match',{values:['next-match','one-per-type','until-disarmed']}),consumeOn:control('enum','accepted',{values:['success','accepted']}),hotkey:control('object',hotkey)},'data'),
};
function resolve(node,options){
 if(!plain(node)||!plain(options))return fail('INVALID_SETTINGS','Use plain Recall node metadata.');
 for(const [value,keys]of[[node,['operation','operationVersion','phase','type']],[options,['phase']]])for(const key of keys){const property=Object.getOwnPropertyDescriptor(value,key);if(property&&(!property.enumerable||!Object.hasOwn(property,'value')))return fail('INVALID_SETTINGS','Recall routing metadata requires own data properties.');}
 const operation=own(node,'operation'),base=Object.hasOwn(RECALL_OPERATIONS,operation)&&RECALL_OPERATIONS[operation];if(!base||own(node,'operationVersion')!==undefined&&own(node,'operationVersion')!==1)return fail('UNKNOWN_OPERATION','Use a supported Recall operation version.');
 const phase=own(options,'phase')??own(node,'phase')??'pre';if(!['pre','post'].includes(phase)||own(node,'phase')!==undefined&&own(node,'phase')!==phase)return fail('INVALID_PHASE','Recall must match its effective workflow stage.');
 const settings={};for(const key of base.controls){const property=Object.getOwnPropertyDescriptor(node,key);if(property&&(!property.enumerable||!Object.hasOwn(property,'value')))return fail('INVALID_SETTINGS','Recall controls require own data properties.');const checked=cloneJsonValue(property?property.value:base.defaults[key]);if(!checked.ok)return fail('INVALID_SETTINGS','Recall controls require bounded plain data.');settings[key]=checked.data.value;const descriptor=base.controlDescriptors[key];
  if(descriptor.type==='string'&&(typeof settings[key]!=='string'||settings[key].length>descriptor.maxLength)||descriptor.type==='integer'&&(!Number.isSafeInteger(settings[key])||settings[key]<descriptor.min||settings[key]>descriptor.max)||descriptor.type==='enum'&&!descriptor.values.includes(settings[key])||descriptor.type==='boolean'&&typeof settings[key]!=='boolean'||descriptor.type==='array'&&(!Array.isArray(settings[key])||settings[key].length>descriptor.max||settings[key].some(value=>!id(value))||new Set(settings[key]).size!==settings[key].length))return fail('INVALID_SETTINGS','Use supported bounded Recall controls.');
 }
 if(!id(settings.actorId)||!id(settings.memorySetId))return fail('INVALID_SETTINGS','Select an actor and memory set explicitly.');
 if(operation==='hotkey-arm'){const checked=validateRecallArmProposal({schemaVersion:1,type:'recall-arm-proposal',...settings});if(!checked.ok)return checked;}
 else if(settings.activation.includes('keyword')&&!settings.keywords.length||settings.activation.includes('event')&&!settings.eventTypes.length)return fail('INVALID_SETTINGS','An automatic trigger needs explicit keywords or event types.');
 const ports=operation==='hotkey-arm'?[pin('proposal','data','output')]:[pin('records','data','input'),pin('presence','data','input'),...(settings.activation.includes('keyword')?[pin('source','data','input')]:[]),...(settings.activation.includes('event')?[pin('events','data','input')]:[]),pin('out','guidance','output'),pin('records','data','output'),pin('report','data','output')];
 return {ok:true,data:{descriptor:{...base,phase},ports,settings}};
}
export function describeRecallNode(node,options={}){const result=resolve(node,options);return result.ok?{ok:true,data:{descriptor:result.data.descriptor,ports:result.data.ports}}:result;}
const skipped=(code,message,status='skipped')=>({ok:true,outputStates:Object.fromEntries(['out','records','report'].map(key=>[key,{status,reason:{code,message}}])),reports:[{operation:'recall',actualCalls:0,code}]});
function inputsFor(raw,ports){const result=cloneJsonValue(raw);if(!result.ok)return fail('INVALID_INPUT','Recall inputs require bounded own plain data.');const inputs=result.data.value;if(!plain(inputs))return fail('INVALID_INPUT','Recall requires named Data inputs.');if(Object.keys(inputs).some(key=>!ports.some(port=>port.direction==='input'&&port.id===key)))return fail('UNSUPPORTED_INPUT','Remove stale Recall input ports.');for(const artifact of Object.values(inputs))if(!exact(artifact,['kind','value','visibility'],['kind','value'])||artifact.kind!=='data'||!Object.hasOwn(artifact,'value')||!validVisibilityMetadata(artifact))return fail('INVALID_INPUT','Recall inputs require checked Data envelopes and visibility.');return {ok:true,data:inputs};}
function presenceFor(raw,actorId){return exact(raw,['schemaVersion','recordType','sceneId','sourceId','revision','actorId','status','evidence'],['schemaVersion','recordType','sceneId','sourceId','revision','actorId','status'])&&raw.schemaVersion===1&&raw.recordType==='scene-presence'&&raw.actorId===actorId&&[raw.sceneId,raw.sourceId,raw.revision].every(id)&&['present','absent','unresolved'].includes(raw.status)?{ok:true,data:raw}:fail('INVALID_RECALL_PRESENCE','Recall needs checked participation of its authorized actor at this scene stage.');}
function triggerFor(settings,inputs,phase){
 if(settings.activation==='armed')return {ok:true,data:{}};
 const kind=settings.activation.replace('armed-or-','');
 if(kind==='character'){if(!inputs.presence)return settings.activation.startsWith('armed-or-')?{ok:true,data:{}}:fail('MISSING_INPUT','Automatic character recall requires scene presence.');const presence=presenceFor(inputs.presence.value,settings.actorId);if(!presence.ok)return presence;if(presence.data.status==='unresolved')return {ok:true,data:{held:true}};return {ok:true,data:presence.data.status==='present'?{automatic:{kind,sourceId:presence.data.sourceId,revision:presence.data.revision,eventIds:[]}}:{}};}
 if(kind==='keyword'){
  if(!inputs.source)return settings.activation.startsWith('armed-or-')?{ok:true,data:{}}:fail('MISSING_INPUT','Automatic keyword recall requires its bounded source.');const source=inputs.source.value;
  if(!exact(source,['sourceId','revision','sceneId','watch','text','visibility','stage'],['sourceId','revision','watch','text'])||!id(source.sourceId)||!id(source.revision)||typeof source.text!=='string'||source.text.length>100000||!['player-message','draft','st-reply','scene-context','accepted-event'].includes(source.watch))return fail('INVALID_RECALL_SOURCE','Keyword recall requires explicit source and revision identity.');
  if((source.watch==='draft'||source.watch==='st-reply'||source.stage==='post')&&phase==='pre')return fail('RECALL_STAGE_MISMATCH','A reply trigger can affect Post processing or a later generation, not the earlier prompt.');
  const text=settings.caseSensitive?source.text:source.text.toLocaleLowerCase('en-US');const matched=settings.keywords.some(keyword=>text.includes(settings.caseSensitive?keyword:keyword.toLocaleLowerCase('en-US')));
  return {ok:true,data:matched?{automatic:{kind,sourceId:source.sourceId,revision:source.revision,eventIds:[]}}:{}};
 }
 if(!inputs.events)return settings.activation.startsWith('armed-or-')?{ok:true,data:{}}:fail('MISSING_INPUT','Automatic event recall requires confirmed occurrences.');
 const events=inputs.events.value;if(!Array.isArray(events)||events.length>128||events.some(event=>!plain(event)))return fail('INVALID_RECALL_EVENTS','Recall events must be a bounded collection.');
 const matches=events.filter(event=>settings.eventTypes.includes(event.eventType)&&event.actorId===settings.actorId);
 if(matches.some(event=>['candidate','unresolved'].includes(event.status)))return {ok:true,data:{held:true}};
 const confirmed=matches.filter(event=>event.status==='confirmed');if(!confirmed.length)return {ok:true,data:{}};
 if(confirmed.length>64||confirmed.some(event=>!eventId(event.eventId)||event.semantics!=='actual'||!(event.confirmation?.accepted===true||event.interpretation==='accepted'))||new Set(confirmed.map(event=>event.eventId)).size!==confirmed.length)return fail('INVALID_RECALL_EVENTS','Only distinct confirmed actual occurrences can activate recall.');
 if(confirmed.some(event=>event.recordType==='occurrence')){const canonical=validateOccurrences(confirmed);if(!canonical.ok)return fail('INVALID_RECALL_EVENTS','Canonical occurrences require their checked identity and confirmation.');}
 const source=confirmed[0].source??confirmed[0],sourceId=source.sourceId,revision=source.revision;if(!id(sourceId)||!id(revision)||confirmed.some(event=>(event.source??event).sourceId!==sourceId||(event.source??event).revision!==revision))return fail('INVALID_RECALL_EVENTS','Group event recall by one explicit source revision.');
 if(phase==='pre'&&['draft','st-reply'].includes(source.watch))return fail('RECALL_STAGE_MISMATCH','Reply occurrences cannot retroactively alter their generation prompt.');
 return {ok:true,data:{automatic:{kind:'event',sourceId,revision,eventIds:confirmed.map(event=>event.eventId)}}};
}
function sameScope(value,scope){const checked=validateRecallScope(value);return checked.ok&&['userId','chatId','workflowId','actorId'].every(key=>checked.data[key]===scope[key]);}
function selectionFor(artifact,settings,scope){
 const visibility=artifactVisibility(artifact);if(visibility.kind==='hidden'||visibility.kind==='actor-private'&&visibility.actorId!==scope.actorId)return fail('RECALL_ACTOR_MISMATCH','Recall records must be permitted material for this actor.');
 let records=artifact.value;
 if(plain(records)){if(!exact(records,['schemaVersion','type','scope','memorySetId','records'])||records.schemaVersion!==1||records.type!=='recall-records'||!sameScope(records.scope,scope)||records.memorySetId!==settings.memorySetId)return fail('INVALID_RECALL_RECORDS','A record container must match the authorized scope and memory set.');records=records.records;}
 if(!Array.isArray(records)||records.length>512)return fail('INVALID_RECALL_RECORDS','Supply at most 512 checked records from Read File or Format.');
 for(const record of records){if(!exact(record,['id','revision','actorId','text','partnerIds','tags','eventId','recency','sourceRefs','scope','visibility'],['id','actorId','text'])||!id(record.id)||record.actorId!==scope.actorId||typeof record.text!=='string'||!record.text.trim()||record.text.length>100000||record.revision!==undefined&&!id(record.revision)||record.eventId!==undefined&&!eventId(record.eventId)||record.recency!==undefined&&(!Number.isSafeInteger(record.recency)||record.recency<0)||record.sourceRefs!==undefined&&(!Array.isArray(record.sourceRefs)||record.sourceRefs.length>64||record.sourceRefs.some(ref=>!exact(ref,['id','revision'])||!id(ref.id)||!id(ref.revision))||new Set(record.sourceRefs.map(ref=>canonical([ref.id,ref.revision]))).size!==record.sourceRefs.length)||record.scope!==undefined&&!sameScope(record.scope,scope)||record.visibility!==undefined&&!validVisibilityMetadata(record)||['partnerIds','tags'].some(key=>record[key]!==undefined&&(!Array.isArray(record[key])||record[key].length>64||record[key].some(value=>!id(value))||new Set(record[key]).size!==record[key].length)))return fail('INVALID_RECALL_RECORDS','Record identity, actor, text and optional filters must be checked bounded data.');const mark=artifactVisibility(record);if(mark.kind==='hidden'||mark.kind==='actor-private'&&mark.actorId!==scope.actorId)return fail('RECALL_ACTOR_MISMATCH','A record cannot disclose another actor or hidden material.');}
 if(new Set(records.map(record=>record.id)).size!==records.length)return fail('INVALID_RECALL_RECORDS','Memory record identities must be distinct.');
 const matches=records.map((record,index)=>({record,index})).filter(({record})=>(!settings.recordIds.length||settings.recordIds.includes(record.id))&&settings.partnerIds.every(partner=>record.partnerIds?.includes(partner))&&settings.tags.every(tag=>record.tags?.includes(tag))).sort((a,b)=>(b.record.recency??0)-(a.record.recency??0)||a.index-b.index);
 const selected=[];let characters=settings.title.length;
 for(const {record}of matches){if(selected.length>=settings.limit)break;const next=record.text.length+1;if(characters+next>settings.maxCharacters)continue;selected.push(record);characters+=next;}
 if(matches.length&&!selected.length)return fail('RECALL_BUDGET_EXCEEDED','No matching whole memory fits the authored retrieval budget.');
 return {ok:true,data:{records:selected,text:[settings.title,...selected.map(record=>record.text)].join('\n'),omittedCount:records.length-selected.length,matchedCount:matches.length}};
}
function safeCapability(raw){const result=cloneJsonValue(raw);if(!result.ok||!plain(result.data.value)||typeof result.data.value.ok!=='boolean')return fail('INVALID_RECALL_RESPONSE','The trusted Recall capability returned invalid data.');return result.data.value.ok?{ok:true,data:result.data.value.data}:fail('RECALL_CAPABILITY_FAILED','The trusted Recall capability did not authorize this action.');}
async function executeRaw(node,namedInputs,local){
 const resolved=resolve(node,{phase:own(local,'phase')});if(!resolved.ok)return resolved;const {descriptor,ports,settings}=resolved.data;
 if(own(local,'root')!==true)return fail('RECALL_ROOT_REQUIRED','Recall arming and activation require the trusted root host.');
 const validated=inputsFor(namedInputs,ports);if(!validated.ok)return validated;const inputs=validated.data,snapshot=stringifyJsonValue(namedInputs).data.text;
 const session=own(local,'recallState');if(!plain(session)||['current','activate','checkClaim','settle'].some(key=>typeof own(session,key)!=='function'))return fail('RECALL_STATE_MISSING','Bind the trusted scoped Recall state service.');
 // Run this guard after trusted callbacks; it never calls the session or another host capability.
 const localCurrent=()=>{const latest=resolve(node,{phase:descriptor.phase});if(!latest.ok||latest.data.descriptor.id!==descriptor.id||canonical(latest.data.settings)!==canonical(settings))return fail('STALE_RECALL_SETTINGS','Recall settings changed while the operation was pending.');if(own(local,'signal')?.aborted)return fail('ABORTED','Recall was cancelled.');const now=stringifyJsonValue(namedInputs);return !now.ok||now.data.text!==snapshot?fail('STALE_RECALL_INPUT','Ignore changed Recall evidence.'):null;};
 const current=()=>{const before=localCurrent();if(before)return before;let result;try{result=own(session,'current')();}catch{return fail('RECALL_SCOPE_UNAVAILABLE','The trusted Recall scope is unavailable.');}const checked=safeCapability(result);if(!checked.ok)return checked;const scope=validateRecallScope(checked.data);if(!scope.ok)return scope;if(scope.data.actorId!==settings.actorId||own(local,'address')?.workflowId!==undefined&&own(local,'address').workflowId!==scope.data.workflowId)return fail('RECALL_ACTOR_MISMATCH','This Recall node does not match its authorized actor or workflow.');const after=localCurrent();return after??scope;};
 const preview=own(local,'preview')===true||own(local,'dryRun')===true||own(local,'target')!==undefined;
 let scope=current();if(!scope.ok)return scope;
 if(descriptor.id==='hotkey-arm'){
  const proposal=freeze({schemaVersion:1,type:'recall-arm-proposal',...settings});let registered=false;
  if(!preview&&typeof own(local,'registerRecallHotkey')==='function'){let result;try{result=safeCapability(await own(local,'registerRecallHotkey')(proposal));}catch{return fail('RECALL_HOTKEY_UNAVAILABLE','The trusted shortcut registration is unavailable.');}if(!result.ok)return result;if(!exact(result.data,['registered'])||result.data.registered!==true)return fail('RECALL_HOTKEY_UNAVAILABLE','The shortcut registration was not acknowledged.');scope=current();if(!scope.ok)return scope;registered=true;}
  return {ok:true,outputs:{proposal:{kind:'data',value:proposal}},reports:[{operation:'hotkey-arm',actualCalls:0,registered,armed:false}]};
 }
 if(preview)return skipped('RECALL_PREVIEW_NO_ACTIVATION','A target preview cannot reserve or consume the next Recall activation.');
 const disclosure=artifactVisibility(inputs);if(disclosure.kind==='hidden'||disclosure.kind==='actor-private'&&disclosure.actorId!==settings.actorId)return fail('RECALL_ACTOR_MISMATCH','Recall evidence must be permitted material for the selected actor.');
 const trigger=triggerFor(settings,inputs,descriptor.phase);if(!trigger.ok)return trigger;if(trigger.data.held)return skipped('RECALL_TRIGGER_UNRESOLVED','The automatic recall trigger is unresolved.','unresolved');
 if(settings.activation!=='armed'&&!settings.activation.startsWith('armed-or-')&&!trigger.data.automatic)return skipped('RECALL_TRIGGER_NOT_MATCHED','The automatic recall trigger did not match.');
 let activation;try{activation=own(session,'activate')({actorId:settings.actorId,memorySetId:settings.memorySetId,target:settings.target,...trigger.data});}catch{return fail('RECALL_ACTIVATION_FAILED','The trusted Recall activation failed.');}
 if(own(activation,'ok')!==true)return fail('RECALL_ACTIVATION_FAILED','The trusted Recall activation did not authorize this generation.');const activationData=own(activation,'data'),status=own(activationData,'status');if(status!=='activated'){const reason=own(activationData,'reason');return skipped(id(own(reason,'code'))?own(reason,'code'):'RECALL_NOT_ACTIVATED','Recall has no eligible contribution.',status==='unresolved'?'unresolved':'skipped');}
 const claim=own(activationData,'claim'),captured=cloneJsonValue(own(activationData,'activation'));let retained=false;
 try{
  if(!claim||!captured.ok||captured.data.value.stage!==descriptor.phase)return fail('RECALL_STAGE_MISMATCH','Recall activation must match the owned generation stage.');const active=captured.data.value;
  if(!inputs.presence)return fail('MISSING_INPUT','An activated recall requires actor presence at this scene stage.');const presence=presenceFor(inputs.presence.value,settings.actorId);if(!presence.ok)return presence;if(presence.data.status!=='present')return skipped(presence.data.status==='absent'?'ACTOR_ABSENT':'PRESENCE_UNRESOLVED','The actor is not confirmed in the scene.',presence.data.status==='absent'?'skipped':'unresolved');
  if(!inputs.records)return fail('MISSING_INPUT','An activated recall requires its explicit memory record input.');
  if(typeof own(local,'authorizeRecallRecords')!=='function')return fail('RECALL_RECORD_AUTHORIZATION_MISSING','The trusted host must authorize the exact supplied memory source.');
  let authorization;try{authorization=safeCapability(await own(local,'authorizeRecallRecords')(own(namedInputs,'records'),freeze({scope:scope.data,memorySetId:settings.memorySetId})));}catch{return fail('RECALL_RECORDS_UNAVAILABLE','The authorized memory source is unavailable.');}
  scope=current();if(!scope.ok)return scope;if(!authorization.ok)return authorization;if(!exact(authorization.data,['scope','memorySetId'])||!sameScope(authorization.data.scope,scope.data)||authorization.data.memorySetId!==settings.memorySetId)return fail('RECALL_RECORD_SCOPE_MISMATCH','The authorized source must match this user, chat, actor and memory set.');
  const selected=selectionFor(inputs.records,settings,scope.data);if(!selected.ok)return selected;if(!selected.data.records.length)return skipped('RECALL_EMPTY','No memory matched the authored filters.');
  if(typeof own(local,'countTokens')!=='function')return fail('RECALL_TOKENIZER_MISSING','Bind the trusted tokenizer for the Recall retrieval budget.');
  let tokens,tokenizerCalls=0;while(selected.data.records.length){let count;try{count=await own(local,'countTokens')(selected.data.text);}catch{return fail('RECALL_TOKENIZER_FAILED','The Recall tokenizer failed.');}tokenizerCalls++;scope=current();if(!scope.ok)return scope;const authorized=own(session,'checkClaim')(claim,{stage:descriptor.phase});if(!authorized.ok)return authorized;const unchanged=localCurrent();if(unchanged)return unchanged;tokens=own(count,'tokens');if(!Number.isSafeInteger(tokens)||tokens<0)return fail('RECALL_TOKENIZER_FAILED','Recall requires a bounded exact token count.');if(tokens<=settings.maxTokens)break;selected.data.records.pop();selected.data.omittedCount++;selected.data.text=[settings.title,...selected.data.records.map(record=>record.text)].join('\n');}
  if(!selected.data.records.length)return fail('RECALL_BUDGET_EXCEEDED','No matching whole memory fits the authored token budget.');
  if(typeof own(local,'stageRecallClaim')!=='function')return fail('RECALL_SETTLEMENT_MISSING','The host must retain the private consumption claim until successful or accepted settlement.');
  let staged;try{staged=safeCapability(await own(local,'stageRecallClaim')(claim,active));}catch{return fail('RECALL_STAGING_FAILED','The host could not retain this Recall claim.');}scope=current();if(!scope.ok)return scope;if(!staged.ok)return staged;if(!exact(staged.data,['staged'])||staged.data.staged!==true)return fail('RECALL_STAGING_FAILED','The private consumption claim was not retained.');const ownedClaim=own(session,'checkClaim')(claim,{stage:descriptor.phase});if(!ownedClaim.ok)return ownedClaim;const unchanged=localCurrent();if(unchanged)return unchanged;retained=true;
  const visibility={kind:'actor-private',actorId:scope.data.actorId},sourceRefs=selected.data.records.map(record=>({id:record.id,...(record.revision?{revision:record.revision}:{})}));
  return {ok:true,outputs:{out:{kind:'guidance',text:selected.data.text,scope:scope.data,visibility,acceptance:'pending',sourceRefs},records:{kind:'data',visibility,value:{schemaVersion:1,type:'recall-selection',scope:scope.data,memorySetId:settings.memorySetId,activationId:active.activationId,records:selected.data.records}},report:{kind:'data',visibility,value:{activationId:active.activationId,recordIds:selected.data.records.map(record=>record.id),omittedCount:selected.data.omittedCount,matchedCount:selected.data.matchedCount,tokens,tokenizerCalls,route:'actor-private-guidance',consumption:'pending'}}},reports:[{operation:'recall',actualCalls:0,selectedCount:selected.data.records.length,omittedCount:selected.data.omittedCount,private:true}]};
 }finally{if(claim&&!retained)try{own(session,'settle')(claim,{status:own(local,'signal')?.aborted?'cancelled':'failed'});}catch{/* The session remains scoped and cannot consume a failed activation. */}}
}
export async function executeRecallNode(node,inputs,local={}){try{return preserveArtifactPrivacy(await executeRaw(node,inputs,local),inputs);}catch{return fail(own(local,'signal')?.aborted?'ABORTED':'RECALL_FAILED','Recall failed without publishing private material.');}}
