import { builder } from './builder.mjs';
export function foundations() {
    const entries = [];
    let r;
    r = builder(1, 'Follow a reply from Send to Review', 'Trace one ordinary SillyTavern reply from its owned Send activation through generation to deliberate review.', 'On Send → Generate Reply → Review / Publish');
    r.steps = ['Inspect On Send.activation and Generate Reply.draft.', 'Confirm that opening this example does not assign or run it.'];
    r.check('generate', 'draft', 'The current generation owns this Draft; review publishes a new swipe only on Apply.');
    entries.push(r.finish());
    r = builder(2, 'Give this scene one clear direction', 'Use an editable text instruction as pre-generation Guidance.', 'Text and Compose Guidance');
    r.add('direction', 'text', { text: 'Give the scene one immediate, observable problem. Stop before choosing the player’s response.' }, 'scene direction');
    r.textGuidance('direction');
    r.check('guidance', 'out', 'The editable Text becomes Guidance before native generation.');
    r.steps = ['Edit Text · scene direction to one concrete instruction.', 'Trace section.Material into Compose.out and Generate Reply.guidance.'];
    r.experiments = [{ change: 'Replace the direction with a quiet sensory scene.', expect: 'The pre-generation Guidance changes without a model request.' }];
    entries.push(r.finish());
    r = builder(3, 'Give the planner only the context it needs', 'Select a small public scene window and observe what the planner omits.', 'Public Scene Context and Response Plan');
    r.add('scene', 'scene-context', { visibilityMode: 'public', includeCharacter: false, recentMessages: 4 }, 'public window');
    r.add('plan', 'response-plan', { instructions: 'Plan one next scene beat from only the public recent messages. Name what remains unknown; do not infer private motives.' }, 'bounded public plan');
    r.connect('scene', 'out', 'plan', 'in');
    r.connect('plan', 'out', 'generate', 'guidance');
    r.requirements = ['Bind Analysis to Active SillyTavern or a configured local model.'];
    r.steps = ['Inspect the Scene Context omission report for older/restricted material.', 'Compare the four-message context with the resulting one-beat plan.'];
    r.budget = '1 auxiliary Response Plan request; one ordinary native generation; no retries.';
    r.check('scene', 'out', 'Public recent context and omissions exclude restricted host material.');
    r.check('plan', 'out', 'One public next-beat plan reaches native Guidance.');
    entries.push(r.finish());
    r = builder(4, 'Give a specialist model a different job', 'Give an auxiliary Model Call its own system Instructions and pass its result into native Guidance.', 'Model Call Instructions and auxiliary binding');
    r.add('request', 'text', { text: 'Suggest a single environmental complication for the current scene. Keep it reversible.' }, 'specialist task');
    r.add('specialist', 'model-call', { instructions: 'You are a concise scene designer. Return one practical complication, preserve player agency, and never write the finished reply.', modelRole: 'SceneDesigner' }, 'separate job');
    r.connect('request', 'out', 'specialist', 'prompt');
    r.textGuidance('specialist');
    r.requirements = ['Set SceneDesigner to Active SillyTavern or choose a different configured local auxiliary model.'];
    r.steps = ['Inspect Model Call.instructions: this is the auxiliary system message.', 'Change the auxiliary binding independently of ordinary native generation.'];
    r.budget = '1 auxiliary Model Call request; one ordinary native generation; no retries.';
    r.check('specialist', 'out', 'A specialist suggestion becomes material for Compose Guidance.');
    entries.push(r.finish());
    r = builder(5, 'Reuse a prompt block from SillyTavern', 'Read a real configured prompt block as raw or resolved material for guidance.', 'Prompt Source raw and resolved');
    r.add('prompt', 'prompt-source', { source: 'system', promptId: 'main', form: 'raw' }, 'existing main block');
    r.textGuidance('prompt');
    r.requirements = ['Choose an existing SillyTavern prompt ID; the portable default is main.'];
    r.steps = ['Inspect Prompt Source.out before sending.', 'Toggle form raw/resolved to observe substitutions; this text is material, not Model Call Instructions.'];
    r.check('prompt', 'out', 'A selected prompt block is read without inventing a new system operation.');
    r.experiments = [{ change: 'Set form to resolved.', expect: 'Substitutions use the current host context; the block remains input material.' }];
    entries.push(r.finish());
    r = builder(6, 'Bring a lore sheet into the scene', 'Load an imported UTF-8 snapshot, decode JSON, and select only the current location facts.', 'File Input snapshot, JSON Decode, Select Fields');
    r.add('lore', 'file-input', { fileName: 'harbor-lore.json', content: JSON.stringify({ location: 'North Harbor', constraint: 'The lighthouse is dark.', unrelated: 'A distant kingdom holds a festival.' }), loaded: true }, 'imported snapshot');
    r.add('decode', 'json-decode');
    r.connect('lore', 'out', 'decode', 'in');
    r.add('selection', 'select-fields', { fields: [{ name: 'location', path: ['location'] }, { name: 'constraint', path: ['constraint'] }] }, 'scene facts');
    r.connect('decode', 'out', 'selection', 'in');
    r.guidance('selection');
    r.steps = ['Inspect the imported snapshot content; it does not read a live file.', 'Select location and constraint while omitting unrelated lore.', 'For plain text, remove JSON Decode and Select Fields, then connect File Input.out to a Compose text section.'];
    r.check('selection', 'out', 'Only location and constraint reach Guidance.');
    r.experiments = [{ change: 'Replace snapshot content with plain text.', expect: 'JSON Decode holds until you use the documented direct text-section route.' }];
    r.fixtures['harbor-lore.json'] = { location: 'North Harbor', constraint: 'The lighthouse is dark.', unrelated: 'A distant kingdom holds a festival.' };
    entries.push(r.finish());
    r = builder(7, 'Let a second model polish the narration', 'Apply pre-generation direction, then revise only narration while preserving protected literals.', 'Revise Draft narration scope');
    r.add('direction', 'text', { text: 'Describe the scene through concrete sounds and movement; preserve dialogue and player agency.' });
    r.textGuidance('direction');
    r.add('polish', 'revise-draft', { scope: 'narration', protectedLiterals: ['North Harbor'], instructions: 'Tighten repetition and sentence rhythm. Preserve facts, chronology, all dialogue and North Harbor exactly.' }, 'narration pass');
    r.connect('generate', 'draft', 'polish', 'draft');
    r.requirements = ['Bind Prose to Active SillyTavern or a chosen local model.'];
    r.steps = ['Compare the native Draft with the narration-only revision before Apply.'];
    r.budget = '1 auxiliary Revise Draft request after one ordinary native generation.';
    r.check('polish', 'out', 'Narration changes; dialogue and the protected literal remain unchanged.');
    entries.push(r.finish('polish', 'out'));
    r = builder(8, 'Add an Observed Items dropdown', 'Extract literal item mentions from the owned generation snapshot and append public notes to the current owned Draft.', 'Reply Snapshot, literal Extract, Render Notes, Append');
    r.add('snapshot', 'reply-snapshot', {}, 'owned generation snapshot');
    r.add('items', 'extract', { mode: 'literal', patterns: [{ id: 'lantern', literal: 'lantern', label: 'Lantern' }, { id: 'map', literal: 'map', label: 'Map' }], phase: 'post' }, 'literal observed items');
    r.connect('snapshot', 'out', 'items', 'source');
    const draft = r.notes('items');
    r.steps = ['In an owned Send, Reply Snapshot reads the cached original just-generated reply. A bounded Run-to-here preview instead reads the latest existing completed assistant entry.', 'The new native Draft continues to Append and Review; the snapshot is an immutable source view, while the owned Draft continues to review.'];
    r.check('items', 'out', 'Literal records retain exact offsets and quotes; a mention grants no inventory ownership.');
    r.check('append', 'out', 'Public dropdown notes are appended to the newly owned Draft.');
    r.cases = [{ when: 'No literal match', expect: 'Empty notes leave an ordinary usable Draft.' }];
    entries.push(r.finish(...draft));
    return entries;
}
