import {test,expect} from '@playwright/test';
async function launch(page){
 await page.route('**/scripts/user.js',route=>route.fulfill({contentType:'text/javascript',body:"export function getCurrentUserHandle(){return 'default-user';}"}));
 await page.route('**/script.js',route=>route.fulfill({contentType:'text/javascript',body:'export const isGenerating=()=>false;export const syncMesToSwipe=()=>true;export const syncSwipeToMes=()=>true;'}));
 await page.goto('/tests/browser/harness.html');await page.waitForFunction(()=>!!window.canvasHarness);
 await page.evaluate(async()=>{const h=window.canvasHarness,c=h.context;c.chatId='Story-2';c.characterId=0;c.groupId=null;c.characters=[{avatar:'mara.png',data:{name:'Mara'}}];c.chat=[{mes:'Mara waits in the harbor.',is_user:true,extra:{}}];const {starterGraph}=await import('/src/workflow/starters.js?v='+h.version),{operationDefaults}=await import('/src/workflow/catalog.js?v='+h.version),graph=starterGraph('unified-basic');for(const [id,operation,x,y]of [['shortcut','hotkey-arm',200,360],['recall-a','recall',500,360],['recall-b','recall',800,360]])graph.nodes[id]={...operationDefaults(operation),id,type:'workflow',actorId:'character:mara.png',memorySetId:'moments',x,y};await h.activate(graph);await h.view({x:10,y:10,zoom:1});});
 await page.getByRole('checkbox',{name:'Enable Lattice',exact:true}).check();
}
const card=(page,id)=>page.locator('.pc-node[data-id="'+id+'"]');
async function status(page,action){await page.evaluate(async action=>{const h=window.canvasHarness,r=await import('/src/run.js?v='+h.version),result=r.getNativeWorkflowController()[action+'Recall']('shortcut');if(!result.ok)throw Error(JSON.stringify(result.error));await h.settle();},action);}
test('shared queued badges preserve card geometry, drafts, focus and authoring state',async({page})=>{
 await launch(page);await page.evaluate(()=>{const h=window.canvasHarness;h.canvas.select({kind:'node',id:'recall-a'});});
 const toggle=page.getByRole('button',{name:'Toggle inspector',exact:true});if(await toggle.getAttribute('aria-pressed')!=='true')await toggle.click();
 const region=page.getByRole('region',{name:'Node details',exact:true}),editor=region.getByLabel('Tags',{exact:true});await editor.fill('unfinished filter');await editor.focus();const before=await page.evaluate(()=>{const h=window.canvasHarness;window.recallCard=document.querySelector('.pc-node[data-id="recall-a"]');window.recallEditor=document.querySelector('[aria-label="Tags"]');return {graph:JSON.stringify(h.graph),box:window.recallCard.getBoundingClientRect().toJSON(),undo:h.H.canUndo?.(h.graph)};});
 await status(page,'queue');await expect(page.locator('.pc-node-recall-status')).toHaveCount(3);await expect(region.getByRole('status')).toContainText('Queued for next reply');await expect(editor).toHaveValue('unfinished filter');await expect(editor).toBeFocused();
 const after=await page.evaluate(()=>{const h=window.canvasHarness;return {sameCard:window.recallCard===document.querySelector('.pc-node[data-id="recall-a"]'),sameEditor:window.recallEditor===document.querySelector('[aria-label="Tags"]'),graph:JSON.stringify(h.graph),box:window.recallCard.getBoundingClientRect().toJSON(),undo:h.H.canUndo?.(h.graph),calls:h.providerCalls()};});expect(after.sameCard).toBe(true);expect(after.sameEditor).toBe(true);expect(after.graph).toBe(before.graph);expect(after.box).toEqual(before.box);expect(after.undo).toBe(before.undo);expect(after.calls).toBe(0);await page.screenshot({path:'.superpowers/sdd/2026-10-10-canvas-memory-recall/canvas-queued.png'});
 await status(page,'cancel');await expect(page.locator('.pc-node-recall-status')).toHaveCount(0);
});
test('selected-node context queues one shared set and badge opens Details without toggling',async({page})=>{
 await launch(page);await page.evaluate(()=>{const h=window.canvasHarness;h.canvas.setMulti(['shortcut','recall-a','recall-b']);});await card(page,'recall-a').click({button:'right'});const menu=page.getByRole('menu',{name:'Selection actions',exact:true});await expect(menu.getByRole('menuitem',{name:'Queue recall for 3 nodes',exact:true})).toBeEnabled();await menu.getByRole('menuitem',{name:'Queue recall for 3 nodes',exact:true}).click();await expect(page.locator('.pc-node-recall-status')).toHaveCount(3);
 const count=await page.evaluate(async()=>{const h=window.canvasHarness,r=await import('/src/run.js?v='+h.version);return r.getNativeWorkflowController().statusRecall().data.requests.filter(x=>x.queued).length;});expect(count).toBe(1);
 await card(page,'recall-a').getByRole('button',{name:/Memory recall:/}).click();await expect(page.getByRole('region',{name:'Memory recall',exact:true})).toBeVisible();await expect(page.locator('.pc-node-recall-status')).toHaveCount(3);expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);
});
test('compact overview badges retain minimum painted size and identical document replacement expires queues',async({page})=>{
 await launch(page);await page.evaluate(async()=>{const h=window.canvasHarness,g=structuredClone(h.graph);g.nodes['recall-a'].presentation={compact:true};await h.activate(g);});await status(page,'queue');await page.evaluate(async()=>window.canvasHarness.view({x:50,y:50,zoom:.25}));const icon=card(page,'recall-a').locator('.pc-node-recall-status svg');await expect(icon).toBeVisible();const box=await icon.boundingBox();expect(box.width).toBeGreaterThanOrEqual(9.9);expect(box.height).toBeGreaterThanOrEqual(9.9);
 await page.getByRole('checkbox',{name:'Enable Lattice',exact:true}).uncheck();await expect(page.locator('.pc-node-recall-status')).toHaveCount(0);await page.evaluate(async()=>{const h=window.canvasHarness;await h.activate(structuredClone(h.graph));});await page.getByRole('checkbox',{name:'Enable Lattice',exact:true}).check();await expect(page.locator('.pc-node-recall-status')).toHaveCount(0);
});

test('Node submenu exposes scoped global controls and a single-heading grouped overview',async({page})=>{
 await launch(page);await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Memory recall',exact:true}).focus();await page.keyboard.press('ArrowRight');const submenu=page.getByRole('menu',{name:'Memory recall options',exact:true});await expect(submenu.getByRole('menuitem',{name:'Queue recall for selected nodes',exact:true})).toBeDisabled();await submenu.getByRole('menuitem',{name:'Queue recall for all eligible nodes',exact:true}).click();await expect(page.locator('.pc-node-recall-status')).toHaveCount(3);
 await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Memory recall',exact:true}).hover();await page.getByRole('menuitem',{name:'Memory recall overview…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Memory recall',exact:true});await expect(dialog.getByRole('heading',{name:'Memory recall',exact:true})).toHaveCount(1);await expect(dialog.locator('[data-recall-set]')).toHaveCount(1);await page.screenshot({path:'.superpowers/sdd/2026-10-10-canvas-memory-recall/recall-overview.png'});await dialog.getByRole('button',{name:'Cancel recall moments',exact:true}).click();await expect(page.locator('.pc-node-recall-status')).toHaveCount(0);await dialog.getByRole('button',{name:'Close',exact:true}).click();
 await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Configure',exact:true}).hover();await expect(page.getByRole('menu',{name:'Configure options',exact:true})).not.toContainText('recall');await page.keyboard.press('Escape');expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);
});

test('focused Memory recall menu entries isolate graph keyboard commands',async({page})=>{await launch(page);await page.evaluate(()=>window.canvasHarness.canvas.select({kind:'node',id:'recall-a'}));const before=await page.evaluate(()=>JSON.stringify(window.canvasHarness.graph));await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Memory recall',exact:true}).focus();await page.keyboard.press('ArrowRight');await page.getByRole('menuitem',{name:'Queue recall for selected nodes',exact:true}).focus();await page.keyboard.press('Delete');await page.keyboard.press('c');expect(await page.evaluate(()=>JSON.stringify(window.canvasHarness.graph))).toBe(before);await page.keyboard.press('Escape');await expect(page.getByRole('menu',{name:'Memory recall options',exact:true})).toHaveCount(0);});


test('nested views retain root-wide recall controls and reveal each linked root node',async({page})=>{
 await launch(page);await page.evaluate(async()=>{const h=window.canvasHarness,{computeDefinitionIdentity,definitionRefKey}=await import('/src/workflow/definitions.js?v='+h.version),checked=computeDefinitionIdentity({id:'recall-child',version:1,name:'Recall child',parameters:[],interface:[],body:{schema:3,runtime:2,mode:'native-pre',nodes:{'recall-a':{id:'recall-a',type:'workflow',operation:'text',text:'child'}},wires:{}}});if(!checked.ok)throw Error(JSON.stringify(checked.error));const definition={...checked.data.materializedDefinition,semanticHash:checked.data.semanticHash},g=structuredClone(h.graph);g.definitions[definitionRefKey(definition)]=definition;g.nodes.child={id:'child',type:'subgraph',definition:{id:definition.id,version:definition.version,semanticHash:definition.semanticHash},parameterOverrides:{},roleOverrides:{},nodeBindingOverrides:{},x:50,y:500};await h.activate(g);h.canvas.hooks.onOpen(h.graph.nodes.child);await h.view({x:320,y:180,zoom:1});await h.settle();});
 await expect(card(page,'recall-a')).toBeVisible();await page.evaluate(()=>window.canvasHarness.canvas.select({kind:'node',id:'recall-a'}));await expect(page.getByRole('region',{name:'Memory recall',exact:true})).toHaveCount(0);await card(page,'recall-a').click({button:'right'});await expect(page.getByRole('menu',{name:'Node actions',exact:true})).not.toContainText('Queue recall');await page.keyboard.press('Escape');await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Memory recall',exact:true}).hover();await page.getByRole('menuitem',{name:'Queue recall for all eligible nodes',exact:true}).click();await expect(page.locator('.pc-node-recall-status')).toHaveCount(0);
 await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Memory recall',exact:true}).hover();await page.getByRole('menuitem',{name:'Memory recall overview…',exact:true}).click();const dialog=page.getByRole('dialog',{name:'Memory recall',exact:true});await expect(dialog.getByRole('button',{name:'Recalled memories · recall-a',exact:true})).toBeVisible();await expect(dialog.getByRole('button',{name:'Recalled memories · recall-b',exact:true})).toBeVisible();await dialog.getByRole('button',{name:'Recalled memories · recall-b',exact:true}).click();await expect(card(page,'recall-b')).toBeVisible();await expect(page.getByRole('region',{name:'Memory recall',exact:true})).toContainText('Queued');expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);
});


test('pending badges use amber and state markers while preserving their cards',async({page})=>{await launch(page);await status(page,'queue');const badge=card(page,'recall-a').locator('.pc-node-recall-status'),ready=await badge.evaluate(el=>getComputedStyle(el).color);await page.evaluate(()=>{window.recallBadgeCard=document.querySelector('.pc-node[data-id="recall-a"]');window.canvasHarness.canvas.setRecallStatus({'recall-a':{state:'generation',tooltip:'Recall reserved for this generation',ariaLabel:'Memory recall: reserved'}});});await expect(badge.locator('.pc-recall-marker')).toHaveCount(1);const pending=await badge.evaluate(el=>getComputedStyle(el).color);expect(pending).not.toBe(ready);await page.screenshot({path:'.superpowers/sdd/2026-10-10-canvas-memory-recall/canvas-reserved.png'});await page.evaluate(()=>window.canvasHarness.canvas.setRecallStatus({'recall-a':{state:'acceptance',tooltip:'Recall awaiting acceptance',ariaLabel:'Memory recall: awaiting acceptance'}}));await expect(badge.locator('.pc-recall-marker')).toHaveCount(1);expect(await badge.evaluate(el=>getComputedStyle(el).color)).toBe(pending);expect(await page.evaluate(()=>window.recallBadgeCard===document.querySelector('.pc-node[data-id="recall-a"]'))).toBe(true);});


test('badge keyboard activation opens Details without changing the shared queue',async({page})=>{await launch(page);await status(page,'queue');const badge=card(page,'recall-a').getByRole('button',{name:/Memory recall:/});for(const key of ['Enter','Space']){await badge.focus();await page.keyboard.press(key);await expect(page.getByRole('region',{name:'Memory recall',exact:true})).toContainText('Queued');await expect(page.locator('.pc-node-recall-status')).toHaveCount(3);}await page.screenshot({path:'.superpowers/sdd/2026-10-10-canvas-memory-recall/recall-details.png'});expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);});

test('stale menu captures report a recoverable error without partially queueing',async({page})=>{await launch(page);await page.evaluate(async()=>{const h=window.canvasHarness,g=structuredClone(h.graph);g.nodes.other={...g.nodes.shortcut,id:'other',memorySetId:'other',hotkey:{code:'KeyT',ctrl:true,shift:true,alt:false,meta:false},x:50,y:450};await h.activate(g);});await page.getByRole('menuitem',{name:'Workflow',exact:true}).click();await page.getByRole('menuitem',{name:'Memory recall',exact:true}).hover();await page.evaluate(async()=>{const h=window.canvasHarness,r=await import('/src/run.js?v='+h.version);const queued=r.getNativeWorkflowController().queueRecall('other');if(!queued.ok)throw Error(JSON.stringify(queued.error));await h.settle();});await page.getByRole('menuitem',{name:'Queue recall for all eligible nodes',exact:true}).click();const result=await page.evaluate(async()=>{const h=window.canvasHarness,r=await import('/src/run.js?v='+h.version);return {requests:r.getNativeWorkflowController().statusRecall().data.requests,toasts:h.toasts};});expect(result.requests.filter(r=>r.queued).map(r=>r.memorySetId)).toEqual(['other']);expect(result.toasts.at(-1).type).toBe('error');expect(result.toasts.at(-1).message).toMatch(/changed|reopen/i);expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);});
