import {test,expect} from '@playwright/test';
async function launch(page){
 await page.route('**/scripts/user.js',route=>route.fulfill({contentType:'text/javascript',body:"export function getCurrentUserHandle(){return 'default-user';}"}));
 await page.route('**/script.js',route=>route.fulfill({contentType:'text/javascript',body:'export const isGenerating=()=>false;export const syncMesToSwipe=()=>true;export const syncSwipeToMes=()=>true;'}));
 await page.goto('/tests/browser/harness.html');await page.waitForFunction(()=>!!window.canvasHarness);
 await page.evaluate(async()=>{const h=window.canvasHarness,c=h.context;c.chatId='Story-2';c.characterId=0;c.groupId=null;c.characters=[{avatar:'mara.png',data:{name:'Mara'}}];c.chat=[{mes:'Mara waits in the harbor.',is_user:true,extra:{}}];c.extensionSettings.connectionManager={profiles:[{id:'analysis',name:'Analysis connection',api:'openai',model:'analysis-model',preset:null},{id:'creative',name:'Creative connection',api:'openai',model:'creative-model',preset:null}]};c.CONNECT_API_MAP={openai:{selected:'openai',source:'openai'}};c.ConnectionManagerRequestService.getProfile=id=>c.extensionSettings.connectionManager.profiles.find(p=>p.id===id);document.dispatchEvent(new CustomEvent('pc-state'));await h.settle();});
}
async function assign(page){await page.getByRole('button',{name:'Workflows',exact:true}).click();await page.getByRole('menuitem',{name:'Assign unified workflow',exact:true}).click();await expect(page.locator('.pc-root-workflow-status')).toContainText('unified · Assigned');await page.getByRole('checkbox',{name:'Arm',exact:true}).check();}
async function tool(page,name){await page.getByRole('button',{name:'Tools',exact:true}).click();await page.getByRole('menuitem',{name,exact:true}).click();}
test('unified wand helper models can be bound through actual Details without changing the pinned helper',async({page})=>{
 await launch(page);await page.evaluate(async()=>{const h=window.canvasHarness,{UNIFIED_WORKFLOW_EXAMPLE_DATA}=await import('/src/workflow/unified-example-data.js?v='+h.version),graph=structuredClone(UNIFIED_WORKFLOW_EXAMPLE_DATA.find(e=>e.id==='unified-broken-wand').packages[0].graph);await h.activate(graph);h.canvas.select({kind:'node',id:'confirm-each'});});
 const toggle=page.getByRole('button',{name:'Toggle inspector',exact:true});if(await toggle.getAttribute('aria-pressed')!=='true')await toggle.click();
 const region=page.getByRole('region',{name:'Node details',exact:true});const group=region.locator('details[data-helper-model-controls]');if(!await group.evaluate(el=>el.open))await group.locator('summary').click();
 const before=await page.evaluate(()=>structuredClone(window.canvasHarness.graph.definitions));
 await region.getByLabel('decision connection profile',{exact:true}).selectOption('analysis');await expect(region.getByLabel('decision model mode',{exact:true})).toHaveValue('block');
 await region.getByLabel('decision model mode',{exact:true}).selectOption('override');await region.getByLabel('decision model identifier',{exact:true}).fill('custom-check-model');await region.getByLabel('decision model identifier',{exact:true}).blur();
 expect(await page.evaluate(()=>window.canvasHarness.graph.nodes['confirm-each'].roleOverrides)).toEqual({decision:{profileId:'analysis',model:'custom-check-model'}});expect(await page.evaluate(()=>window.canvasHarness.graph.definitions)).toEqual(before);
 await assign(page);expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);
});
test('Story-2 document authorization and scoped Recall hotkeys work through shipped UI',async({page})=>{
 await launch(page);await page.evaluate(async()=>{const h=window.canvasHarness,{operationDefaults}=await import('/src/workflow/catalog.js?v='+h.version);const graph=structuredClone(h.graph);graph.id='browser-recall';graph.name='Browser recall';graph.nodes.arm={...operationDefaults('hotkey-arm'),id:'arm',type:'workflow',actorId:'character:mara.png',memorySetId:'mara-moments',x:400,y:700,w:270,h:200};await h.activate(graph);});await assign(page);
 await tool(page,'Story documents…');const documents=page.getByRole('dialog',{name:'Story documents',exact:true});await expect(documents).toContainText('default-user');await expect(documents).toContainText('Story-2');await documents.getByLabel('Logical target ID',{exact:true}).fill('story-clock');await documents.getByLabel('Document name',{exact:true}).fill('Campaign clock');await documents.getByText('Story clock template',{exact:true}).click();await documents.getByLabel('Calendar ID',{exact:true}).fill('campaign-days');await documents.getByLabel('Starting story minute',{exact:true}).fill('840');await documents.getByRole('button',{name:'Use story clock template',exact:true}).click();expect(JSON.parse(await documents.getByLabel('Initial template',{exact:true}).inputValue()).absoluteMinute).toBe(840);await documents.getByRole('button',{name:'Save authorization',exact:true}).click();await expect(documents.getByRole('status')).toContainText('authorization updated locally');await documents.getByRole('button',{name:'Close',exact:true}).click();
 await tool(page,'Recall arms…');const recall=page.getByRole('dialog',{name:'Recall arms',exact:true});await expect(recall).toContainText('Actor character:mara.png');await recall.getByRole('button',{name:'Arm mara-moments',exact:true}).click();await expect(recall.getByRole('button',{name:'Disarm mara-moments',exact:true})).toBeVisible();await recall.getByRole('button',{name:'Disarm mara-moments',exact:true}).click();await recall.getByRole('button',{name:'Close',exact:true}).click();
 await page.keyboard.press('Control+Shift+KeyR');await tool(page,'Recall arms…');await expect(recall.getByRole('button',{name:'Disarm mara-moments',exact:true})).toBeVisible();await recall.getByRole('button',{name:'Disarm mara-moments',exact:true}).click();await recall.getByRole('button',{name:'Close',exact:true}).click();
 await tool(page,'Story documents…');await documents.getByLabel('Logical target ID',{exact:true}).focus();await page.keyboard.press('Control+Shift+KeyR');await documents.getByRole('button',{name:'Close',exact:true}).click();await tool(page,'Recall arms…');await expect(recall.getByRole('button',{name:'Arm mara-moments',exact:true})).toBeVisible();expect(await page.evaluate(()=>window.canvasHarness.providerCalls())).toBe(0);
});
