import assert from 'node:assert/strict';
import { mkdtempSync, mkdirSync, copyFileSync, writeFileSync, readFileSync } from 'node:fs';
import { join } from 'node:path';
import { tmpdir } from 'node:os';
import { spawnSync } from 'node:child_process';
const root = mkdtempSync(join(tmpdir(), 'lattice-version-test-'));
mkdirSync(join(root, 'tools')); mkdirSync(join(root, 'src', 'canvas'), { recursive: true });
mkdirSync(join(root, 'tests', 'browser'), { recursive: true });
copyFileSync(new URL('../tools/bump-version.mjs', import.meta.url), join(root, 'tools', 'bump-version.mjs'));
writeFileSync(join(root, 'manifest.json'), JSON.stringify({ version: '0.1.0', js: 'index.js?v=0.1.0' }));
writeFileSync(join(root, 'index.js'), "import { x } from './src/state.js?v=0.1.0';");
writeFileSync(join(root, 'src', 'state.js'), 'export const x = 1;');
writeFileSync(join(root, 'src', 'canvas', 'presentation.js'), "import { x } from '../state.js?v=0.1.0';");
writeFileSync(join(root, 'style.css'), "@import url('./dist/lattice.css?v=0.1.0');");
writeFileSync(join(root, 'package.json'), JSON.stringify({ version: '0.1.0' }));
writeFileSync(join(root, 'package-lock.json'), JSON.stringify({ version: '0.1.0', packages: { '': { version: '0.1.0' } } }));
writeFileSync(join(root, 'tests', 'browser', 'cache.spec.mjs'), "import { x } from '../../src/state.js?v=0.1.0';\nconst same = await import('../../src/state.js?v=0.1.0');\nconst helper = await import('../../src/helper.js');");
const result = spawnSync(process.execPath, [join(root, 'tools', 'bump-version.mjs'), '0.2.0'], { encoding: 'utf8' });
assert.equal(result.status, 0, result.stderr);
assert.match(readFileSync(join(root, 'src', 'canvas', 'presentation.js'), 'utf8'), /state\.js\?v=0\.2\.0/, 'nested native modules use the same domain URL as the extension entry');
const browser = readFileSync(join(root, 'tests', 'browser', 'cache.spec.mjs'), 'utf8');
assert.equal((browser.match(/state\.js\?v=0\.2\.0/g) ?? []).length, 2, 'static and dynamic test imports share the released domain URL');
assert.ok(browser.includes("import('../../src/helper.js')"), 'unversioned test helpers remain unchanged');
assert.match(readFileSync(join(root, 'style.css'), 'utf8'), /lattice\.css\?v=0\.2\.0/);
assert.equal(JSON.parse(readFileSync(join(root, 'manifest.json'), 'utf8')).js, 'index.js?v=0.2.0');
assert.equal(JSON.parse(readFileSync(join(root, 'package.json'), 'utf8')).version, '0.2.0');
const lock = JSON.parse(readFileSync(join(root, 'package-lock.json'), 'utf8'));
assert.equal(lock.version, '0.2.0');
assert.equal(lock.packages[''].version, '0.2.0');
console.log('bump-version: ok');
