import assert from 'node:assert/strict';
import { fixture, dom, mouse } from './canvas-fixture.mjs';
const request = globalThis.requestAnimationFrame, cancel = globalThis.cancelAnimationFrame;
let sequence = 0; const frames = new Map();
globalThis.requestAnimationFrame = callback => { frames.set(++sequence, callback); return sequence; };
globalThis.cancelAnimationFrame = id => frames.delete(id);
const { host, canvas } = fixture();
const card = host.querySelector('.pc-node');
const path = host.querySelector('.pc-wire');
const d = path.getAttribute('d');
canvas.zoomBy(1.2, 200, 200);
assert.equal(host.querySelector('.pc-node'), card, 'zoom preserves card identity');
assert.equal(host.querySelector('.pc-wire'), path, 'zoom preserves wire identity');
assert.equal(path.getAttribute('d'), d, 'camera movement leaves graph-space wire geometry untouched');
let transforms = 0;
const apply = canvas.applyTransform.bind(canvas);
canvas.applyTransform = () => { transforms++; apply(); };
for (let i = 0; i < 3; i++) host.dispatchEvent(new dom.window.WheelEvent('wheel', { deltaY: -1, clientX: 200, clientY: 200, bubbles: true, cancelable: true }));
assert.equal(frames.size, 1, 'a burst of wheel input requests one frame');
const callbacks = [...frames.values()]; frames.clear(); callbacks.forEach(callback => callback(16));
assert.equal(transforms, 1, 'a burst of wheel input paints the camera once per frame');
canvas.cancelGesture();
globalThis.requestAnimationFrame = request; globalThis.cancelAnimationFrame = cancel;
const height = Object.getOwnPropertyDescriptor(dom.window.HTMLElement.prototype, 'offsetHeight');
let measurements = 0;
Object.defineProperty(dom.window.HTMLElement.prototype, 'offsetHeight', { configurable: true, get() { if (this.matches('.pc-node')) measurements++; return height.get.call(this); } });
canvas.render();
assert.ok(measurements <= Object.keys(canvas.graph.nodes).length, 'a render measures each card at most once before drawing wires');
Object.defineProperty(dom.window.HTMLElement.prototype, 'offsetHeight', height);
const prompts = Object.values(canvas.graph.nodes).filter(n => n.type === 'workflow');
canvas.setMulti(prompts.map(n => n.id));
const cards = prompts.map(n => host.querySelector(`.pc-node[data-id="${n.id}"]`));
mouse(cards[0], 'mousedown', 80, 80); mouse(window, 'mousemove', 120, 110);
await new Promise(resolve => setTimeout(resolve, 25));
assert.equal(host.querySelector(`.pc-node[data-id="${prompts[0].id}"]`), cards[0], 'multi-drag preserves card identity');
assert.equal(host.querySelector(`.pc-node[data-id="${prompts[1].id}"]`), cards[1], 'other selected cards remain mounted');
mouse(window, 'mouseup', 120, 110);
await canvas.destroy();
console.log('canvas-performance: ok');
