import assert from 'node:assert/strict';
import { fixture, S, mouse } from './canvas-fixture.mjs';
let resolveAnswer;
const pending = new Promise(resolve => { resolveAnswer = resolve; });
const { canvas, graph, a } = fixture({ confirmDelete: () => pending });
canvas.select({ kind: 'node', id: a.id });
const deletion = canvas.deleteSelection();
const replacement = structuredClone(graph); replacement.id = 'other-graph';
const before = JSON.stringify(replacement.nodes);
canvas.setGraph(replacement);
resolveAnswer(true);
assert.equal(await deletion, false, 'graph switch cancels an outstanding delete confirmation');
assert.equal(JSON.stringify(replacement.nodes), before, 'a delayed answer cannot delete from the newly opened graph');
assert.ok(graph.nodes[a.id], 'the old graph stays untouched when its operation was cancelled');
let resolveMember;
const member = new Promise(resolve => { resolveMember = resolve; });
const linkFixture = fixture({ onPickMember: () => member });
const { canvas: linkCanvas, graph: linkGraph, a: first, b: second, host } = linkFixture;
linkGraph.wires = {};
const group = S.groupNodes(linkGraph, [first.id, second.id], 'Folded');
const target = S.outputNode(linkGraph);
linkCanvas.render();
mouse(host.querySelector('.pc-gport[data-gport="out"]'), 'mousedown', 180, 100);
document.elementFromPoint = () => host.querySelector(`.pc-node[data-id="${target.id}"]`);
mouse(window, 'mouseup', target.x, target.y);
const other = structuredClone(linkGraph); other.id = 'another-graph';
linkCanvas.setGraph(other);
resolveMember({ id: first.id, port: null });
await new Promise(resolve => setTimeout(resolve, 5));
assert.equal(Object.keys(other.wires).length, 0, 'a deferred folded-group picker cannot wire the next graph');
assert.equal(Object.keys(linkGraph.wires).length, 0, 'the cancelled wire does not alter the old graph');
const removed = fixture();
await removed.canvas.destroy();
mouse(removed.host, 'mousedown', 80, 80);
mouse(window, 'mousemove', 130, 130);
mouse(window, 'mouseup', 130, 130);
assert.deepEqual([removed.a.x, removed.a.y], [50, 50], 'destroy releases window and host gesture listeners');
assert.equal(removed.canvas.marquee, null, 'no new host gesture starts after destroy');
assert.equal(removed.host.querySelector('.pc-viewport'), null, 'the Svelte layer is unmounted');
const wheeled = fixture();
wheeled.host.dispatchEvent(new window.WheelEvent('wheel', { deltaY: -120, clientX: 240, clientY: 160, bubbles: true, cancelable: true }));
assert.ok(wheeled.graph.view.zoom > 1, 'wheel input advances the camera before its scheduled paint');
window.dispatchEvent(new window.Event('resize'));
assert.equal(wheeled.canvas.viewport.style.transform, `translate(${wheeled.graph.view.x}px, ${wheeled.graph.view.y}px) scale(${wheeled.graph.view.zoom})`, 'cancelling a pending wheel frame reconciles the displayed camera with its saved coordinates');
await new Promise(resolve => setTimeout(resolve, 10));
assert.equal(wheeled.canvas.viewport.style.transform, `translate(${wheeled.graph.view.x}px, ${wheeled.graph.view.y}px) scale(${wheeled.graph.view.zoom})`, 'a cancelled frame cannot restore an older camera');
await wheeled.canvas.destroy();
console.log('canvas-lifecycle: ok');
