import assert from 'node:assert/strict';
import { createWorkflowDocumentSession } from '../src/ui/document-session.js';

const graph = () => ({ id: 'same-id', name: 'Draft', schema: 3, runtime: 2, mode: 'native-unified', nodes: { text: { id: 'text', type: 'workflow', operation: 'text', text: 'before' } }, wires: {} });
const session = createWorkflowDocumentSession(), g = graph();
assert.equal(session.current(), null);
assert.equal(session.dirty(), false);
const notices = [], unsubscribe = session.subscribe(event => notices.push(event));
session.activate(g, { clean: true, source: { name: 'draft.json', kind: 'upload' } });
const token = session.capture(), before = session.snapshot();
assert.equal(session.dirty(), false);
g.updatedAt = 42; g.view = { x: 30, y: 60, zoom: 2 }; g.recording = { output: 'private' }; g.nodes.text.result = 'private';
assert.equal(session.snapshot(), before, 'timestamps, camera and runtime output cannot mark authored work dirty');
g.nodes.text.text = 'after';
assert.equal(session.dirty(), true);
assert.equal(session.markSaved(token, before, { kind: 'native', name: 'saved.json' }), true);
assert.equal(session.dirty(), true, 'a write of an older snapshot cannot mark newer edits clean');
assert.equal(session.source().name, 'saved.json');
assert.equal(session.markSaved(token, session.snapshot(), session.source()), true);
assert.equal(session.dirty(), false);
session.activate(graph(), { source: { sourceName: 'Recovered document' } });
assert.equal(session.stillCurrent(token), false, 'same graph ID cannot extend an old activation');
assert.equal(session.markSaved(token, before, { name: 'wrong.json' }), false);
assert.equal(session.source().sourceName, 'Recovered document');
assert.equal(session.dirty(), true, 'detached unsaved activation has no disk checkpoint');
session.source({ sourceName: 'Recovered renamed' });
assert.equal(session.source().sourceName, 'Recovered renamed');
unsubscribe();
assert.equal(notices.length, 5);

const views = { version: 1, workflowId: 'same-id', activeKey: '["root","same-id"]', views: [{ identity: { kind: 'root', workflowId: 'same-id' }, open: true, camera: { x: 0, y: 0, zoom: 1 }, selection: { primary: null, multi: [] }, inspector: { item: null, section: '', open: true }, nodePresentation: { text: { alias: 'Authored' } } }] };
session.activate(graph(), { workspaceViews: views, clean: true });
const authored = session.snapshot();
views.views[0].camera.x = 100;
views.activeKey = 'navigation';
views.views[0].selection.multi = ['text'];
assert.equal(session.snapshot(), authored, 'navigation is separate from authored presentation');
views.views[0].nodePresentation.text.alias = 'Changed';
assert.equal(session.dirty(), true, 'authored presentation contributes to the checkpoint');
assert.equal(session.capture().workspaceViews, views);
assert.equal(session.stillCurrent({ ...session.capture() }), false, 'tokens cannot be forged');
const viewsToken = session.capture(), replacement = structuredClone(views);
replacement.views[0].nodePresentation.text.alias = 'Replacement';
session.workspaceViews(replacement);
assert.equal(session.workspaceViews(), replacement);
assert.equal(viewsToken.workspaceViews, replacement, 'a captured activation exposes current serialized presentation');
assert.equal(session.stillCurrent(viewsToken), true, 'presentation edits keep the activation current');
assert.equal(session.dirty(), true);
const cameraOnly = structuredClone(replacement); cameraOnly.views[0].nodePresentation = {};
session.activate(graph(), { clean: true });
session.workspaceViews(cameraOnly);
assert.equal(session.dirty(), false, 'the first camera-only retained view does not modify an otherwise unchanged document');
console.log('document-session: ok');
