import assert from 'node:assert/strict';
import { fixture, mouse } from './canvas-fixture.mjs';
import { installMock } from './mock.js';
installMock();
const version = JSON.parse((await import('node:fs')).readFileSync(new URL('../manifest.json', import.meta.url))).version;
const S = await import(`../src/state.js?v=${version}`), H = await import(`../src/history.js?v=${version}`);
const { graph, canvas, host, a, b } = fixture(); H.track(graph);
const group = S.groupNodes(graph, [a.id, b.id], 'Scene'); H.noteChange(graph); H.flush(graph); canvas.render();
assert.deepEqual(S.groupMembers(graph, group.id).map(n => n.id), ['a', 'b']); assert.ok(!host.querySelector('[data-id="a"]')); assert.match(host.querySelector('.pc-node-group').textContent, /Scene/);
assert.equal(host.querySelectorAll('.pc-wire-hit').length, 0, 'internal wire is hidden when its visual group folds');
const folded = host.querySelector('.pc-node-group'); mouse(folded, 'mousedown', 60, 60); mouse(window, 'mousemove', 100, 90); mouse(window, 'mouseup', 100, 90);
assert.equal(a.x, 90); assert.equal(b.x, 390); assert.equal(group.x, 90);
group.collapsed = false; canvas.render(); assert.ok(host.querySelector('[data-id="a"]')); assert.ok(host.querySelector('.pc-group-frame')); assert.equal(host.querySelectorAll('.pc-wire-hit').length, 1);
assert.equal(host.querySelectorAll('.pc-group-frame .pc-port,.pc-group-toggle').length, 0, 'visual groups have no executable routing or enabled switch');
H.noteChange(graph); H.flush(graph); S.ungroup(graph, group.id); H.noteChange(graph); H.flush(graph); assert.deepEqual(graph.groups, {}); assert.equal(graph.nodes.a.inGroup, undefined);
H.undo(graph); assert.ok(graph.groups[group.id]); assert.equal(graph.nodes.a.inGroup, group.id); H.redo(graph); assert.deepEqual(graph.groups, {});
canvas.destroy(); console.log('groups: ok');
