import assert from 'node:assert/strict';
import * as api from '../src/workflow/introspection/context-state.js';
const one = {kind:'context',messages:[{id:'a',role:'user',text:'First'}],source:{chatId:'chat'}};
const two = {kind:'context',messages:[{id:'b',role:'assistant',text:'Second'}],source:{chatId:'chat'}};
const joined = await api.shapeContext({in1:one,in2:two});
assert.equal(joined.ok,true,'assemble must produce a validated Context');
assert.deepEqual(joined.artifact.messages.map(message => message.id),['a','b']);
assert.equal(joined.reports[0].code,'CONTEXT_JOIN');
assert.deepEqual(joined.artifact.source.inputs.map(input => input.portId),['in1','in2']);
assert.equal((await api.shapeContext({in1:one},{inputCount:1})).ok,false);
assert.equal((await api.shapeContext({in1:one,in2:two,unknown:one})).ok,false);
const slots = Object.fromEntries(Array.from({length:16},(_,index) => [`in${index+1}`,{kind:'context',messages:[{id:`slot${index}`,role:'user',text:`Message ${index}`}]}]));
assert.equal((await api.shapeContext(slots,{inputCount:16})).artifact.messages.length,16);
assert.equal((await api.shapeContext(slots,{inputCount:17})).ok,false);
const countTokens = async text => ({tokens:text.length,method:'characters-fixture'});
const history = {kind:'context',messages:[{id:'a',role:'user',text:'A'.repeat(30)},{id:'b',role:'assistant',text:'B'.repeat(30)},{id:'c',role:'user',text:'C'.repeat(30)}]};
let capabilityGetterReads=0;
for (const capability of ['request','signal']) {
    const unsafePorts={countTokens};
    Object.defineProperty(unsafePorts,capability,{enumerable:true,get(){capabilityGetterReads++;return capability==='signal' ? new AbortController().signal : async () => ({ok:true,data:{text:'Summary',finish:'stop'}});}});
    const unsafeResult=await api.shapeContext({context:history},{mode:'focus',targetTokens:500},unsafePorts);
    assert.equal(unsafeResult.ok,false,'capability getters must fail before being evaluated');
    assert.equal(unsafeResult.error.code,'INVALID_PORTS');
    assert.equal(capabilityGetterReads,0);
}
const staleContext=structuredClone(history);staleContext.messages[0].revision='r1';
const staleInputs={context:staleContext};
const staleFocus=await api.shapeContext(staleInputs,{mode:'focus',targetTokens:500},{countTokens:async text => {staleContext.messages[0].revision='r2';return countTokens(text);}});
assert.equal(staleFocus.ok,false,'Focus must reject an original source changed during token measurement');
assert.equal(staleFocus.error.code,'STALE_INPUT');
assert.equal(Object.hasOwn(staleFocus,'artifact'),false);
const selected = await api.shapeContext({context:history},{mode:'focus',method:'select',targetTokens:85,keepRecent:1},{countTokens});
assert.equal(selected.ok,true,'focus selection must honor its own named Context input');
assert.deepEqual(selected.artifact.messages.map(message => message.id),['b','c']);
assert.deepEqual(selected.artifact.original,history.messages);
assert.equal(selected.reports.some(report => report.code==='CONTEXT_PRESERVATION'),true);
let resultGetterReads=0, compressionTokenCalls=0;
const unsafeResponse=await api.shapeContext({context:history},{mode:'focus',method:'compress',targetTokens:5,keepRecent:0},{
    countTokens:async () => ({tokens:++compressionTokenCalls===1 ? 10 : 1,method:'bounded-fixture'}),binding:{},
    request:async () => ({ok:true,data:{get text(){resultGetterReads++;return 'summary';},finish:'stop'}}),
});
assert.equal(unsafeResponse.ok,false,'Focus must reject request result getters before the compactor consumes them');
assert.equal(resultGetterReads,0);
assert.equal(Object.hasOwn(unsafeResponse,'artifact'),false);
const unsafeTokenResult=await api.shapeContext({context:history},{mode:'focus',targetTokens:500},{
    countTokens:async () => ({get tokens(){resultGetterReads++;return 1;},method:'bounded-fixture'}),
});
assert.equal(unsafeTokenResult.ok,false,'Focus must reject token result getters before the compactor consumes them');
assert.equal(resultGetterReads,0);
assert.equal(Object.hasOwn(unsafeTokenResult,'artifact'),false);
let requests = 0;
const compressed = await api.shapeContext({context:history},{mode:'focus',method:'compress',targetTokens:90,keepRecent:1,maxTokens:32},{countTokens,binding:{profileId:'analysis',model:'test'},request:async () => {requests++; return {ok:true,data:{text:'Summary',finish:'stop'}};}});
assert.equal(compressed.ok,true);
assert.equal(requests,1);
assert.deepEqual(compressed.artifact.messages.map(message => message.text),['Summary','C'.repeat(30)]);
assert.equal((await api.shapeContext({context:history},{mode:'focus',targetTokens:0},{countTokens})).ok,false);
assert.equal((await api.shapeContext({context:history},{mode:'focus',unknown:true},{countTokens})).ok,false);
const cutoff = await api.shapeContext({context:history},{mode:'focus',method:'compress',targetTokens:90,keepRecent:1},{countTokens,binding:{profileId:'analysis',model:'test'},request:async () => ({ok:true,data:{text:'Summary',finish:'length'}})});
assert.equal(cutoff.ok,false);
assert.equal(Object.hasOwn(cutoff,'artifact'),false,'failed shaping must not expose an authoritative artifact');
const stopped = new AbortController();stopped.abort();
assert.equal((await api.shapeContext({in1:one,in2:two},{},{signal:stopped.signal})).ok,false);
const lateStop = new AbortController();
const late = await api.shapeContext({context:history},{mode:'focus',targetTokens:500},{countTokens:async text => {lateStop.abort();return countTokens(text);},signal:lateStop.signal});
assert.equal(late.ok,false);
assert.equal(Object.hasOwn(late,'artifact'),false);
const visibility = {kind:'context',messages:[{id:'public',role:'user',text:'Seen',visibleTo:['actor','other']},{id:'secret',role:'assistant',text:'Private',visibleTo:['other']},{id:'unknown',role:'user',text:'Unmarked'}],original:[{id:'old-secret',role:'user',text:'Earlier private',visibleTo:['other']},{id:'old-seen',role:'assistant',text:'Earlier seen',visibleTo:['actor']}]};
const view = await api.shapeContext({context:visibility},{mode:'perspective',actorId:'actor'});
assert.equal(view.ok,true);
assert.deepEqual(view.artifact.messages.map(message => message.id),['public']);
assert.deepEqual(view.artifact.original.map(message => message.id),['old-seen']);
assert.deepEqual(view.reports[0].omittedMessageIds,['secret','unknown']);
assert.deepEqual(view.reports[0].originalOmittedMessageIds,['old-secret']);
assert.equal((await api.shapeContext({context:visibility},{mode:'perspective'})).ok,false);
assert.equal((await api.shapeContext({context:one},{mode:'perspective',actorId:'actor'})).ok,false);
const metadataCopies = structuredClone(visibility);
metadataCopies.source={input:visibility.messages};
metadataCopies.provenance={input:{original:visibility.messages}};
metadataCopies.privateContext=visibility.messages;
metadataCopies.messages[0].source={original:visibility.messages};
metadataCopies.messages[0].revision='r3';
const safeView = await api.shapeContext({context:metadataCopies},{mode:'perspective',actorId:'actor'});
assert.equal(safeView.ok,true);
assert.equal(JSON.stringify(safeView.artifact).includes('Private'),false,'filtered text must not survive copied source or provenance metadata');
assert.equal(JSON.stringify(safeView.artifact).includes('Unmarked'),false);
assert.equal(safeView.artifact.messages[0].text,'Seen');
assert.equal(safeView.artifact.messages[0].revision,'r3');
assert.equal(safeView.artifact.provenance.actorId,'actor');
const absentActor = await api.shapeContext({context:visibility},{mode:'perspective',actorId:'absent'});
assert.equal(absentActor.ok,true);
assert.deepEqual(absentActor.artifact.messages,[]);
assert.equal((await api.shapeContext({context:{kind:'context',messages:[{id:'bad',role:'user',text:'Bad',visibleTo:'actor'}]}},{mode:'perspective',actorId:'actor'})).ok,false);
let getterReads = 0;
const unsafeSettings = {mode:'focus',get targetTokens(){getterReads++;return 100;}};
assert.equal((await api.shapeContext({context:one},unsafeSettings,{countTokens})).ok,false);
assert.equal(getterReads,0);
const unsafeContext = {kind:'context',messages:[{id:'bad',role:'user',text:'Text',get visibleTo(){getterReads++;return ['actor'];}}]};
assert.equal((await api.shapeContext({context:unsafeContext},{mode:'perspective',actorId:'actor'})).ok,false);
assert.equal(getterReads,0);
const record = (recordType,payload,sourceRefs=[]) => ({kind:'data',value:{schemaVersion:1,recordType,scope:{chatId:'chat',actorId:'actor'},store:{id:'store',version:4},sourceRefs,payload}});
const initial = {traits:[],beliefs:[],goals:[],relationships:[],conflicts:[],conditions:[],episodes:[],values:{anger:1,trust:0.2},curves:{emotion:{phase:'onset',value:1,elapsed:0}},tracks:{consequences:{eventIds:['past'],count:1}}};
const state = record('actor-state',initial,[{id:'past',revision:'r1'}]);
const stateSnapshot = structuredClone(state);
const read = api.advanceState?.(state);
assert.equal(read?.ok,true,'state value read must return validated actor state');
assert.equal(read.artifact.value.recordType,'actor-state');
assert.deepEqual(read.artifact,state);
assert.notEqual(read.artifact,state);
assert.equal(Object.isFrozen(read.artifact),true);
const update = api.advanceState(state,{updates:{anger:0.4}});
assert.equal(update.ok,true);
assert.equal(update.artifact.value.recordType,'state-proposal');
assert.deepEqual(update.artifact.value.payload.values,{anger:0.4});
assert.equal(update.artifact.value.store.version,4);
assert.equal(api.advanceState(state,{updates:{anger:2}}).ok,false);
assert.equal(api.advanceState(state,{updates:{anger:-2},min:-3,max:3}).ok,true);
assert.equal(api.advanceState(state,{min:2,max:1}).ok,false);
assert.equal(api.advanceState(state,{updates:{anger:NaN}}).ok,false);
assert.equal(api.advanceState(state,{updates:{anger:Infinity}}).ok,false);
assert.equal(api.advanceState(state,{updates:{anger:0.5},actorId:'other'}).ok,false);
assert.equal(api.advanceState(state,{updates:Object.fromEntries(Array.from({length:33},(_,index) => [`value${index}`,0]))}).ok,false);
const peak = api.advanceState(state,{mode:'curve'});
assert.equal(peak.ok,true);
assert.deepEqual(peak.artifact.value.payload.curves.emotion,{phase:'peak',value:0.75,elapsed:0});
const prototypeNamedCurve = api.advanceState(state,{mode:'curve',curveId:'toString'});
assert.equal(prototypeNamedCurve.ok,true,'valid absent curve IDs must not read inherited map fields');
assert.deepEqual(prototypeNamedCurve.artifact.value.payload.curves.toString,{phase:'peak',value:0,elapsed:0});
const recovery = api.advanceState(state,{mode:'curve',steps:5});
assert.deepEqual(recovery.artifact.value.payload.curves.emotion,{phase:'baseline',value:0,elapsed:0});
const custom = api.advanceState(state,{mode:'curve',steps:2,decay:0.5,baseline:0.2,durations:{onset:3,peak:1,plateau:1,decline:1,aftermath:1}});
assert.equal(custom.ok,true);
assert.deepEqual(custom.artifact.value.payload.curves.emotion,{phase:'onset',value:0.4,elapsed:2});
const settledState = structuredClone(state);settledState.value.payload.curves.emotion={phase:'baseline',value:0,elapsed:0};
assert.deepEqual(api.advanceState(settledState,{mode:'curve',steps:64}).artifact.value.payload.curves.emotion,{phase:'baseline',value:0,elapsed:0});
assert.equal(api.advanceState(state,{mode:'curve',steps:0}).ok,false);
assert.equal(api.advanceState(state,{mode:'curve',steps:65}).ok,false);
assert.equal(api.advanceState(state,{mode:'curve',decay:1.1}).ok,false);
assert.equal(api.advanceState(state,{mode:'curve',durations:{onset:0}}).ok,false);
const events = record('events',{events:[{id:'past',revision:'r1',text:'Past',settled:true},{id:'new',revision:'r2',text:'New',settled:true}]},[{id:'past',revision:'r1'},{id:'new',revision:'r2'}]);
const track = api.advanceState(state,{mode:'track'},events);
assert.equal(track.ok,true);
assert.deepEqual(track.artifact.value.payload.tracks.consequences,{eventIds:['past','new'],count:2});
assert.deepEqual(track.artifact.value.sourceRefs,[{id:'past',revision:'r1'},{id:'new',revision:'r2'}]);
const repeatedState = structuredClone(state);repeatedState.value.payload.tracks.consequences={eventIds:['past','new'],count:2};repeatedState.value.sourceRefs=events.value.sourceRefs;
assert.deepEqual(api.advanceState(repeatedState,{mode:'track'},events).artifact.value.payload.tracks.consequences,{eventIds:['past','new'],count:2});
assert.equal(api.advanceState(state,{mode:'track'}).ok,false);
const otherActor = structuredClone(events);otherActor.value.scope.actorId='other';
assert.equal(api.advanceState(state,{mode:'track'},otherActor).ok,false);
const stale = structuredClone(events);stale.value.store.version=3;
assert.equal(api.advanceState(state,{mode:'track'},stale).ok,false);
const unverified = structuredClone(events);unverified.value.sourceRefs=[];
assert.equal(api.advanceState(state,{mode:'track'},unverified).ok,false);
const draft = structuredClone(events);draft.value.payload.events[1].settled=false;
assert.equal(api.advanceState(state,{mode:'track'},draft).ok,false);
const full = structuredClone(state);full.value.payload.tracks.consequences={eventIds:Array.from({length:64},(_,index)=>`old${index}`),count:64};
assert.equal(api.advanceState(full,{mode:'track'},events).ok,false);
const conflictingRevision = structuredClone(events);conflictingRevision.value.payload.events[0].revision='r2';conflictingRevision.value.sourceRefs[0].revision='r2';
assert.equal(api.advanceState(state,{mode:'track'},conflictingRevision).ok,false);
const dangerous = JSON.parse('{"updates":{"__proto__":0.5}}');
assert.equal(api.advanceState(state,dangerous).ok,false);
assert.deepEqual(state,stateSnapshot);
assert.deepEqual(visibility.messages.map(message=>message.id),['public','secret','unknown']);
console.log('introspection context/state: ok');
