import assert from 'node:assert/strict';
import test from 'node:test';
import {createChatDocumentCatalog} from '../src/workflow/document-catalog.js?v=0.26.0';
import {createNativeFileSession} from '../src/workflow/native-settlement.js?v=0.26.0';
import {executeTimeNode} from '../src/workflow/operations/time-nodes.js?v=0.26.0';
const api=await import('../src/workflow/native-story-state.js?v=0.26.0').catch(()=>({}));
async function fixture(minute=360){let saves=0,current=true;const c={chatId:'story',chat:[],chatMetadata:{}};const scope={userId:'default-user',chatId:'story'};const catalog=createChatDocumentCatalog({getContext:()=>c,getUserId:()=>scope.userId});catalog.define({targetId:'clock',name:'Clock',format:'json',visibility:{kind:'public'},content:JSON.stringify({schemaVersion:1,clockId:'clock',calendarId:'days',revision:1,dayLengthMinutes:1440,absoluteMinute:minute,settledTimeEventIds:[]})});const effects=[];const files=createNativeFileSession({catalog,scope,context:()=>c,userId:()=>scope.userId,persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}},isCurrent:()=>current,workflowId:'workflow',originalDraft:{source:{originalText:'Native',messageIndex:0,swipeId:0}},validateEvidence:()=>({ok:true}),stage:effect=>{effects.push(effect);return {ok:true};}}).data;assert.equal(typeof api.createNativeStoryState,'function');const state=api.createNativeStoryState({files,scope,isCurrent:()=>current,turnId:'player-turn-1',sourceForEvent:()=>({ok:false,error:{code:'SOURCE_UNAVAILABLE',message:'No source'}}),cache:api.createNativeOutcomeCache({random:()=>0.25})});return {state,files,c,effects,saves:()=>saves,stale:()=>{current=false;}};}
async function advance(f,{policy='interrupt',minutes=720,schedules=[{scheduleId:'curse',kind:'daily',minuteOfDay:840}]}={}){const read=await f.state.readClock('clock');assert.equal(read.ok,true,JSON.stringify(read.error));const source=await executeTimeNode({operation:'story-clock',clockId:'clock'},{},{root:true,readStoryClock:()=>read});f.state.registerClock(source.outputs.out.value,'clock');return executeTimeNode({operation:'advance-time',policy,schedules},{clock:source.outputs.out,proposal:{kind:'data',value:{kind:'duration',minutes}}},{retainTimeProjection:f.state.retainTimeProjection});}
test('native clock stages an authenticated interrupted advance, revision and consumed ledger without saving before acceptance',async()=>{const f=await fixture(),projection=await advance(f);assert.equal(projection.ok,true,JSON.stringify(projection.error));assert.equal(projection.outputs.clock.value.absoluteMinute,840);assert.equal(projection.outputs.remainder.value.minutes,240);const staged=await f.state.stageClock(projection.outputs.report.value);assert.equal(staged.ok,true,JSON.stringify(staged.error));assert.equal(f.saves(),0);assert.equal(f.effects.length,1);assert.equal((await f.effects[0].preflight()).ok,true);assert.equal((await f.effects[0].commit({root:true,accepted:true})).ok,true);const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(saved.revision,2);assert.equal(saved.absoluteMinute,840);assert.equal(saved.pendingTimeAdvance.minutes,240);assert.equal(saved.settledTimeEventIds.length,1);assert.equal(f.saves(),1);});
test('clock staging rejects fabricated projections and stale source; accepted rerun reuses its preturn clock',async()=>{const f=await fixture(),projection=await advance(f);assert.equal((await f.state.stageClock(structuredClone(projection.outputs.report.value))).ok,false);await f.state.stageClock(projection.outputs.report.value);await f.effects[0].commit({root:true,accepted:true});const again=await advance(f);assert.equal(again.outputs.clock.value.absoluteMinute,840);const staged=await f.state.stageClock(again.outputs.report.value);assert.equal(staged.ok,true,JSON.stringify(staged.error));assert.equal((await f.effects[1].commit({root:true,accepted:true})).ok,true);assert.equal(f.saves(),1);f.stale();assert.equal((await f.state.readClock('clock')).ok,false);});
test('accepted catch-up retains midnight and anchored eight-hour occurrence identities',async()=>{const f=await fixture(0),projection=await advance(f,{policy:'catch-up',minutes:1440,schedules:[{scheduleId:'midnight',kind:'daily',minuteOfDay:0},{scheduleId:'periodic',kind:'interval',anchorMinute:0,intervalMinutes:480}]});assert.equal(projection.ok,true);assert.deepEqual(projection.outputs.occurrences.value.map(event=>event.dueMinute),[480,960,1440,1440]);await f.state.stageClock(projection.outputs.report.value);await f.effects[0].commit({root:true,accepted:true});const clock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(clock.settledTimeEventIds.length,4);assert.equal(clock.pendingTimeAdvance,null);});
import { normalizeOccurrences,confirmOccurrences,resolveItemHolders } from '../src/workflow/operations/event-data.js?v=0.26.0';
import { executeRandom } from '../src/workflow/operations/random-outcomes.js?v=0.26.0';
const randomSource={sourceId:'player-1',revision:'r1',sceneId:'scene',watch:'player-message',text:'Mara uses her broken wand.',visibility:'public'};
const eventCandidates=normalizeOccurrences(randomSource,[{eventType:'item-used',actorId:'mara',itemId:'wand',position:{start:0,end:randomSource.text.length},semantics:'actual'}],{actorIds:['mara'],itemIds:['wand']}).data.events;
const randomEvent=resolveItemHolders({wand:'mara'},confirmOccurrences(eventCandidates,[{eventId:eventCandidates[0].eventId,accepted:true}]).data.events).data.events[0];
const randomLibrary={libraryId:'wand',revision:'1',itemId:'wand',effects:[{id:'wild',kind:'generate',weight:1}]};
test('native pending outcomes survive a failed author without redrawing, then persist only resolved accepted data',async()=>{
 const f=await fixture();f.c.chatMetadata={};const catalog=createChatDocumentCatalog({getContext:()=>f.c,getUserId:()=> 'default-user'});catalog.define({targetId:'outcomes',name:'Outcomes',format:'json',content:'[]',visibility:{kind:'public'}});
 let draws=0,saves=0,current=true;const effects=[],cache=api.createNativeOutcomeCache({random:()=>{draws++;return .4;}});
 function state(){const files=createNativeFileSession({catalog,scope:{userId:'default-user',chatId:'story'},context:()=>f.c,userId:()=> 'default-user',persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}},isCurrent:()=>current,workflowId:'workflow',originalDraft:{source:{originalText:'Native',messageIndex:0,swipeId:0}},validateEvidence:()=>({ok:true}),stage:effect=>{effects.push(effect);return {ok:true};}}).data;return api.createNativeStoryState({files,scope:{userId:'default-user',chatId:'story'},isCurrent:()=>current,turnId:'turn',sourceForEvent:()=>({ok:true,data:{isCurrent:()=>current}}),cache});}
 let s=state(),picked=await s.selectNativeRandomOutcomes({events:[randomEvent],library:randomLibrary});assert.equal(picked.ok,true,JSON.stringify(picked.error));const failed=await executeRandom({operation:'effect-author'},{in:{kind:'data',value:picked.data.outcomes[0]}},{request:async()=>({ok:false,error:{code:'FAILED',message:'No model'}}),reuseNativeOutcome:s.reuseNativeOutcome,retainNativeOutcome:s.retainNativeOutcome});assert.equal(failed.ok,false);s.release();
 s=state();picked=await s.selectNativeRandomOutcomes({events:[randomEvent],library:{...randomLibrary,revision:'2',effects:[{id:'different',kind:'fixed',weight:1,description:'A different list.'}]}});assert.equal(picked.ok,true,JSON.stringify(picked.error));assert.equal(picked.data.outcomes[0].selection.id,'wild');assert.equal(draws,1);
 const authored=await executeRandom({operation:'effect-author'},{in:{kind:'data',value:picked.data.outcomes[0]}},{request:async()=>({ok:true,data:{finish:'stop',text:JSON.stringify({id:'moths',description:'Paper moths spiral around Mara.',spellOutcome:'replaced',duration:'One minute',consequence:'The target is unharmed.'})}}),reuseNativeOutcome:s.reuseNativeOutcome,retainNativeOutcome:s.retainNativeOutcome});assert.equal(authored.ok,true,JSON.stringify(authored.error));
 const resolved=await executeRandom({operation:'stage-outcome'},{in:authored.artifact,novelty:{kind:'data',value:{accepted:true}}},{retainNativeOutcome:s.retainNativeOutcome});assert.equal(resolved.ok,true,JSON.stringify(resolved.error));const staged=await s.stageOutcomes('outcomes',resolved.artifact.value);assert.equal(staged.ok,true,JSON.stringify(staged.error));assert.equal(saves,0);assert.equal((await effects[0].commit({root:true,accepted:true})).ok,true);assert.equal(saves,1);const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].outcomes.content);assert.equal(saved[0].acceptance,'accepted');assert.equal(saved[0].effect.id,'moths');
 s.release();s=state();const durable=await s.selectNativeRandomOutcomes({events:[randomEvent],library:randomLibrary,ledgerId:'outcomes'});assert.equal(durable.ok,true,JSON.stringify(durable.error));assert.equal(durable.data.outcomes[0].effect.id,'moths');assert.equal(draws,1);current=false;assert.equal((await s.stageOutcomes('outcomes',durable.data.outcomes)).ok,false);
});
test('retained clock replay remains idempotent after later turns have earlier advance records',async()=>{const f=await fixture(),first=await advance(f);await f.state.stageClock(first.outputs.report.value);await f.effects[0].commit({root:true,accepted:true});f.state.release();f.state=api.createNativeStoryState({files:f.files,scope:{userId:'default-user',chatId:'story'},isCurrent:()=>true,turnId:'player-turn-2',sourceForEvent:()=>({ok:false}),cache:api.createNativeOutcomeCache()});const second=await advance(f,{minutes:120,schedules:[]});assert.equal(second.outputs.clock.value.absoluteMinute,960);assert.equal((await f.state.stageClock(second.outputs.report.value)).ok,true);await f.effects[1].commit({root:true,accepted:true});const replay=await advance(f,{minutes:120,schedules:[]});assert.equal(replay.outputs.clock.value.absoluteMinute,960);assert.equal((await f.state.stageClock(replay.outputs.report.value)).ok,true);assert.equal((await f.effects[2].commit({root:true,accepted:true})).ok,true);assert.equal(f.saves(),2);});
test('scheduled file evidence requires the exact retained event and an accepted clock staging intent',async()=>{const f=await fixture(),projection=await advance(f),event=projection.outputs.occurrences.value[0];assert.equal(f.state.validateEvidence([event],'Final','Native').ok,false);await f.state.stageClock(projection.outputs.report.value);assert.equal(f.state.validateEvidence([event],'Final','Native').ok,true);assert.equal(f.state.validateEvidence([{...event,dueMinute:event.dueMinute+1}],'Final','Native').ok,false);assert.equal(f.state.validateEvidence([null],'Final','Native').ok,false);});
test('private time proposal cannot be saved into a public clock target',async()=>{const f=await fixture(),read=await f.state.readClock('clock'),clock=await executeTimeNode({operation:'story-clock',clockId:'clock'},{},{root:true,readStoryClock:()=>read});f.state.registerClock(clock.outputs.out.value,'clock');const projection=await executeTimeNode({operation:'advance-time'},{clock:clock.outputs.out,proposal:{kind:'data',value:{kind:'duration',minutes:60},visibility:{kind:'actor-private',actorId:'mara'}}},{retainTimeProjection:f.state.retainTimeProjection});assert.equal(projection.ok,true);const staged=await f.state.stageClock(projection.outputs.report.value);assert.equal(staged.error.code,'PRIVATE_DESTINATION');assert.equal(f.effects.length,0);assert.equal(f.saves(),0);});
test('provider failures and token metadata cannot disclose credentials through wild effect reports',async()=>{const picked=await import('../src/workflow/operations/random-outcomes.js?v=0.26.0').then(module=>module.selectRandomOutcomes([randomEvent],randomLibrary,[],{random:()=>.1}));const outcome=picked.data.outcomes[0];const failed=await executeRandom({operation:'effect-author'},{in:{kind:'data',value:outcome}},{request:async()=>({ok:false,error:{code:'TRUNCATED_OUTPUT',message:'SECRET provider detail',usage:{prompt_tokens:1,authorization:'SECRET'}}})});assert.equal(JSON.stringify(failed).includes('SECRET'),false);const authored=await executeRandom({operation:'effect-author'},{in:{kind:'data',value:outcome}},{request:async()=>({ok:true,data:{finish:'stop',usage:{prompt_tokens:3,completion_tokens:5,authorization:'SECRET'},text:JSON.stringify({id:'moths',description:'Paper moths circle Mara.',spellOutcome:'replaced',duration:'One minute',consequence:'The target remains unharmed.'})}})});assert.equal(JSON.stringify(authored).includes('SECRET'),false);assert.deepEqual(authored.reports[0].usage,{prompt_tokens:3,completion_tokens:5});});
test('empty native outcome set stages no file effect and makes no draw',async()=>{const f=await fixture(),empty=await f.state.stageOutcomes('clock',[]);assert.equal(empty.ok,true,JSON.stringify(empty.error));assert.equal(empty.data.status,'empty');assert.equal(f.effects.length,0);assert.equal(f.saves(),0);});
test('native caches reject forged saved draws, preserve private restrictions on retry, and revoke active sessions when cleared',async()=>{const f=await fixture(),cache=api.createNativeOutcomeCache({random:()=>.2});const s=api.createNativeStoryState({files:f.files,scope:{userId:'default-user',chatId:'story'},isCurrent:()=>true,turnId:'turn',sourceForEvent:()=>({ok:true,data:{isCurrent:()=>true}}),cache});const library={...randomLibrary,effects:[{id:'fixed',kind:'fixed',weight:1,description:'Sparks.'}]};const picked=await s.selectNativeRandomOutcomes({events:[randomEvent],library,visibility:{kind:'actor-private',actorId:'mara'}});assert.equal(picked.ok,true);const forged={...picked.data.outcomes[0],draw:{...picked.data.outcomes[0].draw,unit:.8}};assert.equal((await s.selectNativeRandomOutcomes({events:[randomEvent],library,saved:[forged]})).error.code,'UNTRUSTED_SAVED_OUTCOME');const retry=await s.selectNativeRandomOutcomes({events:[randomEvent],library});assert.deepEqual(retry.data.visibility,{kind:'actor-private',actorId:'mara'});assert.equal((await s.stageOutcomes('clock',retry.data.outcomes)).error.code,'PRIVATE_DESTINATION');cache.clear();assert.equal((await s.readClock('clock')).ok,false);assert.equal((await s.stageOutcomes('clock',picked.data.outcomes)).ok,false);});

test('trusted freshness callback cannot expose a player source after releasing its service or replacing the cache epoch',async()=>{
 const f=await fixture();for(const revoke of ['release','clear']){let service,armed=false;const cache=api.createNativeOutcomeCache(),playerSource={...randomSource,text:'Captured source remains private after revocation.'};service=api.createNativeStoryState({files:f.files,scope:{userId:'default-user',chatId:'story'},turnId:'turn',cache,playerSource,sourceForEvent:()=>({ok:false}),isCurrent:()=>{if(armed){armed=false;if(revoke==='release')service.release();else cache.clear();}return true;}});armed=true;const result=service.playerSource();assert.equal(result.ok,false,revoke+' must revoke the current action');assert.equal(result.error.code,'STALE_STATE_SCOPE');assert.equal(JSON.stringify(result).includes(playerSource.text),false);}
});
test('callback revocation prevents time and outcome authority from being retained into the cleared cache epoch',async()=>{
 const f=await fixture();let state,armed=false;const cache=api.createNativeOutcomeCache({random:()=>.2});state=api.createNativeStoryState({files:f.files,scope:{userId:'default-user',chatId:'story'},isCurrent:()=>{if(armed){armed=false;cache.clear();}return true;},turnId:'turn',sourceForEvent:()=>({ok:true,data:{isCurrent:()=>true}}),cache});f.state=state;const first=await advance(f,{minutes:60,schedules:[]});assert.equal(first.ok,true);armed=true;const retained=state.retainTimeProjection({operation:'advance-time',inputs:{clock:first.outputs.clock,proposal:{kind:'data',value:{kind:'duration',minutes:60}}},settings:{},outputs:first.outputs});assert.equal(retained.ok,false);assert.equal(retained.error.code,'STALE_STATE_SCOPE');assert.equal((await state.stageClock(first.outputs.report.value)).ok,false);
});
test('the final freshness callback cannot retain an outcome after replacing its private cache epoch',async()=>{const f=await fixture();const nextCache=api.createNativeOutcomeCache({random:()=>.2});let outcomeState,checkCount=0;outcomeState=api.createNativeStoryState({files:f.files,scope:{userId:'default-user',chatId:'story'},isCurrent:()=>{checkCount++;if(checkCount===8)nextCache.clear();return true;},turnId:'turn',sourceForEvent:()=>({ok:true,data:{isCurrent:()=>true}}),cache:nextCache});const selected=await outcomeState.selectNativeRandomOutcomes({events:[randomEvent],library:randomLibrary});assert.equal(selected.ok,false);assert.equal(selected.error.code,'STATE_EVIDENCE_CHANGED');assert.equal((await outcomeState.stageOutcomes('clock',[])).ok,false);
});
test('chained advances retain the turn-start clock and every due event for accepted same-turn replay',async()=>{
 const f=await fixture(0);async function chain(){const first=await advance(f,{policy:'catch-up',minutes:60,schedules:[{scheduleId:'first',kind:'daily',minuteOfDay:30}]});const second=await executeTimeNode({operation:'advance-time',policy:'catch-up',schedules:[{scheduleId:'second',kind:'daily',minuteOfDay:90}]},{clock:first.outputs.clock,proposal:{kind:'data',value:{kind:'duration',minutes:60}}},{retainTimeProjection:f.state.retainTimeProjection});assert.equal(second.ok,true,JSON.stringify(second.error));return {first,second};}const initial=await chain();assert.equal(initial.second.outputs.clock.value.absoluteMinute,120);assert.equal((await f.state.stageClock(initial.second.outputs.report.value)).ok,true);assert.equal(f.state.validateEvidence(initial.first.outputs.occurrences.value,'Final','Native').ok,true);assert.equal((await f.effects[0].commit({root:true,accepted:true})).ok,true);const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(saved.acceptedTimeAdvances[0].previousClock.absoluteMinute,0);assert.equal(saved.settledTimeEventIds.length,2);const replay=await chain();assert.equal(replay.second.outputs.clock.value.absoluteMinute,120);const staged=await f.state.stageClock(replay.second.outputs.report.value);assert.equal(staged.ok,true,JSON.stringify(staged.error));assert.equal((await f.effects[1].commit({root:true,accepted:true})).ok,true);assert.equal(f.saves(),1);
});
test('native accepted clock schema is explicit while optional minute origin metadata stays optional',async()=>{const f=await fixture(600);const valid=await f.state.readClock('clock');assert.equal(valid.ok,true);assert.equal(valid.data.schemaVersion,1);assert.equal(valid.data.unit,undefined);const withoutSchema={...valid.data};delete withoutSchema.schemaVersion;const read=await executeTimeNode({operation:'story-clock',clockId:'clock'},{},{root:true,readStoryClock:()=>({ok:true,data:withoutSchema})});assert.equal(read.ok,false);assert.equal(read.error.code,'INVALID_CLOCK');});

test('an interrupted chained advance must explicitly consume its retained remainder before acceptance',async()=>{const f=await fixture(),first=await advance(f);const unrelated=await executeTimeNode({operation:'advance-time',policy:'catch-up'},{clock:first.outputs.clock,proposal:{kind:'data',value:{kind:'duration',minutes:60}}},{retainTimeProjection:f.state.retainTimeProjection});assert.equal(unrelated.ok,false,'An unrelated duration must not silently discard the interrupted remainder');const resumed=await executeTimeNode({operation:'advance-time',policy:'catch-up'},{clock:first.outputs.clock,proposal:first.outputs.remainder},{retainTimeProjection:f.state.retainTimeProjection});assert.equal(resumed.ok,true,JSON.stringify(resumed.error));assert.equal((await f.state.stageClock(resumed.outputs.report.value)).ok,true);assert.equal((await f.effects[0].commit({root:true,accepted:true})).ok,true);const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(saved.absoluteMinute,1080);assert.equal(saved.pendingTimeAdvance,null);assert.equal(saved.settledTimeEventIds.length,1);assert.equal(saved.acceptedTimeAdvances[0].previousClock.absoluteMinute,360);});
