import assert from 'node:assert/strict';
import { fixture } from './canvas-fixture.mjs';
const { graph, canvas, host } = fixture();
graph.nodes.note = { id: 'note', type: 'note', title: 'Scene note', content: 'Keep the choice open.', x: 700, y: 80 };
graph.nativeCards.note = { canonicalTitle: 'Note', family: 'Organization', iconPath: 'M1 1h2', body: 'Keep the choice open.', ports: [], hostResult: false };
canvas.render();
const note = host.querySelector('[data-id="note"]'); assert.ok(note); assert.match(note.textContent, /Keep the choice open/); assert.equal(note.querySelectorAll('.pc-port').length, 0);
graph.nodes.note.content = 'Changed annotation'; graph.nativeCards.note.body = 'Changed annotation'; canvas.render(); assert.equal(host.querySelector('[data-id="note"]'), note); assert.match(note.textContent, /Changed annotation/);
assert.ok(!note.querySelector('.pc-toggle-off')); assert.ok(!note.querySelector('.pc-tok'));
canvas.destroy(); console.log('notes: ok');
