import assert from 'node:assert/strict';
import {test} from 'node:test';
const module=await import('../src/ui/recall-shortcuts.js?v=0.27.0').catch(()=>({}));
function document(){const listeners=new Map();return {activeElement:null,addEventListener(type,handler){listeners.set(type,handler);},removeEventListener(type,handler){if(listeners.get(type)===handler)listeners.delete(type);},press(extra={}){let prevented=false;listeners.get('keydown')?.({code:'KeyR',ctrlKey:true,shiftKey:true,altKey:false,metaKey:false,repeat:false,isComposing:false,defaultPrevented:false,target:{tagName:'DIV'},composedPath:()=>[],preventDefault(){prevented=true;},...extra});return prevented;},listeners};}
const request=onPress=>({scope:{userId:'default-user',chatId:'Story-2',workflowId:'workflow',actorId:'character:mara.png'},nodeId:'arm',hotkey:{code:'KeyR',ctrl:true,shift:true,alt:false,meta:false},onPress});
test('workspace modal targets and focus cannot queue Recall before bubbling isolation',()=>{const d=document();let armed=0;const registry=module.createRecallShortcutRegistry(d);registry.register(request(()=>{armed++;return {ok:true};}));const overlayButton={tagName:'BUTTON',closest:selector=>selector.includes('.pc-workspace-overlay')?{}:null};assert.equal(d.press({target:overlayButton}),false);d.activeElement=overlayButton;assert.equal(d.press(),false);d.activeElement=null;assert.equal(d.press({composedPath:()=>[overlayButton]}),false);assert.equal(armed,0);assert.equal(d.press({target:{tagName:'BUTTON',getAttribute:()=>null,closest:()=>null}}),true);assert.equal(armed,1);});
test('actual DOM registry runs one exact shortcut, reports a change and removes its listener',()=>{assert.equal(typeof module.createRecallShortcutRegistry,'function');const d=document();let armed=0,changed=0;const registry=module.createRecallShortcutRegistry(d,{changed:()=>changed++});const registered=registry.register(request(()=>{armed++;return {ok:true};}));assert.equal(registered.ok,true);assert.equal(d.press(),true);assert.equal(armed,1);assert.equal(changed,1);registered.data.dispose();assert.equal(d.press(),false);assert.equal(d.listeners.size,0);});
test('typing, composing, repeated and mismatched shortcuts cannot arm recall',()=>{const d=document();let armed=0;const registry=module.createRecallShortcutRegistry(d);registry.register(request(()=>{armed++;return {ok:true};}));for(const extra of [{repeat:true},{isComposing:true},{defaultPrevented:true},{ctrlKey:false},{altKey:true},{code:'KeyT'},{target:{tagName:'TEXTAREA'}},{target:{isContentEditable:true}},{composedPath:()=>[{tagName:'INPUT'}]}])assert.equal(d.press(extra),false);d.activeElement={tagName:'SELECT'};assert.equal(d.press(),false);assert.equal(armed,0);});
test('conflicting registrations hold; disposal and rejected scope callbacks cannot consume keyboard input',()=>{const d=document();const registry=module.createRecallShortcutRegistry(d);const first=registry.register(request(()=>({ok:false,error:{code:'STALE',message:'Changed.'}})));assert.equal(first.ok,true);assert.equal(registry.register({...request(()=>({ok:true})),nodeId:'another'}).ok,false);assert.equal(d.press(),false);first.data.dispose();assert.equal(registry.register({...request(()=>({ok:true})),nodeId:'another'}).ok,true);assert.equal(d.press(),true);registry.dispose();assert.equal(d.press(),false);assert.equal(registry.register(request(()=>({ok:true}))).ok,false);});
