import assert from 'node:assert/strict';
import { fixture, mouse, S } from './canvas-fixture.mjs';
const { canvas, host, a, b, graph } = fixture();
mouse(host, 'mousedown', 20, 20);
mouse(window, 'mousemove', 310, 130);
assert.ok(canvas.multi.has(a.id), 'plain empty-canvas drag selects intersected blocks while dragging');
assert.deepEqual(graph.view, { x: 0, y: 0, zoom: 1 }, 'selection drag does not pan');
mouse(window, 'mouseup', 310, 130);
assert.equal(host.querySelector('.pc-marquee'), null, 'rectangle disappears on release');
mouse(host, 'mousedown', 320, 20, { shiftKey: true });
mouse(window, 'mousemove', 630, 130, { shiftKey: true });
assert.deepEqual(new Set(canvas.multi), new Set([a.id, b.id]), 'Shift rectangle adds to the gesture-start selection');
mouse(window, 'mouseup', 630, 130, { shiftKey: true });
mouse(host, 'mousedown', 630, 130, { altKey: true });
mouse(window, 'mousemove', 320, 20, { altKey: true });
assert.deepEqual([...canvas.multi], [a.id], 'Alt rectangle removes hits in reverse drag direction');
mouse(window, 'mouseup', 320, 20, { altKey: true });
const aCard = () => host.querySelector(`.pc-node[data-id="${a.id}"]`);
mouse(aCard(), 'mousedown', 80, 80, { shiftKey: true }); mouse(window, 'mouseup', 80, 80);
assert.ok(canvas.multi.has(a.id), 'Shift-clicking a selected card preserves it');
const panStart = { ...graph.view };
mouse(aCard(), 'mousedown', 80, 80, { button: 1 });
mouse(window, 'mousemove', 130, 120, { button: 1 });
mouse(window, 'mouseup', 130, 120, { button: 1 });
assert.ok(canvas.multi.has(a.id), 'middle-button pan over a card preserves selection');
assert.equal(graph.view.x, panStart.x + 50);
assert.equal(graph.view.y, panStart.y + 40);
canvas.setMulti([a.id, b.id]);
const aPosition = { x: a.x, y: a.y };
const bPosition = { x: b.x, y: b.y };
mouse(aCard(), 'mousedown', 80, 80);
mouse(window, 'mousemove', 81, 80);
mouse(window, 'mouseup', 81, 80);
assert.deepEqual({ x: a.x, y: a.y }, aPosition, 'sub-threshold card movement stays a click');
assert.deepEqual([...canvas.multi], [a.id], 'clicking a selected member narrows on release');
canvas.setMulti([a.id, b.id]);
mouse(aCard(), 'mousedown', 80, 80);
mouse(window, 'mousemove', 120, 110);
assert.equal(a.x, aPosition.x + 40); assert.equal(b.x, bPosition.x + 40);
assert.equal(canvas.cancelGesture(), true, 'an active drag can be cancelled');
assert.deepEqual({ x: a.x, y: a.y }, aPosition, 'cancel restores the first card');
assert.deepEqual({ x: b.x, y: b.y }, bPosition, 'cancel restores all selected cards');
assert.deepEqual(new Set(canvas.multi), new Set([a.id, b.id]), 'cancel restores the selection');
const group = S.groupNodes(graph, [a.id, b.id], 'Folded'); canvas.render(); canvas.selectAll();
const output = S.outputNode(graph); const outX = output.x;
const groupX = group.x;
mouse(host.querySelector('.pc-node-group'), 'mousedown', 100, 100);
mouse(window, 'mousemove', 140, 130);
assert.equal(output.x, outX + 40, 'dragging a selected folded unit moves the rest of the selection');
assert.equal(group.x, groupX + 40, 'the folded unit itself follows its hidden members');
canvas.cancelGesture(); assert.equal(group.x, groupX); assert.equal(output.x, outX);
const shifted = fixture(); shifted.canvas.setMulti([shifted.a.id, shifted.b.id]);
mouse(shifted.host.querySelector(`[data-id="${shifted.a.id}"]`), 'mousedown', 80, 80, { shiftKey: true });
mouse(window, 'mousemove', 140, 120, { shiftKey: true });
assert.equal(shifted.a.x, 110, 'Shift-drag moves the selected card');
assert.equal(shifted.b.x, 410, 'Shift-drag keeps the selected set together');
mouse(window, 'mouseup', 140, 120, { shiftKey: true });
assert.equal(shifted.canvas.multi.size, 2, 'Shift-drag does not narrow the selected set');
const shiftedGroup = S.groupNodes(shifted.graph, [shifted.a.id, shifted.b.id], 'Shift fold');
shifted.canvas.render(); shifted.canvas.selectAll(); const shiftGroupX = shiftedGroup.x;
mouse(shifted.host.querySelector('.pc-node-group'), 'mousedown', 120, 100, { shiftKey: true });
mouse(window, 'mousemove', 160, 140, { shiftKey: true });
assert.equal(shiftedGroup.x, shiftGroupX + 40, 'Shift-drag also moves a selected folded unit');
shifted.canvas.cancelGesture();
console.log('selection-gestures: ok');
