import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createRecallCommands} from '../src/ui/recall-commands.js';
const projection={nodes:{a:{queueAllowed:true,cancelAllowed:false,shortcutNodeIds:['shortcut'],reason:''},b:{queueAllowed:false,cancelAllowed:false,reason:'Unavailable'}}};
function fixture(){const editorToken={},documentToken={};let context={editorToken,documentToken,selectionEpoch:1,projection},calls=[],changes=0;const commands=createRecallCommands({readContext:()=>context,isContextCurrent:captured=>captured.editorToken===context.editorToken&&captured.documentToken===context.documentToken&&captured.selectionEpoch===context.selectionEpoch,captureRecall:()=>({ok:true,data:{}}),changeRecallQueues:(token,batch)=>{calls.push(batch);return {ok:true,data:{}};},changed:()=>changes++,openDetails:()=>{}});return {commands,calls,change:value=>context={...context,...value},changes:()=>changes};}
test('command captures exact eligible IDs and dispatches one deduplicated batch',()=>{const f=fixture(),capture=f.commands.capture(['a','b']);assert.equal(capture.ok,true);assert.equal(f.commands.change(capture.data,'queue').ok,true);assert.deepEqual(f.calls,[{action:'queue',shortcutNodeIds:['shortcut']}]);assert.equal(f.changes(),1);});
test('document, editor and selection changes invalidate without falling back to all',()=>{for(const change of [{editorToken:{}},{documentToken:{}},{selectionEpoch:2}]){const f=fixture(),capture=f.commands.capture(['a']);f.change(change);assert.equal(f.commands.change(capture.data,'queue').ok,false);assert.equal(f.calls.length,0);}});
test('empty, forged and newly ineligible captures cannot mutate',()=>{const f=fixture();assert.equal(f.commands.capture([]).ok,false);assert.equal(f.commands.change({},'queue').ok,false);const capture=f.commands.capture(['a']);f.change({projection:{nodes:{a:{queueAllowed:false,reason:'No longer eligible'}}}});assert.equal(f.commands.change(capture.data,'queue').ok,false);assert.equal(f.calls.length,0);});

test('a partly invalidated batch cannot apply its remaining nodes',()=>{const f=fixture();projection.nodes.c={queueAllowed:true,shortcutNodeIds:['another']};const capture=f.commands.capture(['a','c']);f.change({projection:{nodes:{a:projection.nodes.a,c:{queueAllowed:false}}}});assert.equal(f.commands.change(capture.data,'queue').ok,false);assert.equal(f.calls.length,0);delete projection.nodes.c;});
