import assert from 'node:assert/strict';
import test from 'node:test';
import {createRecallState} from '../src/workflow/recall-state.js';
import {artifactVisibility} from '../src/workflow/artifact-privacy.js';
let executeRecallNode,describeRecallNode,RECALL_OPERATIONS;
try{({executeRecallNode,describeRecallNode,RECALL_OPERATIONS}=await import('../src/workflow/operations/recall-nodes.js'));}catch(error){if(error.code!=='ERR_MODULE_NOT_FOUND')throw error;}
const scope={userId:'default-user',chatId:'Story-2',workflowId:'story',actorId:'mara'},visibility={kind:'actor-private',actorId:'mara'};
const data=value=>({kind:'data',value});
const presence=(status='present')=>data({schemaVersion:1,recordType:'scene-presence',sceneId:'scene',sourceId:'input',revision:'r1',actorId:'mara',status});
const records=()=>({kind:'data',visibility,value:[{id:'kiss-1',revision:'r1',actorId:'mara',text:'I remember the harbor kiss.',partnerIds:['elias'],tags:['harbor'],eventId:'event-1',recency:1},{id:'kiss-2',revision:'r2',actorId:'mara',text:'I remember a quieter farewell.',partnerIds:['elias'],tags:['farewell'],eventId:'event-2',recency:2}]});
const node=(extra={})=>({id:'recall',type:'workflow',operation:'recall',actorId:'mara',memorySetId:'moments',...extra});
const arm=(extra={})=>({schemaVersion:1,type:'recall-arm-proposal',actorId:'mara',memorySetId:'moments',target:'both',uses:'next-match',consumeOn:'accepted',hotkey:{code:'KeyM',ctrl:true,alt:false,shift:true,meta:false},...extra});
function fixture(){let current={...scope},generation={generationId:'g1',kind:'reply',stage:'pre',newlyGenerated:true};const session=createRecallState({getAuthority:()=>({scope:current,generation})}).data,captured=[],authorized=[];return {session,captured,authorized,setScope:value=>current=value,setGeneration:value=>generation=value,local:{phase:'pre',root:true,recallState:session,countTokens:async text=>({tokens:Math.ceil(text.length/4)}),authorizeRecallRecords:async(artifact,request)=>{authorized.push({artifact,request});return {ok:true,data:{scope,memorySetId:'moments'}};},stageRecallClaim:async(claim,activation)=>{captured.push({claim,activation});return {ok:true,data:{staged:true}};}}};}
test('Recall and Hotkey Arm descriptors and injected adapters exist',()=>{assert.equal(typeof executeRecallNode,'function');assert.equal(typeof describeRecallNode,'function');assert.equal(RECALL_OPERATIONS.recall.requestBound,0);assert.equal(RECALL_OPERATIONS['hotkey-arm'].modelRole,null);});
const run=(name,fn)=>test(name,{skip:!executeRecallNode},fn);
run('Hotkey Arm emits only a checked descriptive proposal and registration does not arm or generate',async()=>{const f=fixture();let registration;const result=await executeRecallNode({operation:'hotkey-arm',actorId:'mara',memorySetId:'moments'},{},{...f.local,registerRecallHotkey:async proposal=>{registration=proposal;return {ok:true,data:{registered:true}};}});assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.outputs.proposal.value.type,'recall-arm-proposal');assert.equal(registration.actorId,'mara');assert.equal(f.session.inspect().data.requests.length,0);assert.equal(f.captured.length,0);});
run('an unarmed generation skips without reading or requiring files or waiting for a hotkey',async()=>{const f=fixture();const result=await executeRecallNode(node(),{},f.local);assert.equal(result.ok,true);assert.equal(result.outputStates.out.status,'skipped');assert.equal(f.authorized.length,0);assert.equal(f.captured.length,0);});
run('armed Recall filters supplied records and routes private Guidance to its own present actor',async()=>{const f=fixture();f.session.queue(arm());const input=records();const result=await executeRecallNode(node({tags:['harbor'],partnerIds:['elias']}),{records:input,presence:presence()},f.local);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.authorized[0].artifact,input);assert.deepEqual(result.outputs.records.value.records.map(r=>r.id),['kiss-1']);assert.match(result.outputs.out.text,/harbor kiss/u);assert.equal(result.outputs.out.scope.actorId,'mara');assert.deepEqual(artifactVisibility(result.outputs.out),visibility);assert.equal(f.captured.length,1);assert.equal(JSON.stringify(result).includes('claimId'),false);assert.equal(f.session.inspect().data.requests[0].queued,true);});
run('absent actors skip while unresolved presence holds and an absent partner does not block an actor recalling their own memory',async()=>{for(const status of ['absent','unresolved']){const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{presence:presence(status)},f.local);assert.equal(result.ok,true);assert.equal(result.outputStates.out.status,status==='absent'?'skipped':'unresolved');assert.equal(f.authorized.length,0);assert.equal(f.captured.length,0);const next=await executeRecallNode(node(),{records:records(),presence:presence()},f.local);assert.equal(next.ok,true);assert.equal(f.captured.length,1);}});
run('automatic keyword activation and manual activation share one generation identity',async()=>{const f=fixture();f.session.queue(arm());const inputs={source:data({sourceId:'player',revision:'r1',watch:'player-message',text:'We return to the harbor.'}),records:records(),presence:presence()};const first=await executeRecallNode(node({activation:'armed-or-keyword',keywords:['harbor']}),inputs,f.local);assert.equal(first.ok,true);const second=await executeRecallNode(node({activation:'keyword',keywords:['harbor']}),inputs,f.local);assert.equal(second.outputStates.out.status,'skipped');assert.equal(second.outputStates.out.reason.code,'RECALL_ALREADY_ACTIVATED');assert.equal(f.captured.length,1);});
run('event activation requires confirmed actual actor-scoped occurrences and preserves event identities',async()=>{for(const status of ['candidate','confirmed']){const f=fixture();const inputs={events:data([{eventId:'event-1',eventType:'kiss',actorId:'mara',sourceId:'reply',revision:'r1',status,semantics:'actual',interpretation:'accepted'}]),records:records(),presence:presence()};const result=await executeRecallNode(node({activation:'event',eventTypes:['kiss']}),inputs,f.local);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.outputStates?.out?.status,status==='candidate'?'unresolved':undefined);assert.equal(f.captured.length,status==='confirmed'?1:0);if(status==='confirmed')assert.deepEqual(f.captured[0].activation.eventIds,['event-1']);}});
run('reply-only and swipe-only targets reject navigation and triggers first seen after generation cannot become pre guidance',async()=>{const f=fixture();f.session.queue(arm({target:'swipe'}));let result=await executeRecallNode(node(),{},f.local);assert.equal(result.outputStates.out.status,'skipped');f.setGeneration({generationId:'g2',kind:'swipe',stage:'pre',newlyGenerated:false});result=await executeRecallNode(node(),{},f.local);assert.equal(result.outputStates.out.status,'skipped');f.setGeneration({generationId:'g3',kind:'reply',stage:'pre',newlyGenerated:true});result=await executeRecallNode(node({activation:'keyword',keywords:['harbor']}),{source:data({sourceId:'reply',revision:'r1',watch:'st-reply',text:'harbor'}),records:records(),presence:presence()},f.local);assert.equal(result.ok,false);assert.equal(result.error.code,'RECALL_STAGE_MISMATCH');});
run('empty matches skip but missing, malformed or unauthorized records fail and restore the arm allowance',async()=>{for(const input of [undefined,data([{id:'bad',actorId:'other',text:'PRIVATE'}])]){const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{presence:presence(),...(input?{records:input}:{})},f.local);assert.equal(result.ok,false);assert.equal(f.captured.length,0);assert.equal(f.session.inspect().data.requests[0].queued,true);assert.equal(f.session.activate({actorId:'mara',memorySetId:'moments',target:'both'}).data.status,'activated');}const f=fixture();f.session.queue(arm());const empty=await executeRecallNode(node({tags:['missing']}),{records:records(),presence:presence()},f.local);assert.equal(empty.outputStates.out.status,'skipped');});
run('retrieval budgets are deterministic, report omissions, and never truncate a record',async()=>{const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node({limit:1,maxCharacters:100}),{records:records(),presence:presence()},f.local);assert.equal(result.ok,true);assert.equal(result.outputs.records.value.records[0].id,'kiss-2');assert.equal(result.outputs.report.value.omittedCount,1);const g=fixture();g.session.queue(arm());const bounded=await executeRecallNode(node({maxCharacters:8}),{records:records(),presence:presence()},g.local);assert.equal(bounded.ok,false);assert.equal(bounded.error.code,'RECALL_BUDGET_EXCEEDED');assert.equal(g.captured.length,0);});
run('scope/source changes and cancellation during authorization discard late private results and release claims',async()=>{for(const change of ['scope','source','cancel']){const f=fixture(),input=records(),abort=new AbortController();f.session.queue(arm());const local={...f.local,signal:abort.signal,authorizeRecallRecords:async()=>{if(change==='scope')f.setScope({...scope,chatId:'other'});if(change==='source')input.value[0].text='changed';if(change==='cancel')abort.abort();return {ok:true,data:{scope,memorySetId:'moments'}};}};const result=await executeRecallNode(node(),{records:input,presence:presence()},local);assert.equal(result.ok,false);assert.equal(f.captured.length,0);assert.equal(JSON.stringify(result).includes('harbor kiss'),false);}});
run('portable graph scope cannot replace trusted record authorization or live claim capture',async()=>{const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{records:records(),presence:presence()},{...f.local,authorizeRecallRecords:undefined});assert.equal(result.error.code,'RECALL_RECORD_AUTHORIZATION_MISSING');assert.equal(f.captured.length,0);const g=fixture();g.session.queue(arm());const unstaged=await executeRecallNode(node(),{records:records(),presence:presence()},{...g.local,stageRecallClaim:undefined});assert.equal(unstaged.error.code,'RECALL_SETTLEMENT_MISSING');assert.equal(g.session.inspect().data.requests[0].queued,true);});
run('descriptor and record boundaries reject getters, stale pins and malformed optional visibility before callbacks',async()=>{let reads=0;const unsafe=node();Object.defineProperty(unsafe,'phase',{get(){reads++;return 'pre';},enumerable:true});assert.equal(describeRecallNode(unsafe).ok,false);const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{records:{...records(),visibility:{kind:'actor-private',actorId:'mara',extra:true}},presence:presence()},f.local);assert.equal(result.ok,false);assert.equal(f.authorized.length,0);assert.equal(reads,0);assert.equal((await executeRecallNode(node(),{stale:data([])},f.local)).error.code,'UNSUPPORTED_INPUT');});
run('token budget uses the trusted tokenizer, retains whole records, and cannot accept late generation work',async()=>{const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node({maxTokens:16}),{records:records(),presence:presence()},{...f.local,countTokens:async text=>({tokens:Math.ceil(text.length/4)})});assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.outputs.records.value.records.length,1);assert.equal(result.outputs.report.value.omittedCount,1);assert.ok(result.outputs.report.value.tokens<=16);const g=fixture();g.session.queue(arm());const late=await executeRecallNode(node(),{records:records(),presence:presence()},{...g.local,countTokens:async()=>{g.setGeneration({generationId:'changed',kind:'reply',stage:'pre',newlyGenerated:true});return {tokens:1};}});assert.equal(late.ok,false);assert.equal(late.error.code,'STALE_RECALL_GENERATION');assert.equal(g.captured.length,0);});
run('unrelated actor-private trigger material cannot taint recall routed to this actor',async()=>{const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{records:records(),presence:{...presence(),visibility:{kind:'actor-private',actorId:'elias'}}},f.local);assert.equal(result.ok,false);assert.equal(result.error.code,'RECALL_ACTOR_MISMATCH');assert.equal(f.captured.length,0);});

run('scope field order and the actual Format JSON reader remain compatible with scoped record selection',async()=>{const {executeFileNode}=await import('../src/workflow/operations/file-nodes.js');const formatted=await executeFileNode({operation:'format',inputMode:'json-text',format:'json'},{in:{kind:'text',text:JSON.stringify(records().value),visibility}},{phase:'pre'});assert.equal(formatted.ok,true);const f=fixture();f.session.queue(arm());const reversed={actorId:'mara',workflowId:'story',chatId:'Story-2',userId:'default-user'};const result=await executeRecallNode(node(),{records:formatted.outputs.records,presence:presence()},{...f.local,authorizeRecallRecords:async()=>({ok:true,data:{scope:reversed,memorySetId:'moments'}})});assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.outputs.records.value.records.length,2);assert.ok(result.outputs.out.text.includes('\n'));assert.equal(result.outputs.out.text.includes('\\n'),false);});
run('explicitly unsuccessful staging or hotkey registration never claims success or retains an allowance',async()=>{const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{records:records(),presence:presence()},{...f.local,stageRecallClaim:async()=>({ok:true,data:{staged:false}})});assert.equal(result.ok,false);assert.equal(result.error.code,'RECALL_STAGING_FAILED');assert.equal(f.session.activate({actorId:'mara',memorySetId:'moments',target:'both'}).data.status,'activated');const g=fixture();const registration=await executeRecallNode({operation:'hotkey-arm',actorId:'mara',memorySetId:'moments'},{},{...g.local,registerRecallHotkey:async()=>({ok:true,data:{registered:false}})});assert.equal(registration.ok,false);});
run('manual target and preview execution never register a listener, reserve recall or stage consumption',async()=>{for(const mode of [{preview:true},{target:{workflowId:'story',nodeId:'recall',instancePath:[],portId:'out'}}]){const f=fixture();f.session.queue(arm());const result=await executeRecallNode(node(),{records:records(),presence:presence()},{...f.local,...mode});assert.equal(result.ok,true);assert.equal(result.outputStates.out.status,'skipped');assert.equal(f.captured.length,0);assert.equal(f.session.inspect().data.activationCount,0);let registrations=0;const hotkey=await executeRecallNode({operation:'hotkey-arm',actorId:'mara',memorySetId:'moments'},{},{...f.local,...mode,registerRecallHotkey:async()=>{registrations++;return {ok:true,data:{registered:true}};}});assert.equal(hotkey.ok,true);assert.equal(registrations,0);}});
run('actual normalized and confirmed event outputs feed Recall without changing occurrence identity',async()=>{const {normalizeOccurrences,confirmOccurrences}=await import('../src/workflow/operations/event-data.js');const source={sourceId:'s'.repeat(220),revision:'r'.repeat(220),sceneId:'scene',watch:'player-message',text:'Mara kisses Elias.',visibility:'public'};const normalized=normalizeOccurrences(source,[{eventType:'scene-action',actorId:'mara',position:{start:0,end:source.text.length},semantics:'actual'}],{actorIds:['mara','elias'],itemIds:[]});assert.equal(normalized.ok,true,JSON.stringify(normalized.error));const confirmed=confirmOccurrences(normalized.data.events,[{eventId:normalized.data.events[0].eventId,accepted:true}]);assert.equal(confirmed.ok,true);const f=fixture();const result=await executeRecallNode(node({activation:'event',eventTypes:['scene-action']}),{events:data(confirmed.data.events),records:records(),presence:presence()},f.local);assert.equal(result.ok,true,JSON.stringify(result.error));assert.deepEqual(f.captured[0].activation.eventIds,[confirmed.data.events[0].eventId]);});
run('record source references must retain checked identity and revision rather than arbitrary metadata',async()=>{const f=fixture();f.session.queue(arm());const input=records();input.value[0].sourceRefs='PRIVATE unchecked payload';const result=await executeRecallNode(node(),{records:input,presence:presence()},f.local);assert.equal(result.ok,false);assert.equal(result.error.code,'INVALID_RECALL_RECORDS');assert.equal(f.captured.length,0);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);});
run('settings mutation and private callback diagnostics cannot publish or consume a captured recall',async()=>{for(const change of ['settings','error']){const f=fixture(),settings=node();f.session.queue(arm());const result=await executeRecallNode(settings,{records:records(),presence:presence()},{...f.local,authorizeRecallRecords:async()=>{if(change==='settings')settings.tags=['changed'];else throw new Error('PRIVATE credential diagnostic');return {ok:true,data:{scope,memorySetId:'moments'}};}});assert.equal(result.ok,false);assert.equal(result.error.code,change==='settings'?'STALE_RECALL_SETTINGS':'RECALL_RECORDS_UNAVAILABLE');assert.equal(f.captured.length,0);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);assert.equal(f.session.activate({actorId:'mara',memorySetId:'moments',target:'both'}).data.status,'activated');}});
const generation=()=>({generationId:'g1',kind:'reply',stage:'pre',newlyGenerated:true});
for(const callback of ['current','claim'])for(const mutation of ['settings','input','cancel'])run('final '+callback+' authority callback '+mutation+' cannot publish staged private Guidance',async()=>{const settings=node(),inputs={records:{kind:'data',visibility,value:[{id:'m1',actorId:'mara',text:'PRIVATE original memory'}]},presence:presence()},abort=new AbortController();let finalCalls=0,staged=0,mutated=false;
 const change=()=>{if(mutated)return;mutated=true;if(mutation==='settings')settings.tags=['changed'];else if(mutation==='input')inputs.records.value[0].text='changed';else abort.abort();};
 const session=createRecallState({getAuthority:()=>{if(staged&&++finalCalls===(callback==='current'?1:2))change();return {scope,generation:generation()};}}).data;session.queue(arm());
 const result=await executeRecallNode(settings,inputs,{phase:'pre',root:true,signal:abort.signal,recallState:session,countTokens:async()=>({tokens:1}),authorizeRecallRecords:async()=>({ok:true,data:{scope,memorySetId:'moments'}}),stageRecallClaim:async()=>{staged++;return {ok:true,data:{staged:true}};}});
 assert.equal(mutated,true);assert.equal(staged,1);assert.equal(result.ok,false);assert.equal(result.error.code,{settings:'STALE_RECALL_SETTINGS',input:'STALE_RECALL_INPUT',cancel:'ABORTED'}[mutation]);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);assert.equal(result.outputs,undefined);const inspected=session.inspect();assert.equal(inspected.data.activationCount,0);assert.equal(inspected.data.requests[0].queued,true);assert.deepEqual(inspected.data.requests[0].pendingGenerationIds,[]);
});
for(const mutation of ['settings','input','cancel'])run('tokenizer claim authority callback '+mutation+' is rejected before staging private Guidance',async()=>{const settings=node(),inputs={records:records(),presence:presence()},abort=new AbortController();let counted=false,authorityCalls=0,staged=0;
 const session=createRecallState({getAuthority:()=>{if(counted&&++authorityCalls===2){if(mutation==='settings')settings.tags=['changed'];else if(mutation==='input')inputs.records.value[0].text='changed';else abort.abort();}return {scope,generation:generation()};}}).data;session.queue(arm());const result=await executeRecallNode(settings,inputs,{phase:'pre',root:true,signal:abort.signal,recallState:session,countTokens:async()=>{counted=true;return {tokens:1};},authorizeRecallRecords:async()=>({ok:true,data:{scope,memorySetId:'moments'}}),stageRecallClaim:async()=>{staged++;return {ok:true,data:{staged:true}};}});assert.equal(result.ok,false);assert.equal(result.error.code,{settings:'STALE_RECALL_SETTINGS',input:'STALE_RECALL_INPUT',cancel:'ABORTED'}[mutation]);assert.equal(staged,0);assert.equal(result.outputs,undefined);assert.equal(session.inspect().data.activationCount,0);
});
for(const facet of ['generationId','kind','stage','newlyGenerated'])run('the final coherent authority callback '+facet+' change rejects private Guidance without consuming',async()=>{const inputs={records:{kind:'data',visibility,value:[{id:'m1',actorId:'mara',text:'PRIVATE original memory'}]},presence:presence()};let ownedGeneration=generation(),staged=0,finalCalls=0;const session=createRecallState({getAuthority:()=>{if(staged&&++finalCalls===2)ownedGeneration={...ownedGeneration,[facet]:{generationId:'g2',kind:'swipe',stage:'post',newlyGenerated:false}[facet]};return {scope,generation:ownedGeneration};}}).data;session.queue(arm());const result=await executeRecallNode(node(),inputs,{phase:'pre',root:true,recallState:session,countTokens:async()=>({tokens:1}),authorizeRecallRecords:async()=>({ok:true,data:{scope,memorySetId:'moments'}}),stageRecallClaim:async()=>{staged++;return {ok:true,data:{staged:true}};}});assert.equal(staged,1);assert.equal(result.ok,false);assert.equal(result.error.code,'STALE_RECALL_GENERATION');assert.equal(result.outputs,undefined);assert.equal(JSON.stringify(result).includes('PRIVATE'),false);const inspected=session.inspect();assert.equal(inspected.data.requests[0].queued,true);assert.equal(inspected.data.activationCount,0);assert.deepEqual(inspected.data.requests[0].pendingGenerationIds,[]);});

test('unretained reservations are revoked after scope changes during async record authorization or token counting',async()=>{for(const stage of ['authorization','tokens']){const f=fixture();f.session.queue(arm());const local={...f.local,...(stage==='authorization'?{authorizeRecallRecords:async()=>{f.setScope({});return {ok:true,data:{scope,memorySetId:'moments'}};}}:{countTokens:async()=>{f.setScope({});return {tokens:1};}})};const result=await executeRecallNode(node(),{records:records(),presence:presence()},local);assert.equal(result.ok,false);assert.equal(f.captured.length,0);f.setScope(scope);assert.equal(f.session.inspect().data.requests[0].pendingGenerationCount,0);assert.equal(f.session.activate({actorId:'mara',memorySetId:'moments',target:'both'}).data.status,'activated');}});
