import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createNativeWorkflowController } from '../src/workflow/host.js?v=0.26.0';
import { createChatDocumentCatalog } from '../src/workflow/document-catalog.js?v=0.26.0';
import { operationDefaults } from '../src/workflow/catalog.js?v=0.26.0';
const nextTurn = () => new Promise(resolve => setTimeout(resolve, 10));
function unifiedGraph({ guidance = false, revise = true } = {}) {
    const nodes = { send: { id: 'send', type: 'workflow', operation: 'on-send' }, generate: { id: 'generate', type: 'workflow', operation: 'generate-reply' }, review: { id: 'review', type: 'workflow', operation: 'review-publish' } };
    const wires = { activation: { id: 'activation', route: 'wire', from: 'send', fromPort: 'activation', to: 'generate', toPort: 'activation' } };
    if (revise) nodes.revise = { id: 'revise', type: 'workflow', operation: 'revise-draft', scope: 'whole', instructions: 'Tighten prose.' };
    wires.reply = { id: 'reply', route: 'wire', from: 'generate', fromPort: 'draft', to: revise ? 'revise' : 'review', toPort: 'draft' };
    if (revise) wires.review = { id: 'review', route: 'wire', from: 'revise', fromPort: 'out', to: 'review', toPort: 'draft' };
    if (guidance) { nodes.guide = { id: 'guide', type: 'workflow', operation: 'compose', outputKind: 'guidance', sections: [{ name: 'Style', text: 'Use vivid prose.' }] }; wires.guidance = { id: 'guidance', route: 'wire', from: 'guide', fromPort: 'out', to: 'generate', toPort: 'guidance' }; }
    return { id: 'unified', name: 'Unified test', schema: 3, runtime: 2, mode: 'native-unified', nodes, wires, portals: {}, definitions: {} };
}
function nativeFixture(graph = unifiedGraph(), options = {}) {
    const listeners = new Map(), events = [], results = [];
    const c = { chatId: 'story', characterId: 0, groupId: null, characters: [{ data: { name: 'Mara' } }], chat: [{ mes: 'I open the door.', is_user: true, extra: {} }], extensionPrompts: {}, eventTypes: Object.fromEntries(['GENERATION_STARTED', 'GENERATION_STOPPED', 'GENERATION_ENDED', 'MESSAGE_RECEIVED', 'MESSAGE_SENT', 'CHAT_CHANGED', 'MESSAGE_EDITED', 'MESSAGE_UPDATED', 'MESSAGE_DELETED', 'MESSAGE_SWIPED', 'MESSAGE_SWIPE_DELETED'].map(name => [name, name])) };
    c.eventSource = { on(name, fn) { const bucket = listeners.get(name) ?? []; bucket.push(fn); listeners.set(name, bucket); }, removeListener(name, fn) { listeners.set(name, (listeners.get(name) ?? []).filter(value => value !== fn)); }, async emit(name, ...args) { for (const listener of listeners.get(name) ?? []) await listener(...args); } };
    c.setExtensionPrompt = (key, value) => { c.extensionPrompts[key] = { value }; };
    c.saveChat = async () => {}; c.updateMessageBlock = async () => {}; c.swipe = { refresh: async () => {} };
    let busy = false, user = 'default-user', requests = 0;
    const controller = createNativeWorkflowController({ ...options.ports, context: () => c, getGraph: phase => phase === 'unified' ? graph : undefined, isEnabled: () => true, userId: () => user, isBusy: () => busy, countTokens: options.countTokens ?? (async text => ({ tokens: Math.ceil(text.length / 4) })), resolveBinding: options.resolveBinding ?? (() => ({ ok: true, data: { profileId: 'fixed', model: 'test' } })), request: options.request ?? (async () => { requests++; return { ok: true, data: { text: 'Revised reply.', finish: 'stop' } }; }), onEvent: event => events.push(event), onResult: result => results.push(result), syncMesToSwipe(index) { const m = c.chat[index]; m.swipes[m.swipe_id] = m.mes; return true; }, syncSwipeToMes(index, swipeId) { const m = c.chat[index]; m.swipe_id = swipeId; m.mes = m.swipes[swipeId]; Object.assign(m, structuredClone(m.swipe_info[swipeId])); return true; } });
    controller.subscribe();
    return { c, controller, events, results, setBusy(value) { busy = value; }, setUser(value) { user = value; }, requests: () => requests, async start(type = 'normal') { busy = true; await c.eventSource.emit('GENERATION_STARTED', type, {}, false); return controller.beforeGenerate(c.chat.map(message => ({ ...message })), 8192, options.abort ?? (() => {}), type); } };
}
function addReply(f, { normalized = true, text = 'Native reply.' } = {}) {
    const now = new Date().toISOString(), m = { mes: text, is_user: false, extra: {}, gen_started: now, gen_finished: now };
    if (normalized) Object.assign(m, { swipe_id: 0, swipes: [text], swipe_info: [{ gen_started: now, gen_finished: now, extra: {} }] });
    f.c.chat.push(m); return m;
}
async function settled(f) { for (let tries = 0; tries < 30 && !f.results.length; tries++) await nextTurn(); assert.equal(f.results.length, 1, 'Owned continuation must settle promptly'); return f.results[0]; }


function clockGraph(){const g=unifiedGraph({revise:false});const node=(id,operation,extra={})=>({id,type:'workflow',...operationDefaults(operation),...extra});const wire=(id,from,fromPort,to,toPort)=>g.wires[id]={id,route:'wire',from,fromPort,to,toPort};g.nodes.clock=node('clock','story-clock',{clockId:'clock'});g.nodes.duration=node('duration','text',{text:'{"kind":"duration","minutes":720}'});g.nodes.proposal=node('proposal','json-decode');g.nodes.advance=node('advance','advance-time',{schedules:[{scheduleId:'curse',kind:'daily',minuteOfDay:840}]});g.nodes.commit=node('commit','commit-clock');wire('parse','duration','out','proposal','in');wire('clock','clock','out','advance','clock');wire('proposal','proposal','out','advance','proposal');wire('commit','advance','report','commit','projection');return g;}
function clockFixture(){let catalog,saves=0;const f=nativeFixture(clockGraph(),{ports:{documentCatalog:{capture:()=>catalog.capture()},persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}}}});f.c.chatMetadata={};catalog=createChatDocumentCatalog({getContext:()=>f.c,getUserId:()=> 'default-user'});catalog.define({targetId:'clock',name:'Clock',format:'json',visibility:{kind:'public'},content:JSON.stringify({schemaVersion:1,clockId:'clock',calendarId:'days',revision:1,dayLengthMinutes:1440,absoluteMinute:360,settledTimeEventIds:[]})});return {...f,catalog,saves:()=>saves,async complete(){const prepared=await f.start();assert.equal(prepared.ok,true,JSON.stringify(prepared.error));addReply(f);await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'normal');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);return settled(f);}};}
test('actual native clock projection waits for review and commits the effective clock, revision and occurrence ledger',async()=>{const f=clockFixture(),result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');const clock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(clock.absoluteMinute,840);assert.equal(clock.revision,2);assert.equal(clock.pendingTimeAdvance.minutes,240);assert.equal(clock.settledTimeEventIds.length,1);assert.equal(f.saves(),1);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),1);});
test('actual native clock cancellation and catalog revision changes save nothing',async()=>{const f=clockFixture(),result=await f.complete();f.controller.reject(result.reviewHandles[0]);assert.equal(f.saves(),0);const g=clockFixture(),review=await g.complete();g.catalog.remove('clock');const accepted=await g.controller.apply(review.reviewHandles[0]);assert.equal(accepted.ok,false);assert.equal(g.saves(),0);assert.equal(g.c.chat[1].swipes.length,1);});
test('manual unified Story Clock and Clock Commit targets return bounded previews without persistence',async()=>{const f=clockFixture(),graph=clockGraph();const result=await f.controller.runTarget(graph,{workflowId:'unified',instancePath:[],nodeId:'commit',portId:'receipt'});assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,0);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);});
test('a generated swipe of an accepted player turn replays the clock without advancing or saving twice',async()=>{const f=clockFixture(),first=await f.complete();assert.equal((await f.controller.apply(first.reviewHandles[0])).ok,true);const count=f.results.length;const ready=await f.start('swipe');assert.equal(ready.ok,true,JSON.stringify(ready.error));const m=f.c.chat[1],now=new Date().toISOString();m.swipes.push('Alternative native prose.');m.swipe_info.push({gen_started:now,gen_finished:now,extra:{}});m.swipe_id=m.swipes.length-1;m.mes=m.swipes[m.swipe_id];m.gen_started=now;m.gen_finished=now;await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'swipe');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);for(let tries=0;tries<30&&f.results.length===count;tries++)await nextTurn();const result=f.results.at(-1);assert.equal(result.ok,true,JSON.stringify(result.error));const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');const clock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(clock.revision,2);assert.equal(clock.absoluteMinute,840);assert.equal(clock.settledTimeEventIds.length,1);assert.equal(f.saves(),1);});
test('native scheduled time occurrence may stage a separate checked event ledger with its clock',async()=>{const graph=clockGraph();const node=(id,operation,extra={})=>graph.nodes[id]={id,type:'workflow',...operationDefaults(operation),...extra};const wire=(id,from,fromPort,to,toPort)=>graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};node('readEvents','read-file',{targetId:'time-events'});node('writeEvents','write-file',{mode:'add-unique',key:'occurrenceId'});wire('event-ref','readEvents','reference','writeEvents','reference');wire('event-records','advance','occurrences','writeEvents','records');wire('event-evidence','advance','occurrences','writeEvents','evidence');let catalog,saves=0;const f=nativeFixture(graph,{ports:{documentCatalog:{capture:()=>catalog.capture()},persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}}}});f.c.chatMetadata={};catalog=createChatDocumentCatalog({getContext:()=>f.c,getUserId:()=> 'default-user'});catalog.define({targetId:'clock',name:'Clock',format:'json',visibility:{kind:'public'},content:JSON.stringify({schemaVersion:1,clockId:'clock',calendarId:'days',revision:1,dayLengthMinutes:1440,absoluteMinute:360,settledTimeEventIds:[]})});catalog.define({targetId:'time-events',name:'Time events',format:'json',visibility:{kind:'public'},content:'[]'});assert.equal((await f.start()).ok,true);addReply(f);await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'normal');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);const result=await settled(f);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(saves,0);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(saves,2);const event=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['time-events'].content)[0];assert.equal(event.dueMinute,840);const clock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.deepEqual(clock.settledTimeEventIds,[event.occurrenceId]);});

test('two native Advance Time steps replay the same accepted generated swipe from the actual turn start',async()=>{
 const graph=clockGraph();graph.nodes.duration.text='{"kind":"duration","minutes":60}';graph.nodes.advance.schedules=[];graph.nodes.second={id:'second',type:'workflow',...operationDefaults('advance-time')};graph.wires.secondClock={id:'secondClock',route:'wire',from:'advance',fromPort:'clock',to:'second',toPort:'clock'};graph.wires.secondProposal={id:'secondProposal',route:'wire',from:'proposal',fromPort:'out',to:'second',toPort:'proposal'};graph.wires.commit.from='second';let catalog,saves=0;const f=nativeFixture(graph,{ports:{documentCatalog:{capture:()=>catalog.capture()},persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}}}});f.c.chatMetadata={};catalog=createChatDocumentCatalog({getContext:()=>f.c,getUserId:()=> 'default-user'});catalog.define({targetId:'clock',name:'Clock',format:'json',visibility:{kind:'public'},content:JSON.stringify({schemaVersion:1,clockId:'clock',calendarId:'days',revision:1,dayLengthMinutes:1440,absoluteMinute:0,settledTimeEventIds:[]})});assert.equal((await f.start()).ok,true);addReply(f);await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'normal');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);const first=await settled(f);assert.equal(first.ok,true,JSON.stringify(first.error));assert.equal((await f.controller.apply(first.reviewHandles[0])).ok,true);let clock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(clock.absoluteMinute,120);assert.equal(clock.acceptedTimeAdvances[0].previousClock.absoluteMinute,0);const count=f.results.length;assert.equal((await f.start('swipe')).ok,true);const m=f.c.chat[1],now=new Date().toISOString();m.swipes.push('Second native reply.');m.swipe_info.push({gen_started:now,gen_finished:now,extra:{}});m.swipe_id=m.swipes.length-1;m.mes=m.swipes[m.swipe_id];m.gen_started=now;m.gen_finished=now;await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'swipe');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);for(let tries=0;tries<30&&f.results.length===count;tries++)await nextTurn();const second=f.results.at(-1);assert.equal(second.ok,true,JSON.stringify(second.error));assert.equal((await f.controller.apply(second.reviewHandles[0])).ok,true);clock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].clock.content);assert.equal(clock.absoluteMinute,120);assert.equal(clock.revision,2);assert.equal(saves,1);
});
