import assert from 'node:assert/strict';
import test from 'node:test';
import { executeControl } from '../src/workflow/operations/control-nodes.js?v=0.27.0';
import { executeCollection } from '../src/workflow/operations/collection-nodes.js?v=0.27.0';
import { executeModelNode } from '../src/workflow/operations/model-nodes.js?v=0.27.0';
import { executeEvent } from '../src/workflow/operations/event-nodes.js?v=0.27.0';
const actor={kind:'actor-private',actorId:'mara'};
const operation=(operation,extra={})=>({id:operation,type:'workflow',operation,operationVersion:1,...extra});
test('collection reducers and conditions retain the scope of erased source fields through model output and public assembly',async()=>{const count=executeCollection(operation('collection',{mode:'count'}),{in:{kind:'data',value:[{feeling:'PRIVATE'}],visibility:actor}});assert.equal(count.ok,true,JSON.stringify(count.error));assert.deepEqual(count.artifact.visibility,actor);const condition=await executeControl(operation('condition',{operator:'at-least',value:1}),{in:count.artifact},{phase:'post'});assert.equal(condition.ok,true,JSON.stringify(condition.error));assert.deepEqual(condition.outputs.out.visibility,actor);let calls=0;const text=await executeModelNode(operation('model-call',{inputKind:'data',outputKind:'text'}),{prompt:{kind:'text',text:'Write private reflection.'},data:condition.outputs.out},{phase:'post',request:async()=>{calls++;return {ok:true,data:{text:'PRIVATE feeling.',finish:'stop'}};}});assert.equal(text.ok,true,JSON.stringify(text.error));assert.deepEqual(text.artifact.visibility,actor);const result=await executeModelNode(operation('append',{sectionId:'notes'}),{draft:{kind:'draft',text:'Public story.',source:{token:'draft',originalText:'Public story.'}},section:text.artifact},{phase:'post'});assert.equal(result.ok,false);assert.equal(result.error.code,'PRIVATE_MATERIAL');assert.equal(calls,1);});
test('control selection cannot declassify a selected public value using private decision evidence',async()=>{const result=await executeControl(operation('branch'),{in:{kind:'data',value:'Public value'},condition:{kind:'data',value:{accepted:true},visibility:actor}},{phase:'post'});assert.equal(result.ok,true);assert.deepEqual(result.outputs.yes.visibility,actor);const collected=await executeControl(operation('collect'),{base:result.outputs.yes},{phase:'post'});assert.equal(collected.ok,true);assert.deepEqual(collected.outputs.out.visibility,actor);});
test('actor visibility on model or file Data can pass checked event ports without dropping its scope',async()=>{const result=await executeEvent(operation('scene-presence',{actorId:'mara'}),{in:{kind:'data',value:{sceneId:'scene',sourceId:'source',revision:'rev',actors:[{actorId:'mara',status:'present'}]},visibility:actor}},{phase:'post'});assert.equal(result.ok,true,JSON.stringify(result.error));assert.deepEqual(result.artifact.visibility,actor);});

test('a private condition cannot select a public Draft for publication',async()=>{const native={kind:'draft',text:'Public story.',source:{token:'native-public',originalText:'Public story.'}};const result=await executeControl(operation('branch',{artifactKind:'draft'}),{in:native,condition:{kind:'data',value:{accepted:true},visibility:actor}},{phase:'post'});assert.equal(result.ok,false);assert.equal(result.error.code,'PRIVATE_MATERIAL');assert.equal(native.text,'Public story.');});
test('mixed actor private reductions remain hidden rather than choosing one actor or discarding source restrictions',async()=>{const other={kind:'actor-private',actorId:'laya'};const result=await executeControl(operation('collect'),{base:{kind:'data',value:1,visibility:actor},optional:{kind:'data',value:2,visibility:other}},{phase:'post'});assert.equal(result.ok,true);assert.deepEqual(result.outputs.out.visibility,{kind:'hidden'});});
