import assert from 'node:assert/strict';
import test from 'node:test';
const api=await import('../src/workflow/document-catalog.js?v=0.26.0').catch(()=>({}));
function fixture(){let user='default-user',saves=0;const c={chatId:'story',chat:[],chatMetadata:{otherExtension:{keep:true}}};return {c,user:value=>{user=value;},saves:()=>saves,create:()=>api.createChatDocumentCatalog({getContext:()=>c,getUserId:()=>user,saveMetadata:async()=>{saves++;}})};}
test('manual document definitions authorize named templates while list previews omit their contents',()=>{assert.equal(typeof api.createChatDocumentCatalog,'function');const f=fixture(),catalog=f.create();assert.equal(catalog.define({targetId:'souls.json',name:'Sword souls',format:'json',content:'[]',visibility:{kind:'public'}}).ok,true);assert.equal(f.saves(),0);const definition=catalog.definition('souls.json');assert.equal(definition.data.content,'[]');assert.deepEqual(catalog.snapshot().data.documents.map(doc=>[doc.targetId,doc.format]),[['souls.json','json']]);assert.equal(Object.hasOwn(catalog.snapshot().data.documents[0],'content'),false);assert.deepEqual(f.c.chatMetadata.otherExtension,{keep:true});assert.equal(catalog.definition('unauthorized').error.code,'FILE_NOT_AUTHORIZED');});
test('actor-private definitions retain their target scope and old leases revoke on author or document changes',()=>{const f=fixture(),catalog=f.create();catalog.define({targetId:'mara.json',name:'Mara moments',format:'json',content:'[]',visibility:{kind:'actor-private',actorId:'mara'}});const captured=catalog.capture();assert.equal(captured.ok,true);assert.equal(captured.data.isCurrent(),true);catalog.define({targetId:'mara.json',name:'Mara memories',format:'json',content:'[]',visibility:{kind:'actor-private',actorId:'mara'}});assert.equal(captured.data.isCurrent(),false);const fresh=catalog.capture();f.user('another-user');assert.equal(fresh.data.isCurrent(),false);assert.equal(catalog.snapshot().data.documents.length,0);f.user('default-user');assert.equal(catalog.definition('mara.json').data.visibility.actorId,'mara');assert.equal(fresh.data.isCurrent(),false,'returning to a former scope must not resurrect a lease');});
test('definitions reject malformed formats, inaccessible paths and accessors before modifying metadata',()=>{const f=fixture(),catalog=f.create();const before=structuredClone(f.c.chatMetadata);let reads=0;assert.equal(catalog.define({targetId:'../outside',name:'bad',format:'json',content:'[]',visibility:{kind:'public'}}).ok,false);assert.equal(catalog.define({targetId:'broken.json',name:'bad',format:'json',content:'broken',visibility:{kind:'public'}}).ok,false);assert.equal(catalog.define(Object.defineProperty({},'targetId',{enumerable:true,get(){reads++;return 'bad';}})).ok,false);assert.equal(reads,0);assert.deepEqual(f.c.chatMetadata,before);});
test('stored file format is locked and unregistering preserves existing file content',()=>{const f=fixture(),catalog=f.create();catalog.define({targetId:'souls.json',name:'Souls',format:'json',content:'[]',visibility:{kind:'public'}});f.c.chatMetadata.latticeDocuments={'default-user':{'souls.json':{content:'[{"id":"s1"}]',format:'json',revision:1,receipts:[]}}};assert.equal(catalog.define({targetId:'souls.json',name:'Souls',format:'text',content:'',visibility:{kind:'public'}}).error.code,'FILE_FORMAT_LOCKED');assert.equal(catalog.remove('souls.json').ok,true);assert.equal(catalog.definition('souls.json').error.code,'FILE_NOT_AUTHORIZED');assert.equal(f.c.chatMetadata.latticeDocuments['default-user']['souls.json'].content,'[{"id":"s1"}]');});
test('manual metadata save is explicit and void host acknowledgement remains unverified',async()=>{const f=fixture(),catalog=f.create();catalog.define({targetId:'notes.txt',name:'Notes',format:'text',content:'One memory.',visibility:{kind:'hidden'}});assert.equal(f.saves(),0);const result=await catalog.save();assert.equal(result.ok,true);assert.equal(result.data.acknowledged,false);assert.equal(f.saves(),1);});

test('document capture bounds templates individually and preserves other users without invoking accessors',()=>{const f=fixture(),catalog=f.create();for(let i=0;i<4;i++)assert.equal(catalog.define({targetId:'memory'+i+'.txt',name:'Memory '+i,format:'text',content:'M'.repeat(90000),visibility:{kind:'hidden'}}).ok,true);assert.equal(catalog.capture().data.documents.length,4);f.c.chatMetadata.latticeDocumentCatalog['other-user']={schema:1,documents:{}};const previous=structuredClone(f.c.chatMetadata.latticeDocumentCatalog['other-user']);assert.equal(catalog.define({targetId:'public.txt',name:'Public',format:'text',content:'Text',visibility:{kind:'public'}}).ok,true);assert.deepEqual(f.c.chatMetadata.latticeDocumentCatalog['other-user'],previous);let reads=0;Object.defineProperty(f.c.chatMetadata.latticeDocumentCatalog,'untrusted-user',{enumerable:true,get(){reads++;throw new Error('Must not run');}});assert.equal(catalog.snapshot().ok,false);assert.equal(catalog.define({targetId:'blocked.txt',name:'Blocked',format:'text',content:'Text',visibility:{kind:'public'}}).ok,false);assert.equal(reads,0);});

test('final host callbacks cannot restore a stale other-user namespace during local definition merge',()=>{let calls=0;const c={chatId:'story',chat:[],chatMetadata:{latticeDocumentCatalog:{'other-user':{note:'old'}}}};const catalog=api.createChatDocumentCatalog({getContext:()=>{if(++calls===3)c.chatMetadata.latticeDocumentCatalog['other-user']={note:'new from other writer'};return c;},getUserId:()=> 'default-user'});assert.equal(catalog.define({targetId:'notes.txt',name:'Notes',format:'text',content:'Text',visibility:{kind:'public'}}).ok,true);assert.equal(c.chatMetadata.latticeDocumentCatalog['other-user'].note,'new from other writer');});

test('prepared definition and removal cannot rebase to a user, chat or catalog changed by installation callbacks',()=>{
 for(const action of ['define','remove'])for(const change of ['user','chat','catalog']){
  let user='user-a',calls=0,armed=false;
  const c={chatId:'story',chat:[],chatMetadata:{}};
  const catalog=api.createChatDocumentCatalog({getContext:()=>{if(armed&&++calls===2){if(change==='user')user='user-b';if(change==='chat')c.chatId='other-story';if(change==='catalog')c.chatMetadata.latticeDocumentCatalog['user-a'].documents['external.txt']={targetId:'external.txt',name:'External',format:'text',content:'Other write',visibility:{kind:'public'},revision:'external-revision'};}return c;},getUserId:()=>user});
  assert.equal(catalog.define({targetId:'private.txt',name:'Private A',format:'text',content:'PRIVATE A',visibility:{kind:'actor-private',actorId:'actor-a'}}).ok,true);
  armed=true;calls=0;
  const result=action==='define'?catalog.define({targetId:'new.txt',name:'New',format:'text',content:'A CONTENT',visibility:{kind:'hidden'}}):catalog.remove('private.txt');
  assert.equal(result.ok,false,action+' '+change+' must reject stale preparation');
  assert.equal(c.chatMetadata.latticeDocumentCatalog['user-b'],undefined,'prepared user-a contents never move to another user');
  assert.equal(c.chatMetadata.latticeDocumentCatalog['user-a'].documents['private.txt'].content,'PRIVATE A');
  assert.equal(c.chatMetadata.latticeDocumentCatalog['user-a'].documents['new.txt'],undefined);
  if(change==='catalog')assert.equal(c.chatMetadata.latticeDocumentCatalog['user-a'].documents['external.txt'].content,'Other write');
 }
});
