import assert from 'node:assert/strict';
import {test} from 'node:test';
import {registerHooks} from 'node:module';
import {actorHostFixture as fixture,mara,elias} from './helpers/native-actor-host-fixture.mjs';
import {operationDefaults} from '../src/workflow/catalog.js?v=0.27.0';
test('actual native Character Direction scopes a separate system prompt to the participating selected actor',async()=>{
 const f=fixture(),ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,2);const direction=JSON.stringify(f.requests[1].messages);assert.ok(direction.includes('PRIVATE SEA'));assert.equal(direction.includes('PRIVATE FIRE'),false);assert.ok(f.requests[1].messages[0].content.includes('Mara alone'));assert.ok(Object.values(f.c.extensionPrompts).some(p=>p.value==='Mara considers the sea.'));const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);f.controller.dispose();
});
test('actual native paired actor file/model legs isolate private material and settle only after acceptance',async()=>{
 const f=fixture('files'),ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,0);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.requests.length,3);const calls=f.requests.slice(1).map(r=>JSON.stringify(r.messages));assert.ok(calls.some(s=>s.includes('PRIVATE SEA')));assert.ok(calls.some(s=>s.includes('PRIVATE FIRE')));assert.equal(calls.some(s=>s.includes('PRIVATE SEA')&&s.includes('PRIVATE FIRE')),false);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');const saved=f.c.chatMetadata.latticeDocuments['default-user'];assert.ok(saved['mara.md'].content.includes('Mara considers the sea.'));assert.equal(saved['mara.md'].content.includes('FIRE'),false);assert.ok(saved['elias.md'].content.includes('Elias considers the fire.'));assert.equal(saved['elias.md'].content.includes('SEA'),false);assert.equal(f.c.chat[1].mes.includes('PRIVATE'),false);f.controller.dispose();
});
test('a private-card mutation during the actor request tokenizer holds before transmission',async()=>{
 const f=fixture('direction',{onCount(text,c){if(text.includes('PRIVATE SEA'))c.characters[0].data.description='Changed private source.';}}),ready=await f.start();assert.equal(ready.ok,false);assert.equal(ready.error.code,'ACTOR_CONTEXT_CHANGED');assert.equal(f.requests.length,1);assert.equal(Object.values(f.c.extensionPrompts).some(p=>p.value),false);f.controller.dispose();
});

test('paired private file consequences preserve confirmed first write across second conflict and retry without model calls',async()=>{
 let conflicted=false;const f=fixture('files',{onVerify(selection,c){if(selection.kind==='document'&&selection.targetId==='mara.md'&&!conflicted){conflicted=true;c.chatMetadata.latticeDocuments['default-user']['elias.md']={targetId:'elias.md',revision:1,format:'markdown',content:'Foreign confirmed edit',receipts:[]};}}});
 assert.equal((await f.start()).ok,true);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'partial');const saved=structuredClone(f.c.chatMetadata.latticeDocuments['default-user']['mara.md']),calls=f.requests.length;
 assert.ok(saved.content.includes('Mara considers the sea.'));assert.equal(f.c.chatMetadata.latticeDocuments['default-user']['elias.md'].content,'Foreign confirmed edit');const retried=await f.controller.apply(result.reviewHandles[0]);assert.equal(retried.ok,true,JSON.stringify(retried.error));assert.equal(retried.settlement.status,'partial');assert.equal(f.requests.length,calls);assert.deepEqual(f.c.chatMetadata.latticeDocuments['default-user']['mara.md'],saved);assert.equal(f.c.chat[1].swipes.length,2);f.controller.dispose();
});
test('native actor private-model response is discarded if its captured card changes during the request',async()=>{
 let changed=false;const f=fixture('files',{onRequest(request,material,c){if(!changed&&material.request?.includes('PRIVATE SEA')){changed=true;c.characters[0].data.description='Foreign private card edit';}}});assert.equal((await f.start()).ok,true);const result=await f.complete();assert.equal(result.ok,false);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);assert.equal(result.reviewHandles.length,0);f.controller.dispose();
});
function addMemoryFlow(f){
 delete f.graph.nodes.direction;delete f.graph.wires.present;delete f.graph.wires.guidance;f.graph.nodes.cast.phase='post';f.graph.nodes.mara.phase='post';f.graph.nodes.elias.phase='post';delete f.graph.nodes.scene;delete f.graph.wires.castContext;
 const node=(id,operation,settings={})=>f.graph.nodes[id]={id,type:'workflow',...operationDefaults(operation),...settings},wire=(id,from,fromPort,to,toPort)=>f.graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};
 node('scopeText','text',{text:JSON.stringify({sourceId:'authored',revision:'authored',sceneId:'Story-2',visibility:'public'})});node('scope','json-decode');node('source','draft-event-source');wire('scopeText','scopeText','out','scope','in');wire('scope','scope','out','source','scope');wire('draftSource','generate','draft','source','in');wire('castSource','source','out','cast','data');node('entitiesText','text',{text:JSON.stringify({actorIds:[mara,elias],itemIds:['sword']})});node('entities','json-decode');wire('entities','entitiesText','out','entities','in');
 node('mention','item-mention-trigger',{actorId:mara,itemId:'sword',aliases:['Sword'],watch:'draft'});wire('source','source','out','mention','source');wire('entitySource','entities','out','mention','entities');
 node('holdersText','text',{text:JSON.stringify({sword:mara})});node('holders','json-decode');wire('holders','holdersText','out','holders','in');node('holder','current-holder');wire('holderState','holders','out','holder','holders');wire('holderEvent','mention','out','holder','events');
 node('pick','collection',{mode:'lookup',fieldPath:['holderId'],value:mara});wire('pick','holder','events','pick','in');node('single','select-fields',{fields:['schemaVersion','recordType','eventId','eventType','sceneId','source','actorId','itemId','position','evidence','semantics','status','acceptance','confirmation','holderId'].map(name=>({name,path:['value',name]}))});wire('single','pick','out','single','in');
 node('memory','prompted-memory',{actorId:mara,phase:'post',prompt:'When Sword is mentioned, recall the holder’s existing memory.'});wire('memoryEvent','single','out','memory','event');wire('memoryPresence','mara','out','memory','presence');node('memoryRead','read-file',{targetId:'triggered.json',phase:'post'});node('memoryWrite','write-file',{mode:'add'});wire('memoryReference','memoryRead','reference','memoryWrite','reference');wire('memoryRecord','memory','out','memoryWrite','records');assert.equal(f.catalog.define({targetId:'triggered.json',name:'Triggered memories',format:'json',content:'[]',visibility:{kind:'actor-private',actorId:mara}}).ok,true);
}
test('actual native Prompted Memory triggers on the ordered current holder and reads only authorized existing memories',async()=>{
 const f=fixture('direction',{replyText:'Mara and Elias kiss beside Sword.',modelOutput:material=>material.mode==='recall'?{kind:'recalled',memoryId:'mara-e1',reflection:'Mara recalls the sea.'}:undefined});addMemoryFlow(f);
 const {makeRecord}=await import('../src/workflow/introspection/contracts.js?v=0.27.0');const records={};for(const [actorId,id,text]of [[mara,'mara-e1','PRIVATE SEA episode'],[elias,'elias-e1','PRIVATE FIRE episode']]){const result=makeRecord('actor-state',{scope:{chatId:'Story-2',actorId},store:{id:'native-chat',version:0}},{episodes:[{id,text,classification:'observation',sourceRefs:[]}]},[]);assert.equal(result.ok,true);records[actorId]={state:result.data,receipts:[]};}f.c.chatMetadata.latticeIntrospection={'native-chat':records};
 const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,0);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.requests.length,2);const memory=JSON.parse(f.requests[1].messages.at(-1).content);assert.equal(memory.event.holderId,mara);assert.equal(memory.memories[0].memoryId,'mara-e1');assert.ok(JSON.stringify(memory).includes('PRIVATE SEA'));assert.equal(JSON.stringify(memory).includes('PRIVATE FIRE'),false);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.deepEqual(f.c.chatMetadata.latticeIntrospection['native-chat'],records);f.controller.dispose();
});

test('actual host verifies actor presence after all private Data admission callbacks before transport',async()=>{
 const hostURL=new URL('../src/workflow/host.js?actor-data-admission-race',import.meta.url).href,recallURL=new URL('../src/workflow/native-recall.js',import.meta.url).href;
 const state={current:true,armed:false,revoked:false};globalThis.latticeActorDataAdmissionRace=state;
 // Keep the real Recall producer and source checks; this adapter can only revoke an otherwise genuine presence.
 const adapter='data:text/javascript,'+encodeURIComponent(`import {createNativeRecallController as real} from ${JSON.stringify(recallURL)};export const createNativeRecallController=ports=>{const service=real(ports);return Object.freeze({...service,authorizePresence(...args){return globalThis.latticeActorDataAdmissionRace.current?service.authorizePresence(...args):{ok:false,error:{code:'RECALL_PRESENCE_UNVERIFIED',message:'Presence authority revoked during Data admission.'}};}});};`);
 const hook=registerHooks({resolve(specifier,context,next){return context.parentURL===hostURL&&specifier.startsWith('./native-recall.js')?{url:adapter,shortCircuit:true}:next(specifier,context);}});
 let f;
 try{
  const {createNativeWorkflowController:controllerFactory}=await import(hostURL);
  f=fixture('direction',{controllerFactory,onEvent(event){if(event.type==='request-start'&&event.address.nodeId==='direction')state.armed=true;},onContext(){const priorLimit=Error.stackTraceLimit;Error.stackTraceLimit=40;const stack=new Error().stack;Error.stackTraceLimit=priorLimit;if(state.armed&&!state.revoked&&stack.includes('native-actor-context.js')&&stack.includes('authorizeModelInputs')&&stack.includes('authorizeModelScope')&&!stack.includes('authorizeEventInputs')){state.current=false;state.revoked=true;}}});
  f.graph.nodes.privateData={id:'privateData',type:'workflow',...operationDefaults('read-file'),targetId:'mara.md'};
  f.graph.wires.privateData={id:'privateData',route:'wire',from:'privateData',fromPort:'document',to:'direction',toPort:'data'};
  const result=await f.start();assert.equal(state.revoked,true,'The private Data authorization callback must revoke genuine presence');assert.equal(result.ok,false);assert.equal(result.error.code,'ACTOR_CONTEXT_CHANGED');assert.equal(f.requests.length,1,'Only the public cast request may reach the adapter');assert.equal(f.requests.some(request=>JSON.stringify(request.messages).includes('PRIVATE SEA')),false);assert.equal(Object.values(f.c.extensionPrompts).some(prompt=>prompt.value),false);
 }finally{f?.controller.dispose();hook.deregister();delete globalThis.latticeActorDataAdmissionRace;}
});
