import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createRecallState} from '../src/workflow/recall-state.js';
import {createNativeRecallController} from '../src/workflow/native-recall.js';
import {operationDefaults} from '../src/workflow/catalog.js';
const scope={userId:'u',chatId:'chat',workflowId:'story',actorId:'mara'};
const proposal=(memorySetId='moments',extra={})=>({schemaVersion:1,type:'recall-arm-proposal',actorId:'mara',memorySetId,target:'both',uses:'next-match',consumeOn:'accepted',hotkey:{code:'KeyM',ctrl:true,alt:false,shift:true,meta:false},...extra});
function stateFixture(){let reads=0,generation={generationId:'g1',kind:'reply',stage:'pre',newlyGenerated:true};const state=createRecallState({getAuthority:()=>{reads++;return {scope,generation};}}).data;return {state,reads:()=>reads,setGeneration:value=>generation=value};}
function nativeFixture(){let owner={},enabled=true,activeScope=scope;const nodes={send:{id:'send',type:'workflow',...operationDefaults('on-send')},generate:{id:'generate',type:'workflow',...operationDefaults('generate-reply')},review:{id:'review',type:'workflow',...operationDefaults('review-publish')},a:{id:'a',type:'workflow',...operationDefaults('hotkey-arm'),actorId:'mara',memorySetId:'moments'},b:{id:'b',type:'workflow',...operationDefaults('hotkey-arm'),actorId:'mara',memorySetId:'moments',hotkey:{code:'KeyS',ctrl:true,alt:false,shift:true,meta:false}}};const graph={id:'story',name:'Story',schema:3,runtime:2,mode:'native-unified',nodes,wires:{activation:{id:'activation',route:'wire',from:'send',fromPort:'activation',to:'generate',toPort:'activation'},draft:{id:'draft',route:'wire',from:'generate',fromPort:'draft',to:'review',toPort:'draft'}},portals:{},definitions:{}};const listeners=[];const controller=createNativeRecallController({getActive:()=>enabled?{owner,scope:activeScope,graph,signature:'v1'}:null,registerHotkey:entry=>{listeners.push(entry);return {ok:true,data:{dispose(){entry.closed=true;}}};}});return {controller,graph,listeners,setOwner(){owner={};controller.resetDocument(owner);},setEnabled:value=>enabled=value,setScope:value=>activeScope=value};}
test('state supplies bounded batch queue mutation',()=>{const {state}=stateFixture();assert.equal(typeof state.changeQueues,'function');assert.equal(typeof state.queue,'function');assert.equal(typeof state.cancel,'function');});
test('repeated queue and different keys preserve the exact pending claim',()=>{const {state}=stateFixture();assert.equal(state.queue(proposal()).ok,true);const activation=state.activate({actorId:'mara',memorySetId:'moments',target:'both'});const before=state.inspect().data.requests;assert.equal(state.queue(proposal('moments',{hotkey:{code:'KeyS',ctrl:true,alt:false,shift:true,meta:false}})).ok,true);assert.deepEqual(state.inspect().data.requests,before);assert.equal(state.checkClaim(activation.data.claim).ok,true);assert.equal(state.inspect().data.requests.length,1);});
test('conflicting batch leaves every set unchanged and reads coherent authority once',()=>{const f=stateFixture();f.state.queue(proposal());const before=f.state.inspect().data.requests,reads=f.reads();const changed=f.state.changeQueues({action:'queue',proposals:[proposal('another'),proposal('moments',{target:'swipe'})]});assert.equal(changed.ok,false);assert.equal(f.reads(),reads+1);assert.deepEqual(f.state.inspect().data.requests,before);});
test('capacity overflow changes nothing',()=>{const {state}=stateFixture();assert.equal(state.changeQueues({action:'queue',proposals:Array.from({length:63},(_,i)=>proposal('set-'+i))}).ok,true);const before=state.inspect().data.requests;assert.equal(state.changeQueues({action:'queue',proposals:[proposal('new-a'),proposal('new-b')]}).ok,false);assert.deepEqual(state.inspect().data.requests,before);});
test('cancel batch deduplicates sets and is idempotent',()=>{const {state}=stateFixture();state.queue(proposal());const changed=state.changeQueues({action:'cancel',memorySetIds:['moments','moments']});assert.equal(changed.ok,true);assert.deepEqual(changed.data.changedMemorySetIds,['moments']);assert.equal(state.inspect().data.requests[0].queued,false);assert.deepEqual(state.changeQueues({action:'cancel',memorySetIds:['moments']}).data.changedMemorySetIds,[]);});
test('request status distinguishes generation and awaiting acceptance',()=>{const {state}=stateFixture();state.queue(proposal());const claim=state.activate({actorId:'mara',memorySetId:'moments',target:'both'}).data.claim;assert.equal(state.inspect().data.requests[0].pendingState,'generation');state.settle(claim,{status:'succeeded'});assert.equal(state.inspect().data.requests[0].pendingState,'acceptance');state.settle(claim,{status:'accepted'});assert.equal(state.inspect().data.requests[0].queued,false);assert.equal(state.inspect().data.requests[0].pendingState,null);});
test('native request is shared by compatible shortcuts with different physical keys',()=>{const f=nativeFixture();assert.equal(f.controller.queue('a').ok,true);assert.equal(f.controller.queue('b').ok,true);const status=f.controller.status().data;assert.equal(status.requests.filter(r=>r.queued).length,1);assert.equal(status.shortcuts.length,2);});
test('identical document replacement revokes queues, listeners and old command capture',()=>{const f=nativeFixture();f.controller.queue('a');const capture=f.controller.captureQueueCommand();assert.equal(capture.ok,true);f.setOwner();assert.equal(f.controller.status().data.requests.some(r=>r.queued),false);assert.equal(f.listeners.slice(0,2).every(r=>r.closed),true);assert.equal(f.controller.changeQueues(capture.data,{action:'queue',shortcutNodeIds:['a']}).ok,false);assert.equal(f.controller.status().data.requests.some(r=>r.queued),false);});
test('native batch rejects incompatible policy without partially queueing',()=>{const f=nativeFixture();f.graph.nodes.b.target='swipe';f.graph.nodes.c={...f.graph.nodes.a,id:'c',memorySetId:'separate',hotkey:{code:'KeyT',ctrl:true,alt:false,shift:true,meta:false}};const capture=f.controller.captureQueueCommand();assert.equal(capture.ok,true);assert.equal(f.controller.changeQueues(capture.data,{action:'queue',shortcutNodeIds:['c','a','b']}).ok,false);assert.equal(f.controller.status().data.requests.some(r=>r.queued),false);});
test('disabled unchanged scope preserves queue but replacement while disabled revokes it',()=>{const f=nativeFixture();f.controller.queue('a');f.setEnabled(false);assert.equal(f.controller.queue('a').ok,false);assert.equal(f.controller.status().data.scope,null);f.setEnabled(true);assert.equal(f.controller.status().data.requests[0].queued,true);f.setEnabled(false);f.setOwner();f.setEnabled(true);assert.equal(f.controller.status().data.requests.some(r=>r.queued),false);});
test('native status notification fires only for display transitions',()=>{const f=nativeFixture();f.controller.sync();let events=0;const dispose=f.controller.subscribe(()=>events++);f.controller.queue('a');const queuedEvents=events;assert.ok(queuedEvents>0);f.controller.status();f.controller.sync();f.controller.queue('b');assert.equal(events,queuedEvents);f.controller.cancel('a');assert.ok(events>queuedEvents);dispose();const old=events;f.controller.queue('a');assert.equal(events,old);});

test('requeue after consumption or cancellation publishes one current shared request',()=>{const f=nativeFixture();f.controller.queue('a');f.controller.cancel('a');assert.equal(f.controller.queue('b').ok,true);const status=f.controller.status().data;assert.equal(status.requests.length,1);assert.equal(status.shortcuts.every(item=>item.queued),true);});

test('trusted inactive-scope cleanup only revokes an exact claim and preserves remaining use',()=>{let active=true;const state=createRecallState({getAuthority:()=>({scope:active?scope:{...scope,chatId:'away'},generation:{generationId:'one',kind:'reply',stage:'pre',newlyGenerated:true}})}).data;state.queue(proposal());const claim=state.activate({actorId:'mara',memorySetId:'moments',target:'both'}).data.claim;active=false;assert.equal(state.releaseClaim({...claim}).ok,false);assert.equal(state.releaseClaim(claim).ok,true);active=true;const request=state.inspect().data.requests[0];assert.equal(request.queued,true);assert.equal(request.pendingGenerationCount,0);assert.equal(request.remaining.reply,true);assert.equal(state.checkClaim(claim).ok,false);});
