import assert from 'node:assert/strict';
import {test} from 'node:test';
import {UNIFIED_WORKFLOW_EXAMPLE_DATA as entries} from '../src/workflow/unified-example-data.js';
import {buildScopedStoryExamples} from '../tools/scoped-story-examples.mjs';
import {createNativeWorkflowController} from '../src/workflow/host.js?v=0.27.0';
import {createChatDocumentCatalog} from '../src/workflow/document-catalog.js?v=0.27.0';
import {operationDefaults} from '../src/workflow/catalog.js?v=0.27.0';
import {validateWorkflow} from '../src/workflow/contracts.js?v=0.27.0';
import {makeRecord} from '../src/workflow/introspection/contracts.js?v=0.27.0';
const mara='character:mara.png',elias='character:elias.png';
const ids=['character-specific-prompt','item-triggered-memory','paired-kiss-memories','recall-memories'];
const response=value=>({ok:true,data:{text:typeof value==='string'?value:JSON.stringify(value),finish:'stop'}});
const pause=()=>new Promise(resolve=>setTimeout(resolve,5));
function recipe(id){const entry=entries.find(e=>e.id==='unified-'+id);assert.ok(entry,'Generator must integrate buildScopedStoryExamples for '+id);return structuredClone(entry.packages[0].graph);}
function fixture(id,options={}) {
 const graph=recipe(id);if(options.configureFast!==false&&graph.nodes['kiss-decision'])graph.nodes['kiss-decision'].fastConnectionId='chosen-in-host-ui';
 // The test author explicitly permits invented feelings; portable examples remain opt-in.
 if(graph.nodes['reflection-authorship-text']&&options.allowModelAuthoredFeelings!==false)graph.nodes['reflection-authorship-text'].text=JSON.stringify({allowModelAuthoredFeelings:true});
 if(options.activation){graph.nodes.recall.activation=options.activation;if(!options.activation.includes('keyword'))for(const [wireId,wire]of Object.entries(graph.wires))if(wire.to==='recall'&&wire.toPort==='source')delete graph.wires[wireId];}
 const listeners=new Map(),results=[],requests=[],typed=[],registrations=[];let busy=false,saves=0;
 const c={chatId:'Story-2',characterId:options.selectedActor===elias?1:0,groupId:null,characters:[{avatar:'mara.png',data:{name:'Mara',description:'MARA PRIVATE SEA',visibility:{kind:'actor-private',actorId:mara}}},{avatar:'elias.png',data:{name:'Elias',description:'ELIAS PRIVATE FIRE',visibility:{kind:'actor-private',actorId:elias}}}],chat:[{mes:options.playerText??'Mara and Elias meet beside the door.',is_user:true,extra:{}}],chatMetadata:{},extensionPrompts:{},eventTypes:Object.fromEntries(['GENERATION_STARTED','GENERATION_STOPPED','GENERATION_ENDED','MESSAGE_RECEIVED','MESSAGE_SENT','CHAT_CHANGED','MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED','MESSAGE_SWIPED','MESSAGE_SWIPE_DELETED'].map(name=>[name,name]))};
 c.eventSource={on(name,fn){const bucket=listeners.get(name)??[];bucket.push(fn);listeners.set(name,bucket);},removeListener(name,fn){listeners.set(name,(listeners.get(name)??[]).filter(value=>value!==fn));},async emit(name,...args){for(const fn of listeners.get(name)??[])await fn(...args);}};
 c.setExtensionPrompt=(key,value)=>{c.extensionPrompts[key]={value};};c.saveChat=async()=>{};c.saveMetadata=async()=>true;c.updateMessageBlock=async()=>{};c.swipe={refresh:async()=>{}};
 const catalog=createChatDocumentCatalog({getContext:()=>c,getUserId:()=> 'default-user'});
 for(const [key,actorId]of [['mara',mara],['elias',elias]])for(const suffix of ['item-memories','moments']){
  const content=suffix==='moments'?[{id:key+'-earlier',actorId,text:key==='mara'?'MARA PRIVATE SEA accepted memory':'ELIAS PRIVATE FIRE accepted memory',tags:['harbor']}]:[];
  assert.equal(catalog.define({targetId:key+'-'+suffix,name:key+' '+suffix,format:'json',content:JSON.stringify(content),visibility:{kind:'actor-private',actorId}}).ok,true);
  const stored=makeRecord('actor-state',{scope:{chatId:'Story-2',actorId},store:{id:'native-chat',version:0}},{episodes:[{id:key+'-episode',text:key==='mara'?'MARA PRIVATE SEA authorized episode':'ELIAS PRIVATE FIRE authorized episode',classification:'observation',sourceRefs:[]}]},[]);assert.equal(stored.ok,true);
  c.chatMetadata.latticeIntrospection??={'native-chat':{}};c.chatMetadata.latticeIntrospection['native-chat'][actorId]={state:stored.data,receipts:[]};
 }
 const binding={profileId:'scoped-example-text',model:'text-test'},fastBinding={connectionId:'chosen-in-host-ui',model:'jev-test',provider:'jev'};
 const controller=createNativeWorkflowController({context:()=>c,getGraph:phase=>phase==='unified'?graph:undefined,isEnabled:()=>true,userId:()=> 'default-user',isBusy:()=>busy,documentCatalog:catalog,countTokens:async()=>({tokens:1}),resolveBinding:()=>({ok:true,data:binding}),bindingStatus:()=>({ok:true}),resolveFastBinding:node=>node.fastConnectionId?{ok:true,data:fastBinding}:{ok:false,error:{code:'CONNECTION_MISSING',message:'Select a host connection.'}},fastBindingSummary:()=>({model:fastBinding.model,profileId:null}),requestFastDecision:async request=>{typed.push(request);return {ok:true,data:{model:fastBinding.model,answers:{kiss:{type:'noul',noul:options.probability??0.97}},usage:{input_tokens:8,output_tokens:1}}};},
 request:async request=>{
  requests.push(request);const material=JSON.parse(request.messages.at(-1).content),prompt=material.request??'';const overridden=await options.modelOutput?.(material,request,c);if(overridden!==undefined)return response(overridden);
  if(prompt.startsWith('SCOPED CAST:')){const source=material.context?.source??material.data,quote=source.text??c.chat[0].mes;return response({sceneId:source.sceneId,sourceId:source.sourceId,revision:source.revision,actors:[{actorId:mara,status:options.maraPresence??'present',evidence:quote},{actorId:elias,status:options.eliasPresence??'present',evidence:quote}]});}
  if(prompt.startsWith('SCOPED KISS:')){const source=material.data;return response([{eventType:'scene-action',actorId:mara,objectId:elias,position:{start:0,end:source.text.length},semantics:'actual'}]);}
  if(prompt.startsWith('SCOPED REFLECTION:')){const actorId=material.context.source.actorId;return response({reflection:actorId===mara?'Mara privately recalls the sea beside the kiss.':'Elias privately recalls the fire beside the kiss.'});}
  if(material.event&&material.mode){return response({kind:'recalled',memoryId:material.event.holderId===mara?'mara-episode':'elias-episode',reflection:'Only the holder reflects on the moonstone pendant.'});}
  if(material.scope?.actorId===mara)return response('Mara alone hesitates before the sea.');throw Error('Unexpected scoped example request '+request.messages[0].content);
 },registerRecallHotkey(proposal){const entry={proposal};registrations.push(entry);return {ok:true,data:{dispose:()=>{entry.released=true;}}};},persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}},onResult:result=>results.push(result),syncMesToSwipe(index){const m=c.chat[index];m.swipes[m.swipe_id]=m.mes;return true;},syncSwipeToMes(index,swipeId){const m=c.chat[index];m.swipe_id=swipeId;m.mes=m.swipes[swipeId];Object.assign(m,structuredClone(m.swipe_info[swipeId]));return true;}});controller.subscribe();
 return {graph,c,catalog,controller,requests,typed,registrations,results,saves:()=>saves,async begin(type='normal'){busy=true;await c.eventSource.emit('GENERATION_STARTED',type,{},false);return controller.beforeGenerate(c.chat.map(message=>({...message})),8192,()=>{},type);},async finish(text,type='normal'){const now=new Date().toISOString();if(type==='swipe'){const m=c.chat.at(-1),index=m.swipes.length;m.swipe_id=index;m.mes=text;m.swipes.push(text);m.swipe_info.push({gen_started:now,gen_finished:now,extra:{}});m.gen_started=now;m.gen_finished=now;}else c.chat.push({mes:text,is_user:false,extra:{},gen_started:now,gen_finished:now,swipe_id:0,swipes:[text],swipe_info:[{gen_started:now,gen_finished:now,extra:{}}]});await c.eventSource.emit('MESSAGE_RECEIVED',c.chat.length-1,type);busy=false;await c.eventSource.emit('GENERATION_ENDED',c.chat.length-1);for(let i=0;i<400&&!results.length;i++)await pause();assert.ok(results.length,'Owned native continuation must complete');return results.at(-1);},async generate(text){const prepared=await this.begin();return prepared.ok?this.finish(text):prepared;}};
}
const prompt=f=>Object.values(f.c.extensionPrompts).map(entry=>entry.value).join('\n');
const saved=(f,targetId)=>JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'][targetId].content);

test('four scoped examples are real portable unified graphs with explicit setup and unassigned connections',()=>{
 assert.equal(typeof buildScopedStoryExamples,'function');for(const id of ids){const graph=recipe(id);assert.equal(validateWorkflow(graph).ok,true,id);assert.equal(graph.mode,'native-unified');assert.equal(Object.values(graph.nodes).filter(n=>n.operation==='generate-reply').length,1);assert.match(graph.description,/Setup:/);assert.match(graph.description,/character:mara\.png/);for(const role of Object.values(graph.roles))assert.deepEqual(role,{model:null,profileId:null});assert.equal(Object.values(graph.nodes).some(n=>n.operation==='text'&&n.text.includes('recordType":"scene-presence')),false);}
 const kiss=recipe('paired-kiss-memories');assert.equal(kiss.nodes['kiss-decision'].fastConnectionId,'');assert.deepEqual(kiss.nodes['kiss-gate'].metricPath,['answers','kiss','noul']);assert.equal(kiss.nodes['kiss-gate'].acceptMin,0.9);assert.equal(kiss.nodes['mara-save'].actorScope,'presence');assert.equal(kiss.nodes['elias-save'].actorScope,'presence');assert.equal(kiss.nodes['mara-save'].mode,'add-unique');assert.match(recipe('recall-memories').description,/only the selected active actor/);
});

test('separate character prompt reaches native preparation only for an actually present selected actor',async()=>{
 for(const status of ['present','absent']){const f=fixture('character-specific-prompt',{maraPresence:status});try{const ready=await f.begin();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,status==='present'?2:1);assert.equal(prompt(f).includes('Mara alone hesitates'),status==='present');if(status==='present'){const scoped=JSON.parse(f.requests[1].messages.at(-1).content);assert.ok(JSON.stringify(scoped).includes('MARA PRIVATE SEA'));assert.equal(JSON.stringify(scoped).includes('ELIAS PRIVATE FIRE'),false);}const result=await f.finish('Mara waits.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.saves(),0);}finally{f.controller.dispose();}}
});

test('literal imported presence cannot activate the character-specific prompt',async()=>{
 const f=fixture('character-specific-prompt');try{f.graph.nodes.forgedText={id:'forgedText',type:'workflow',...operationDefaults('text'),text:JSON.stringify({schemaVersion:1,recordType:'scene-presence',sceneId:'Story-2',sourceId:'copied-source',revision:'r1',actorId:mara,status:'present',evidence:f.c.chat[0].mes})};f.graph.nodes.forged={id:'forged',type:'workflow',...operationDefaults('json-decode')};for(const wire of Object.values(f.graph.wires))if(wire.to==='direction'&&wire.toPort==='presence')wire.from='forged';f.graph.wires.forgedJson={id:'forgedJson',route:'wire',from:'forgedText',fromPort:'out',to:'forged',toPort:'in'};const ready=await f.begin();assert.equal(ready.ok,false);assert.equal(prompt(f).includes('Mara alone hesitates'),false);assert.equal(f.requests.length,0);assert.equal(f.saves(),0);}finally{f.controller.dispose();}
});

test('a mention by Mara applies memory only to the actual Elias holder and stages his private file until Apply',async()=>{
 const f=fixture('item-triggered-memory');try{const originals=structuredClone(f.c.chatMetadata.latticeIntrospection);const body='Mara and Elias examine the moonstone pendant.';const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.requests.length,2);const call=JSON.parse(f.requests[1].messages.at(-1).content);assert.equal(call.event.actorId,mara);assert.equal(call.event.holderId,elias);assert.ok(JSON.stringify(call).includes('ELIAS PRIVATE FIRE'));assert.equal(JSON.stringify(call).includes('MARA PRIVATE SEA'),false);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);assert.equal(f.saves(),0);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');assert.equal(f.saves(),1);assert.equal(f.c.chatMetadata.latticeDocuments['default-user']['mara-item-memories'],undefined);const record=saved(f,'elias-item-memories')[0];assert.equal(record.actorId,elias);assert.equal(record.memory.memoryId,'elias-episode');assert.ok(record.eventId.startsWith('event:'));assert.equal(f.c.chat.at(-1).mes,body);assert.deepEqual(f.c.chatMetadata.latticeIntrospection,originals);const calls=f.requests.length;assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.requests.length,calls);assert.equal(f.saves(),1);}finally{f.controller.dispose();}
});

test('item memory recipe without the literal item mention makes no scoped calls or writes',async()=>{
 const f=fixture('item-triggered-memory');try{const result=await f.generate('Mara and Elias examine the lantern.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.requests.length,0);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});

test('paired kiss uses one chosen Fast connection and separate own-context reflections with canonical unique file evidence',async()=>{
 const f=fixture('paired-kiss-memories');try{const body='Mara and Elias kiss beside the door.';const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.typed.length,1);assert.equal(f.requests.length,4);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);for(const request of f.requests.filter(r=>JSON.parse(r.messages.at(-1).content).request?.startsWith('SCOPED REFLECTION:'))){const material=JSON.parse(request.messages.at(-1).content),text=JSON.stringify(material);assert.equal(text.includes('MARA PRIVATE SEA')&&text.includes('ELIAS PRIVATE FIRE'),false);assert.ok(text.includes(material.context.source.actorId===mara?'MARA PRIVATE SEA':'ELIAS PRIVATE FIRE'));}
 const event=f.typed[0].state[0];assert.equal(event.status,'candidate');assert.equal(event.evidence.text,body);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');assert.equal(f.saves(),2);for(const [key,actorId]of [['mara',mara],['elias',elias]]){const records=saved(f,key+'-moments');assert.equal(records.length,2);assert.equal(records[1].id,event.eventId);assert.equal(records[1].eventId,event.eventId);assert.equal(records[1].actorId,actorId);const reflection=actorId===mara?'Mara privately recalls the sea beside the kiss.':'Elias privately recalls the fire beside the kiss.';assert.equal(records[1].text,reflection);assert.equal(records[1].reflection,reflection);assert.equal(records[1].reflectionOrigin,'model-authored');assert.equal(records[1].sceneSummary,body);assert.deepEqual(records[1].sceneEvidence,{origin:'draft',sourceId:event.source.sourceId,revision:event.source.revision,position:{start:0,end:body.length},text:body});assert.deepEqual(records[1].sourceRefs,[{id:event.source.sourceId,revision:event.source.revision}]);}assert.equal(f.c.chat.at(-1).mes,body);assert.equal(f.c.chat.at(-1).swipes[0],body);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),2);assert.equal(f.requests.length,4);}finally{f.controller.dispose();}
});

for(const probability of [0.05,0.55])test('paired kiss confidence '+probability+' cannot run private reflection or stage memory',async()=>{
 const f=fixture('paired-kiss-memories',{probability});try{const result=await f.generate('Mara and Elias discuss a possible kiss.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,1);assert.equal(f.typed.length,1);assert.equal(f.requests.length,1);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);assert.equal(f.requests.some(r=>r.messages.at(-1).content.includes('PRIVATE SEA')||r.messages.at(-1).content.includes('PRIVATE FIRE')),false);}finally{f.controller.dispose();}
});

test('portable Fast recipe holds until a real host connection is explicitly selected',async()=>{
 const f=fixture('paired-kiss-memories',{configureFast:false});try{const result=await f.generate('Mara and Elias kiss beside the door.');assert.equal(result.ok,false);assert.equal(f.typed.length,0);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});

test('Recall hotkey/manual arming spends only accepted matching reply and swipe uses',async()=>{
 const f=fixture('recall-memories');try{assert.equal(f.controller.syncRecall().ok,true);assert.equal(f.registrations.length,1);assert.deepEqual(f.registrations[0].proposal.hotkey,{code:'KeyR',ctrl:true,alt:false,shift:false,meta:false});assert.equal(f.registrations[0].proposal.onPress().ok,true);assert.equal((await f.begin()).ok,true);assert.ok(prompt(f).includes('MARA PRIVATE SEA accepted memory'));const reply=await f.finish('Mara and Elias continue.');assert.equal(reply.ok,true,JSON.stringify(reply.error));assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);assert.equal((await f.controller.apply(reply.reviewHandles[0])).ok,true);assert.deepEqual(f.controller.statusRecall().data.shortcuts[0].remaining,{reply:false,swipe:true});const prior=[...f.c.chat.at(-1).swipes];f.results.length=0;f.c.chat.at(-1).swipe_id=f.c.chat.at(-1).swipes.length;assert.equal((await f.begin('swipe')).ok,true);const swipe=await f.finish('Mara and Elias take another route.','swipe');assert.equal(swipe.ok,true,JSON.stringify(swipe.error));assert.equal((await f.controller.apply(swipe.reviewHandles[0])).ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.deepEqual(f.c.chat.at(-1).swipes.slice(0,prior.length),prior);assert.equal(f.c.chat.at(-1).mes.includes('PRIVATE SEA'),false);assert.equal(f.controller.queueRecall('hotkey').ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);}finally{f.controller.dispose();}
});

for(const activation of ['armed-or-keyword','armed-or-character'])test('Recall '+activation+' uses live native source and private records without an arm',async()=>{
 const f=fixture('recall-memories',{activation,playerText:'Mara and Elias return to the harbor.'});try{assert.equal(f.controller.syncRecall().ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.equal((await f.begin()).ok,true);assert.ok(prompt(f).includes('MARA PRIVATE SEA accepted memory'));assert.equal(prompt(f).includes('ELIAS PRIVATE FIRE'),false);const result=await f.finish('Mara remembers the harbor promise.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.requests.length,1);}finally{f.controller.dispose();}
});

test('unarmed unmatched Recall and a changed selected actor cannot disclose private records',async()=>{
 const f=fixture('recall-memories');try{assert.equal((await f.begin()).ok,true);assert.equal(prompt(f).includes('PRIVATE SEA'),false);const result=await f.finish('Mara waits.');assert.equal(result.ok,true,JSON.stringify(result.error));}finally{f.controller.dispose();}
 const other=fixture('recall-memories',{selectedActor:elias,playerText:'Mara and Elias return to the harbor.'});try{const held=await other.begin();assert.equal(held.ok,false);assert.equal(prompt(other).includes('PRIVATE SEA'),false);assert.equal(other.saves(),0);}finally{other.controller.dispose();}
});


test('a normal no-kiss reply skips Fast and both memory legs while preserving native review',async()=>{
 const f=fixture('paired-kiss-memories',{modelOutput:material=>material.request?.startsWith('SCOPED KISS:')?[]:undefined});try{const result=await f.generate('Mara and Elias discuss the harbor.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,1);assert.equal(f.requests.length,1);assert.equal(f.typed.length,0);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});

test('an absent current holder skips its private memory and file branch',async()=>{
 const f=fixture('item-triggered-memory',{eliasPresence:'absent'});try{const result=await f.generate('Mara mentions the moonstone pendant.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,1);assert.equal(f.requests.length,1);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});

for(const missing of ['maraPresence','eliasPresence'])test('paired kiss skips both private reflections when '+missing+' is absent',async()=>{
 const f=fixture('paired-kiss-memories',{[missing]:'absent'});try{const result=await f.generate('Mara and Elias kiss beside the door.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,1);assert.equal(f.typed.length,1);assert.equal(f.requests.length,2);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});

test('paired kiss requires explicit author permission before inventing either actor’s feelings',async()=>{
 const f=fixture('paired-kiss-memories',{allowModelAuthoredFeelings:false});try{const result=await f.generate('Mara and Elias kiss beside the door.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,1);assert.equal(f.typed.length,1);assert.equal(f.requests.length,2);assert.equal(f.requests.some(r=>JSON.parse(r.messages.at(-1).content).request?.startsWith('SCOPED REFLECTION:')),false);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});
