import assert from 'node:assert/strict';
import {compactContext} from '../src/workflow/compactor.js';
const countTokens=async text=>({tokens:text.length,method:'characters-fixture'});
const smallContext={kind:'context',messages:[{id:'a',role:'user',text:'Hello',source:{index:0}},{id:'b',role:'assistant',text:'Hi',source:{index:1}}]};
const result=await compactContext(smallContext,{targetTokens:1200,keepRecent:2,method:'compress'},{countTokens});
assert.equal(result.ok,true);
assert.deepEqual(result.artifact.messages,smallContext.messages);
assert.equal(result.calls.length,0);
const history={kind:'context',messages:[
    {id:'a',role:'system',text:'A'.repeat(30),source:'original'},
    {id:'b',role:'user',text:'B'.repeat(30),source:'original'},
    {id:'c',role:'assistant',text:'C'.repeat(30),source:'original'},
    {id:'d',role:'user',text:'D'.repeat(30),source:'original'},
]};
const selected=await compactContext(history,{targetTokens:90,keepRecent:1},{countTokens});
assert.deepEqual(selected.artifact.messages,history.messages.slice(2));
assert.deepEqual(selected.artifact.original,history.messages);
assert.equal(selected.calls.length,0);
assert.equal(selected.reports.at(-1).method,'characters-fixture');
assert.equal(selected.reports.at(-1).tokens,85);
const pinned=await compactContext(history,{targetTokens:85,keepRecent:1,pins:['AAA']},{countTokens});
assert.deepEqual(pinned.artifact.messages,[history.messages[0],history.messages[3]]);
assert.equal((await compactContext(history,{targetTokens:30,keepRecent:1,pins:['AAA']},{countTokens})).error?.code,'PIN_BUDGET_EXCEEDED');
assert.equal((await compactContext(history,{targetTokens:1200,pins:['deleted']},{countTokens})).error?.code,'PIN_MISSING');
let compressionCalls=0;
const compressionPorts={countTokens,binding:{profileId:'analysis',model:'compact-model'},request:async request=>{compressionCalls++;return {ok:true,data:{text:request.messages[1].content.includes('D'.repeat(30)) ? 'WRONG RECENT MATERIAL' : 'Short summary',usage:{completion_tokens:3},finish:'stop'}};}};
const compressed=await compactContext(history,{id:'compact',targetTokens:140,keepRecent:1,pins:['AAA'],method:'compress'},compressionPorts);
assert.equal(compressed.ok,true);
assert.equal(compressionCalls,1);
assert.deepEqual(compressed.artifact.messages.filter(m=>m.id==='a' || m.id==='d'),[history.messages[0],history.messages[3]]);
assert.equal(compressed.artifact.messages.find(m=>m.source==='compactor')?.text,'Short summary');
assert.equal(compressed.calls[0].maxTokens,1024);
assert.equal(compressed.calls[0].modelRole,'Analysis');
assert.deepEqual(compressed.calls[0].binding,{profileId:'analysis',model:'compact-model'});
const overflow=await compactContext(history,{targetTokens:100,keepRecent:1,pins:['AAA'],method:'compress'},{...compressionPorts,request:async()=>({ok:true,data:{text:'Too long '.repeat(100),finish:'stop'}})});
assert.equal(overflow.error?.code,'COMPACTION_OVERFLOW');
assert.deepEqual(overflow.artifact.messages,history.messages);
assert.equal(overflow.calls.length,1);
const cutoff=await compactContext(history,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,request:async()=>({ok:true,data:{text:'short',finish:'length',usage:{completion_tokens:1024}}})});
assert.equal(cutoff.error?.code,'TRUNCATED_OUTPUT');
assert.deepEqual(cutoff.artifact.messages,history.messages);
assert.equal(cutoff.calls.length,1);
assert.equal(cutoff.error?.finish,'length');
assert.deepEqual(cutoff.error?.usage,{completion_tokens:1024});
const empty=await compactContext(history,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,request:async()=>({ok:true,data:{text:' ',finish:'stop'}})});
assert.equal(empty.error?.code,'EMPTY_OUTPUT');
const transport=await compactContext(history,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,request:async()=>{throw new Error('transport');}});
assert.equal(transport.error?.code,'REQUEST_FAILED');
assert.equal(transport.calls.length,1);
const stopped=new AbortController(); stopped.abort();
let stoppedCalls=0;
const aborted=await compactContext(history,{targetTokens:140,method:'compress'},{...compressionPorts,signal:stopped.signal,request:async()=>{stoppedCalls++;}});
assert.equal(aborted.error?.code,'ABORTED');
assert.equal(stoppedCalls,0);
const delayedStop=new AbortController();
const late=await compactContext(history,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,signal:delayedStop.signal,request:async()=>{delayedStop.abort();return {ok:true,data:{text:'late output',finish:'stop'}};}});
assert.equal(late.error?.code,'ABORTED');
assert.equal(late.calls.length,1);
const hugeHistory={kind:'context',messages:[{id:'old',role:'user',text:'X'.repeat(40000),source:'old'},{id:'middle',role:'assistant',text:'Compress this',source:'middle'},{id:'recent',role:'user',text:'Keep this',source:'recent'}]};
let boundedPayload='';
const bounded=await compactContext(hugeHistory,{targetTokens:200,keepRecent:1,method:'compress'},{...compressionPorts,request:async request=>{boundedPayload=request.messages[1].content;return {ok:true,data:{text:'Compact',finish:'stop'}};}});
assert.equal(bounded.ok,true);
assert.equal(boundedPayload.includes('X'),false);
assert.equal(boundedPayload.includes('Compress this'),true);
assert.deepEqual(bounded.reports.find(report=>report.code==='COMPRESSION_INPUT_OMITTED').messageIds,['old']);
assert.deepEqual(bounded.artifact.original,hugeHistory.messages);
const unmeasured=await compactContext(history,{},{countTokens:async()=>{throw new Error('tokenizer unavailable');}});
assert.equal(unmeasured.error?.code,'TOKEN_COUNT_FAILED');
assert.equal(unmeasured.calls.length,0);
assert.equal((await compactContext(history,{},{countTokens:async()=>({tokens:NaN,method:'bad'})})).error?.code,'TOKEN_COUNT_FAILED');
assert.equal((await compactContext(history,{targetTokens:0},{countTokens})).error?.code,'INVALID_SETTINGS');
assert.equal((await compactContext({kind:'context',messages:[{id:'bad',role:'user',text:12}]},{},{countTokens})).error?.code,'INVALID_CONTEXT');
assert.equal((await compactContext(history,{method:'compress',targetTokens:140},{countTokens})).error?.code,'BINDING_MISSING');
const changing=structuredClone(history);
const stable=await compactContext(changing,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,request:async()=>{changing.messages[3].text='mutated';return {ok:true,data:{text:'Summary',finish:'stop'}};}});
assert.deepEqual(stable.artifact.original,history.messages);
const measuringStop=new AbortController();
const measureAborted=await compactContext(smallContext,{},{countTokens:async text=>{measuringStop.abort();return countTokens(text);},signal:measuringStop.signal});
assert.equal(measureAborted.error?.code,'ABORTED');
const malformedResponse=await compactContext(history,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,request:async()=>undefined});
assert.equal(malformedResponse.error?.code,'REQUEST_FAILED');
assert.equal(malformedResponse.calls.length,1);
const colliding=structuredClone(history);colliding.messages[0].id='compact:summary';
const collision=await compactContext(colliding,{id:'compact',targetTokens:160,keepRecent:1,pins:['AAA'],method:'compress'},compressionPorts);
assert.equal(collision.ok,true);
assert.equal(new Set(collision.artifact.messages.map(message=>message.id)).size,collision.artifact.messages.length);
assert.equal(transport.trace.length,1);
assert.equal(transport.trace[0].error.code,'REQUEST_FAILED');

const literalPinned=await compactContext(history,{targetTokens:85,keepRecent:1,pins:['AAA']},{countTokens});
assert.equal(literalPinned.ok,true);
assert.deepEqual(literalPinned.artifact.messages,[history.messages[0],history.messages[3]]);
assert.equal((await compactContext(history,{pins:['a']},{countTokens})).error?.code,'PIN_MISSING');
assert.equal((await compactContext(history,{pins:['']},{countTokens})).error?.code,'INVALID_SETTINGS');
const unverifiedSummary=await compactContext(history,{targetTokens:140,keepRecent:1,method:'compress'},{...compressionPorts,request:async()=>({ok:true,data:{text:'Opaque summary',finish:null,usage:{completion_tokens:5}}})});
assert.equal(unverifiedSummary.error?.code,'COMPLETION_UNVERIFIED');
assert.deepEqual(unverifiedSummary.artifact.messages,history.messages);
assert.equal(unverifiedSummary.calls.length,1);
const selectionReport=selected.reports.find(report=>report.code==='CONTEXT_PRESERVATION');
assert.deepEqual(selectionReport?.retainedMessageIds,['c','d']);
assert.deepEqual(selectionReport?.removedMessageIds,['a','b']);
assert.deepEqual(selectionReport?.summarizedMessageIds,[]);
assert.deepEqual(selectionReport?.inputOmittedMessageIds,[]);
assert.equal(selectionReport?.originalRetained,true);
assert.deepEqual(selected.artifact.messages.map(message=>message.text),['C'.repeat(30),'D'.repeat(30)]);
const compressionReport=compressed.reports.find(report=>report.code==='CONTEXT_PRESERVATION');
assert.deepEqual(compressionReport?.retainedMessageIds,['a','d']);
assert.deepEqual(compressionReport?.removedMessageIds,['b','c']);
assert.deepEqual(compressionReport?.summarizedMessageIds,['b','c']);
assert.deepEqual(compressionReport?.inputOmittedMessageIds,[]);
assert.equal(compressionReport?.originalRetained,true);
assert.deepEqual(compressed.artifact.messages.map(message=>message.text),['A'.repeat(30),'Short summary','D'.repeat(30)]);
const boundedReport=bounded.reports.find(report=>report.code==='CONTEXT_PRESERVATION');
assert.deepEqual(boundedReport?.retainedMessageIds,['recent']);
assert.deepEqual(boundedReport?.removedMessageIds,['old','middle']);
assert.deepEqual(boundedReport?.summarizedMessageIds,['middle']);
assert.deepEqual(boundedReport?.inputOmittedMessageIds,['old']);
assert.equal(boundedReport?.originalRetained,true);
assert.deepEqual(bounded.artifact.messages.map(message=>message.text),['Compact','Keep this']);
const failedReport=overflow.reports.find(report=>report.code==='CONTEXT_PRESERVATION');
assert.deepEqual(failedReport?.retainedMessageIds,['a','b','c','d']);
assert.deepEqual(failedReport?.removedMessageIds,[]);
assert.deepEqual(failedReport?.summarizedMessageIds,[]);
assert.deepEqual(failedReport?.inputOmittedMessageIds,[]);
assert.equal(failedReport?.originalRetained,true);
assert.deepEqual(overflow.artifact.messages.map(message=>message.text),history.messages.map(message=>message.text));
console.log('compactor: ok');
