import assert from 'node:assert/strict';
import test from 'node:test';
import { installMock } from './mock.js';
import * as state from '../src/state.js?v=0.27.0';
import { starterGraph } from '../src/workflow/starters.js?v=0.27.0';
import { validateWorkflow } from '../src/workflow/contracts.js?v=0.27.0';
import { sendWorkflowState } from '../src/run.js?v=0.27.0';
test('new unified starter has explicit native boundary and a checked review terminal',()=>{const graph=starterGraph('unified-basic');assert.equal(graph.mode,'native-unified');assert.deepEqual(Object.values(graph.nodes).map(node=>node.operation),['on-send','generate-reply','review-publish']);const checked=validateWorkflow(graph);assert.equal(checked.ok,true,JSON.stringify(checked.error));assert.equal(checked.data.callBound,0);});
test('unified creation stays unassigned and deletion clears only its Send binding',()=>{installMock();const value=state.settings(),graph=state.createGraph('Story');assert.equal(graph.mode,'native-unified');assert.deepEqual(value.nativeBindings,{workflowGraphId:null});value.nativeBindings.workflowGraphId=graph.id;assert.equal(sendWorkflowState().automatic,true);assert.match(sendWorkflowState().armedText,/one workflow|unified/i);state.deleteGraph(graph.id);assert.deepEqual(value.nativeBindings,{workflowGraphId:null});});
test('saved unified binding is admitted and a retired root cannot be assigned to Send',()=>{const graph=starterGraph('unified-basic');installMock({settings:{graphs:{[graph.id]:graph},nativeBindings:{workflowGraphId:graph.id}}});assert.equal(state.settings().nativeBindings.workflowGraphId,graph.id);const invalid={id:'retired',schema:3,runtime:2,mode:'native-pre',nodes:{},wires:{}};installMock({settings:{graphs:{[invalid.id]:invalid},nativeBindings:{workflowGraphId:invalid.id}}});assert.throws(()=>state.settings(),/unified binding/i);});
