import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createNativeRecallController} from '../src/workflow/native-recall.js?v=0.27.0';
import {runWorkflowForHost,workflowSignature} from '../src/workflow/runtime.js?v=0.27.0';
import {operationDefaults} from '../src/workflow/catalog.js?v=0.27.0';
const node=(id,operation,settings={})=>({id,type:'workflow',...operationDefaults(operation),...settings});
const scope={userId:'u',chatId:'c',workflowId:'w',actorId:'a'};
function graph(){return {id:'w',schema:3,runtime:2,mode:'native-unified',nodes:{send:node('send','on-send'),generate:node('generate','generate-reply'),review:node('review','review-publish'),hotkey:node('hotkey','hotkey-arm',{actorId:'a',memorySetId:'m'})},wires:{activation:{id:'activation',route:'wire',from:'send',fromPort:'activation',to:'generate',toPort:'activation'},draft:{id:'draft',route:'wire',from:'generate',fromPort:'draft',to:'review',toPort:'draft'}},definitions:{},portals:{}};}
function fixture(options={}){const g=graph(),controller=new AbortController();let currentScope=scope,live=true;const source={sourceId:'native-scene',revision:'r',sceneId:'c',watch:'scene-context'};const service=createNativeRecallController({getActive:()=>{options.onActive?.();return {scope:currentScope,graph:g,signature:workflowSignature(g)};},...(options.registerHotkey?{registerHotkey:options.registerHotkey}:{})});const run={};assert.equal(service.begin(run,{scope,signature:workflowSignature(g),signal:controller.signal,getGeneration:()=>({generationId:'g',kind:'reply',stage:'pre',newlyGenerated:true}),isCurrent:()=>live}).ok,true);return {g,service,run,source,controller,setScope:value=>currentScope=value,setLive:value=>live=value};}
const retain=(f,operation,inputs,artifact,rawResult={ok:true,artifact},settings={})=>f.service.retain(f.run,{node:node('n',operation,settings),address:{workflowId:'w',instancePath:[],nodeId:'n'},inputs,artifact,portId:'out',rawResult});
test('private provenance requires the exact live root result and ignores copied metadata/results/artifacts',()=>{
 const f=fixture(),artifact=Object.freeze({kind:'context',messages:[],source:f.source}),raw={ok:true,artifact};assert.equal(f.service.capture(f.run,raw,{kind:'source',source:f.source,text:'Actual narrative.',fresh:()=>true}).ok,true);assert.equal(retain(f,'scene-context',{},artifact,raw).ok,true);assert.equal(f.service.lookup(f.run,artifact).ok,true);const copy=structuredClone(artifact);assert.equal(f.service.lookup(f.run,copy).ok,false);assert.equal(retain(f,'scene-context',{},copy,structuredClone(raw)).ok,true);assert.equal(f.service.lookup(f.run,copy).ok,false);f.service.releaseRun(f.run);assert.equal(f.service.lookup(f.run,artifact).ok,false);
});
test('source-only literal casts never acquire presence but an actual verified interpretation may',()=>{
 const f=fixture(),artifact={kind:'context',messages:[],source:f.source},raw={ok:true,artifact};f.service.capture(f.run,raw,{kind:'source',source:f.source,text:'A waits.',fresh:()=>true});retain(f,'scene-context',{},artifact,raw);
 const cast={kind:'data',value:{sceneId:'c',sourceId:'native-scene',revision:'r',actors:[{actorId:'a',status:'present',evidence:'A waits.'}]}},presence={kind:'data',value:{schemaVersion:1,recordType:'scene-presence',sceneId:'c',sourceId:'native-scene',revision:'r',actorId:'a',status:'present',evidence:'A waits.'}};
 retain(f,'select-fields',{in:artifact},cast);retain(f,'scene-presence',{in:cast},presence);assert.equal(f.service.authorizePresence(f.run,presence,{actorId:'a'}).ok,false);
 retain(f,'model-call',{context:artifact},cast,{ok:true,artifact:cast,reports:[{code:'MODEL_CALL',actualCalls:1}]});retain(f,'scene-presence',{in:cast},presence);assert.equal(f.service.authorizePresence(f.run,presence,{actorId:'a'}).ok,true);assert.equal(f.service.authorizePresence(f.run,structuredClone(presence),{actorId:'a'}).ok,false);assert.equal(f.service.authorizePresence(f.run,presence,{actorId:'other'}).ok,false);
});
test('provenance cancellation in a trusted source callback cannot retain late output',()=>{
 const f=fixture(),artifact={kind:'data',value:[]},raw={ok:true,artifact};f.service.capture(f.run,raw,{kind:'file',recordValue:[],fresh:()=>{f.controller.abort();return true;}});const kept=retain(f,'read-file',{},artifact,raw);assert.equal(kept.ok,false);assert.equal(f.service.lookup(f.run,artifact).ok,false);
});
test('shortcut registration reentrancy and disposal remain bounded and cannot resurrect a closed listener',()=>{
 let service,nested,disposes=0;const g=graph();service=createNativeRecallController({getActive:()=>({scope,graph:g,signature:workflowSignature(g)}),registerHotkey:()=>{nested=service.sync();service.dispose();return {ok:true,data:{dispose:()=>{disposes++;service.sync();}}};}});const result=service.sync();assert.equal(nested.ok,false);assert.equal(nested.error.code,'RECALL_REGISTRATION_PENDING');assert.equal(result.ok,false);assert.equal(disposes,1);assert.deepEqual(service.status().data,{scope:null,requests:[],shortcuts:[],version:1});assert.equal(service.queue('hotkey').ok,false);
});
function runtimeGraph(){const g=graph();g.nodes.text=node('text','text',{text:'{"note":"Use the scene"}'});g.nodes.decode=node('decode','json-decode');g.nodes.guide=node('guide','compose',{mode:'template',template:'{note}',outputKind:'guidance'});for(const [id,from,fromPort,to,toPort]of [['json','text','out','decode','in'],['data','decode','out','guide','data'],['guidance','guide','out','generate','guidance']])g.wires[id]={id,route:'wire',from,fromPort,to,toPort};return g;}
test('private runtime provenance acknowledgment failure holds dependent native output and redacts callback errors',async()=>{
 for(const failure of ['reject','throw']){let generated=0;const result=await runWorkflowForHost(runtimeGraph(),{runId:'proof-failure',countTokens:async()=>({tokens:1})},{executeHostOperation:async node=>{if(node.operation==='on-send')return {ok:true,outputs:{activation:{kind:'data',value:{}}}};generated++;return {ok:true,outputs:{draft:{kind:'draft',text:'Native',source:{token:'owned',originalText:'Native'}}}};},retainRecallProvenance:payload=>{if(payload.node.operation==='json-decode'){if(failure==='throw')throw new Error('RAW PRIVATE ERROR');return {ok:false,error:{code:'RAW',message:'RAW PRIVATE ERROR'}};}return {ok:true,data:{retained:true}};}});assert.equal(result.ok,false);assert.equal(result.error.code,'RECALL_PROVENANCE_FAILED');assert.equal(generated,0);assert.equal(JSON.stringify(result).includes('RAW PRIVATE ERROR'),false);}
});
test('runtime cancellation after awaited private provenance capture records no late dependent native release',async()=>{
 const controller=new AbortController();let generated=0;const result=await runWorkflowForHost(runtimeGraph(),{runId:'proof-cancel',signal:controller.signal,countTokens:async()=>({tokens:1})},{executeHostOperation:async node=>{if(node.operation==='on-send')return {ok:true,outputs:{activation:{kind:'data',value:{}}}};generated++;return {ok:true,outputs:{draft:{kind:'draft',text:'Native',source:{token:'owned',originalText:'Native'}}}};},retainRecallProvenance:async payload=>{if(payload.node.operation==='json-decode'){await Promise.resolve();controller.abort();}return {ok:true,data:{retained:true}};}});assert.equal(result.ok,false);assert.equal(result.error.code,'ABORTED');assert.equal(result.recording.status,'cancelled');assert.equal(generated,0);
});
test('Prompted Memory holder authority requires an exact ordered Current Holder producer on actual source evidence',async()=>{
 const {executeEvent}=await import('../src/workflow/operations/event-nodes.js?v=0.27.0');const {executeCollection}=await import('../src/workflow/operations/collection-nodes.js?v=0.27.0');const {executePrimitive}=await import('../src/workflow/operations/nodes.js?v=0.27.0');const f=fixture();assert.equal(typeof f.service.authorizeHolderEvent,'function');
 const source={...f.source,text:'Sword glows.',visibility:'public'},sourceArtifact={kind:'data',value:source},sourceResult={ok:true,artifact:sourceArtifact};f.service.capture(f.run,sourceResult,{kind:'source',source,text:source.text,fresh:()=>true});retain(f,'player-event-source',{},sourceArtifact,sourceResult);
 const entities={kind:'data',value:{actorIds:['a','b'],itemIds:['sword']}},mentionNode=node('mention','item-mention-trigger',{actorId:'a',itemId:'sword',aliases:['Sword'],watch:'scene-context'});const mention=await executeEvent(mentionNode,{source:sourceArtifact,entities},{phase:'pre'});assert.equal(mention.ok,true);retain(f,'item-mention-trigger',{source:sourceArtifact,entities},mention.outputs.out,mention,{actorId:'a',itemId:'sword',aliases:['Sword'],watch:'scene-context'});
 const holder=await executeEvent(node('holder','current-holder'),{events:mention.outputs.out,holders:{kind:'data',value:{sword:'a'}}},{phase:'pre'});assert.equal(holder.ok,true);assert.equal(f.service.retain(f.run,{node:node('holder','current-holder'),address:{workflowId:'w',instancePath:[],nodeId:'holder'},inputs:{events:mention.outputs.out,holders:{kind:'data',value:{sword:'a'}}},artifact:holder.outputs.events,portId:'events',rawResult:holder}).ok,true);
 const collectionNode=node('pick','collection',{mode:'lookup',fieldPath:['holderId'],value:'a'});const collection=await executeCollection(collectionNode,{in:holder.outputs.events},{phase:'pre'});assert.equal(collection.ok,true);retain(f,'collection',{in:holder.outputs.events},collection.artifact,collection,{mode:'lookup',fieldPath:['holderId'],value:'a'});
 const event=holder.outputs.events.value[0],fields=Object.keys(event).map(name=>({name,path:['value',name]})),selected=await executePrimitive(node('single','select-fields',{fields}),{in:collection.artifact},{phase:'pre'});assert.equal(selected.ok,true);retain(f,'select-fields',{in:collection.artifact},selected.artifact,selected,{fields});const allowed=f.service.authorizeHolderEvent(f.run,selected.artifact,{actorId:'a'});assert.equal(allowed.ok,true,JSON.stringify(allowed.error));assert.equal(allowed.data.eventId,event.eventId);assert.equal(f.service.authorizeHolderEvent(f.run,structuredClone(selected.artifact),{actorId:'a'}).ok,false);assert.equal(f.service.authorizeHolderEvent(f.run,selected.artifact,{actorId:'b'}).ok,false);
 const literal={kind:'data',value:event};assert.equal(f.service.authorizeHolderEvent(f.run,literal,{actorId:'a'}).ok,false);f.controller.abort();assert.equal(f.service.authorizeHolderEvent(f.run,selected.artifact,{actorId:'a'}).ok,false);
});

test('For Each and Collection cannot carry invented, reassigned or rewritten occurrence identity from an authenticated parent',async()=>{
 const {executeEvent}=await import('../src/workflow/operations/event-nodes.js?v=0.27.0');const {executeControl}=await import('../src/workflow/operations/control-nodes.js?v=0.27.0');const {executeCollection}=await import('../src/workflow/operations/collection-nodes.js?v=0.27.0');const {normalizeOccurrences,confirmOccurrences}=await import('../src/workflow/operations/event-data.js?v=0.27.0');
 const f=fixture(),source={...f.source,text:'A waits.',visibility:'public'},input={kind:'data',value:source},raw={ok:true,artifact:input},entities={kind:'data',value:{actorIds:['a','b'],itemIds:[]}};f.service.capture(f.run,raw,{kind:'source',source,text:source.text,fresh:()=>true});retain(f,'player-event-source',{},input,raw);
 const candidate={eventType:'scene-action',actorId:'a',position:{start:0,end:8},semantics:'actual'},candidates={kind:'data',value:[candidate]},normalized=await executeEvent(node('normalize','event-normalize'),{source:input,entities,candidates},{phase:'pre'});assert.equal(normalized.ok,true);retain(f,'event-normalize',{source:input,entities,candidates},normalized.artifact,normalized);
 const foreign=normalizeOccurrences(source,[{...candidate,actorId:'b'}],entities.value);assert.equal(foreign.ok,true);const confirmed=confirmOccurrences(foreign.data.events,foreign.data.events.map(event=>({eventId:event.eventId,accepted:true})));assert.equal(confirmed.ok,true);const helper={id:'h',version:1,semanticHash:'sha256:'+'a'.repeat(64)},settings={helper,limit:2,requestBoundPerIteration:0};
 const changed=await executeControl(node('each','for-each',settings),{in:normalized.artifact},{iterateHelper:async()=>({ok:true,artifact:{kind:'data',value:confirmed.data.events}})});assert.equal(changed.ok,true);f.service.retain(f.run,{node:node('each','for-each',settings),address:{workflowId:'w',instancePath:[],nodeId:'each'},inputs:{in:normalized.artifact},artifact:changed.outputs.out,portId:'out',rawResult:changed});assert.equal(f.service.lookup(f.run,changed.outputs.out).ok,false,'A canonical new actor/event ID is still not an unchanged parent occurrence.');
 const confirmedNode=node('confirmed','confirm-events'),confirmedResult=await executeEvent(confirmedNode,{events:normalized.artifact,decisions:{kind:'data',value:normalized.artifact.value.map(event=>({eventId:event.eventId,accepted:true}))}});retain(f,'confirm-events',{events:normalized.artifact},confirmedResult.artifact,confirmedResult);assert.equal(f.service.lookup(f.run,confirmedResult.artifact).ok,true);
 const merged=await executeCollection(node('merge','collection',{mode:'merge'}),{in:confirmedResult.artifact,other:{kind:'data',value:confirmed.data.events}},{phase:'pre'});assert.equal(merged.ok,true);retain(f,'collection',{in:confirmedResult.artifact,other:{kind:'data',value:confirmed.data.events}},merged.artifact,merged,{mode:'merge'});
 const records={kind:'data',value:[{id:'m',actorId:'a',text:'Private memory'}]},recordResult={ok:true,artifact:records};f.service.capture(f.run,recordResult,{kind:'file',recordValue:records.value,fresh:()=>true});retain(f,'read-file',{},records,recordResult);
 const cast={kind:'data',value:{sceneId:'c',sourceId:f.source.sourceId,revision:f.source.revision,actors:[{actorId:'a',status:'present',evidence:'A waits.'}]}},presence={kind:'data',value:{schemaVersion:1,recordType:'scene-presence',sceneId:'c',sourceId:f.source.sourceId,revision:f.source.revision,actorId:'a',status:'present',evidence:'A waits.'}};retain(f,'model-call',{data:input},cast,{ok:true,artifact:cast,reports:[{code:'MODEL_CALL',actualCalls:1}]});retain(f,'scene-presence',{in:cast},presence);
 const result=await f.service.execute(f.run,node('recall','recall',{actorId:'a',memorySetId:'m',activation:'event',eventTypes:['scene-action']}),{records,presence,events:merged.artifact},{phase:'pre',countTokens:()=>({tokens:1})});assert.equal(result.ok,false,'An unrelated literal collection cannot gain event trigger authority from a valid collection input.');
});

async function canonicalMemoryHost(mode){
 const {createNativeWorkflowController}=await import('../src/workflow/host.js?v=0.27.0');const {makeRecord}=await import('../src/workflow/introspection/contracts.js?v=0.27.0');const episodes=[{id:'e1',text:'Actual native memory',classification:'observation',sourceRefs:[]},{id:'e2',text:'Second native memory',classification:'interpretation',sourceRefs:[]}],stored=makeRecord('actor-state',{scope:{chatId:'c',actorId:'character:0'},store:{id:'native-chat',version:0}},{episodes},[]);assert.equal(stored.ok,true);
 const g=graph();g.nodes.hotkey.actorId='character:0';g.nodes.scene=node('scene','scene-context',{includeCharacter:false,visibilityMode:'public'});g.nodes.prompt=node('prompt','text',{text:'Actual actors from context.source and narrative'});g.nodes.cast=node('cast','model-call',{outputKind:'data'});g.nodes.presence=node('presence','scene-presence',{actorId:'character:0'});g.nodes.memory=node('memory','memory',{view:'episodes'});g.nodes.recall=node('recall','recall',{actorId:'character:0',memorySetId:'m'});
 const fields=['schemaVersion','recordType','scope','store','sourceRefs','payload'].map(name=>({name,path:[name]}));
 const replacement=(name,value)=>Object.assign(fields.find(field=>field.name===name),{path:['missing'],required:false,default:value});
 if(mode==='invented')replacement('payload',{episodes:[{id:'e1',text:'Invented canonical memory',classification:'observation',sourceRefs:[]}]});
 if(mode==='classification')replacement('payload',{episodes:[{...episodes[0],classification:'possibility'}]});
 if(mode==='scope')replacement('scope',{chatId:'c',actorId:'character:99'});
 if(mode==='version')replacement('store',{id:'native-chat',version:4});
 if(mode==='store')replacement('store',{id:'invented-store',version:0});
 if(mode==='sourceRefs')replacement('sourceRefs',[{id:'invented-source',revision:'invented-revision'}]);
 if(mode==='subset')replacement('payload',{episodes:[episodes[1]]});
 g.nodes.project=node('project','select-fields',{fields});const wire=(id,from,fromPort,to,toPort)=>g.wires[id]={id,route:'wire',from,fromPort,to,toPort};for(const args of [['cp','prompt','out','cast','prompt'],['cx','scene','out','cast','context'],['ps','cast','out','presence','in'],['mp','memory','out','project','in'],['records','project','out','recall','records'],['presence','presence','out','recall','presence'],['guidance','recall','out','generate','guidance']])wire(...args);
 if(mode==='plain-subset'){g.nodes.project=node('project','select-fields',{fields});g.nodes.format=node('format','format',{mapping:'select',fields:[{name:'id',path:['payload','episodes','1','id']},{name:'text',path:['payload','episodes','1','text']},{name:'sourceRefs',path:['payload','episodes','1','sourceRefs']},{name:'actorId',path:['missing'],required:false,default:'character:0'},{name:'revision',path:['missing'],required:false,default:'0'}]});wire('format','project','out','format','in');g.wires.records.from='format';g.wires.records.fromPort='records';}
 const listeners=new Map(),c={chatId:'c',characterId:0,groupId:null,characters:[{data:{name:'Mara'}}],chat:[{mes:'Mara waits.',is_user:true,extra:{}}],chatMetadata:{latticeIntrospection:{'native-chat':{'character:0':{state:stored.data,receipts:[]}}}},extensionPrompts:{},eventTypes:Object.fromEntries(['GENERATION_STARTED','GENERATION_STOPPED','GENERATION_ENDED','MESSAGE_RECEIVED','CHAT_CHANGED','CHARACTER_SELECTED'].map(name=>[name,name]))};
 c.eventSource={on(name,fn){const list=listeners.get(name)??[];list.push(fn);listeners.set(name,list);},removeListener(name,fn){listeners.set(name,(listeners.get(name)??[]).filter(value=>value!==fn));},async emit(name,...args){for(const fn of listeners.get(name)??[])await fn(...args);}};c.setExtensionPrompt=(key,value)=>c.extensionPrompts[key]={value};
 const controller=createNativeWorkflowController({context:()=>c,getGraph:phase=>phase==='unified'?g:undefined,isEnabled:()=>true,userId:()=>scope.userId,isBusy:()=>true,countTokens:async()=>({tokens:1}),resolveBinding:()=>({ok:true,data:{profileId:'fixed',model:'test'}}),request:async request=>{const material=JSON.parse(request.messages.at(-1).content),source=material.context.source;return {ok:true,data:{text:JSON.stringify({sceneId:source.sceneId,sourceId:source.sourceId,revision:source.revision,actors:[{actorId:'character:0',status:'present',evidence:'Mara waits.'}]}),finish:'stop'}};}});controller.subscribe();assert.equal(controller.queueRecall('hotkey').ok,true);await c.eventSource.emit('GENERATION_STARTED','normal',{},false);const result=await controller.beforeGenerate(c.chat.map(value=>({...value})),8192,()=>{},'normal');const prompts=Object.values(c.extensionPrompts).map(value=>value.value);controller.dispose();return {result,prompts,c,stored};
}
test('actual native Memory projection cannot replace canonical episodes with an invented default payload',async()=>{
 const f=await canonicalMemoryHost('invented');assert.equal(f.result.ok,false,'Select Fields must not make its transformed payload its own trusted Memory original.');assert.equal(f.prompts.some(text=>text.includes('Invented canonical memory')),false);assert.deepEqual(f.c.chatMetadata.latticeIntrospection['native-chat']['character:0'].state,f.stored.data);
});
test('actual canonical Memory envelope metadata and episode fields retain trusted capture identity',async()=>{
 for(const mode of ['scope','version','store','sourceRefs','classification']){const f=await canonicalMemoryHost(mode);assert.equal(f.result.ok,false,mode);assert.equal(f.prompts.every(text=>!text),true,mode);}
});
test('unchanged canonical Memory projection and exact episode subsets remain useful to native Recall',async()=>{
 for(const mode of ['unchanged','subset','plain-subset']){const f=await canonicalMemoryHost(mode);assert.equal(f.result.ok,true,JSON.stringify({mode,error:f.result.error}));assert.equal(f.prompts.some(text=>text.includes('Second native memory')),true,mode);if(mode==='subset')assert.equal(f.prompts.some(text=>text.includes('Actual native memory')),false);}
});


test('selected real Branch output preserves exact source/presence proof and rejects opposite, rewritten or claimed clones',async()=>{
 const {executeControl}=await import('../src/workflow/operations/control-nodes.js?v=0.27.0');
 const f=fixture(),source={kind:'context',messages:[],source:f.source,visibility:{kind:'public'}},root={ok:true,artifact:source};f.service.capture(f.run,root,{kind:'source',source:f.source,text:'A waits.',fresh:()=>true});retain(f,'scene-context',{},source,root);
 const cast={kind:'data',value:{sceneId:'c',sourceId:'native-scene',revision:'r',actors:[{actorId:'a',status:'present',evidence:'A waits.'}]}},presence={kind:'data',value:{schemaVersion:1,recordType:'scene-presence',sceneId:'c',sourceId:'native-scene',revision:'r',actorId:'a',status:'present',evidence:'A waits.'},visibility:{kind:'public'}};
 retain(f,'model-call',{context:source},cast,{ok:true,artifact:cast,reports:[{code:'MODEL_CALL',actualCalls:1}]});retain(f,'scene-presence',{in:cast},presence);
 for(const [input,kind]of [[source,'context'],[presence,'data']])for(const accepted of [true,false,null]){
  const branch=node('route','branch',{artifactKind:kind}),inputs={in:input,condition:{kind:'data',value:{accepted}}},raw=await executeControl(branch,inputs,{phase:'pre'});assert.equal(raw.ok,true);const selected=accepted===true?'yes':accepted===false?'no':'unresolved',output=Object.freeze(structuredClone(raw.outputs[selected]));
  const keep=(artifact,portId=selected,rawResult=raw,settings={})=>f.service.retain(f.run,{node:{...branch,...settings},address:{workflowId:'w',instancePath:[],nodeId:'route'},inputs,artifact,portId,rawResult});
  assert.equal(keep(output).ok,true);assert.equal(f.service.lookup(f.run,output).data?.kind,input===presence?'presence':'source');if(input===presence)assert.equal(f.service.authorizePresence(f.run,output,{actorId:'a'}).ok,true);
  for(const attempt of ['opposite','claimed-clone','visibility','source','modifier','fields','default']){
   const candidate=structuredClone(output);if(attempt==='visibility')candidate.visibility={kind:'hidden'};if(attempt==='source'){if(candidate.value)candidate.value.revision='forged';else candidate.source.revision='forged';}
   const altered=attempt==='claimed-clone'?structuredClone(raw):raw,settings=attempt==='modifier'?{modifiers:[{type:'prefix',text:'changed'}]}:attempt==='fields'?{fields:[]}:attempt==='default'?{default:{}}:{};
   keep(candidate,attempt==='opposite'?(selected==='yes'?'no':'yes'):selected,altered,settings);assert.equal(f.service.lookup(f.run,candidate).ok,false,attempt);
  }
 }
 const staleBranch=node('stale','branch',{artifactKind:'data'}),inputs={in:presence,condition:{kind:'data',value:true}},raw=await executeControl(staleBranch,inputs,{phase:'pre'}),output=structuredClone(raw.outputs.yes);f.setLive(false);assert.equal(f.service.retain(f.run,{node:staleBranch,inputs,artifact:output,portId:'yes',rawResult:raw}).ok,false);assert.equal(f.service.authorizePresence(f.run,output,{actorId:'a'}).ok,false);
});
