import assert from 'node:assert/strict';
import * as contracts from '../src/workflow/contracts.js';
import * as catalog from '../src/workflow/catalog.js';

const fixture = () => ({ id: 'root', schema: 3, runtime: 2, mode: 'native-unified', nodes: {
    source: { id: 'source', type: 'workflow', operation: 'scene-context' },
    compact: { id: 'compact', type: 'workflow', operation: 'smart-compactor' },
    other: { id: 'other', type: 'workflow', operation: 'smart-compactor', enabled: false },
}, wires: { a: { id: 'a', route: 'wire', from: 'source', fromPort: 'out', to: 'compact', toPort: 'in', order: 0 }, b: { id: 'b', route: 'wire', from: 'source', fromPort: 'out', to: 'other', toPort: 'in', order: 1 } }, groups: {} });

// Structural authoring validation must allow absent terminals and disabled unfinished branches.
assert.equal(typeof contracts.validateGraphStructure, 'function');
assert.equal(contracts.validateGraphStructure(fixture()).ok, true);
assert.equal(contracts.validateWorkflow(fixture()).error.code, 'MISSING_TERMINAL');
assert.equal(typeof contracts.isWorkflowGraph, 'function');
assert.equal(contracts.isWorkflowGraph(fixture()), true);
for (const schema of [1, 2, 99]) assert.equal(contracts.isWorkflowGraph({ ...fixture(), schema }), false);
let getterCalls = 0;
assert.equal(contracts.isWorkflowGraph({ get schema() { getterCalls++; return 3; } }), false);
assert.equal(getterCalls, 0);
assert.equal(typeof catalog.portsForNode, 'function');
assert.deepEqual(catalog.portsForNode(fixture(), fixture().nodes.source).map(p => [p.id, p.direction, p.kind]), [['out', 'output', 'context']]);
assert.deepEqual(catalog.portsForNode(fixture(), { type: 'workflow', operation: 'guidance' }).map(p => p.id), ['in', 'out']);
const { cloneWorkflowDocument } = await import('../src/workflow/document.js');
const original = fixture(), before = structuredClone(original);
const normalized = cloneWorkflowDocument(original);
assert.equal(normalized.ok, true);
assert.deepEqual(original, before);
assert.equal(normalized.data.schema, 3);
assert.equal(normalized.data.runtime, 2);
assert.equal(normalized.data.wires.a.fromPort, 'out');
assert.equal(normalized.data.wires.a.toPort, 'in');
assert.equal(normalized.data.wires.a.route, 'wire');
assert.deepEqual(Object.keys(normalized.data.wires), ['a', 'b']);
assert.equal(cloneWorkflowDocument({ ...original, schema: 1 }).ok, false);
assert.equal(cloneWorkflowDocument({ ...original, runtime: 9 }).error.code, 'UNSUPPORTED_VERSION');
assert.equal(contracts.validateGraphStructure(normalized.data).ok, true);
assert.deepEqual(cloneWorkflowDocument(normalized.data).data, normalized.data);
const wrongPort = structuredClone(normalized.data);
wrongPort.wires.a.fromPort = 'in';
assert.equal(contracts.validateGraphStructure(wrongPort).error.code, 'INVALID_PORT');
const wrongDirection = structuredClone(normalized.data);
wrongDirection.wires.a.toPort = 'out';
assert.equal(contracts.validateGraphStructure(wrongDirection).error.code, 'INVALID_PORT');
const overfull = structuredClone(normalized.data);
overfull.wires.c = { id: 'c', route: 'wire', from: 'other', fromPort: 'out', to: 'compact', toPort: 'in' };
assert.equal(contracts.validateGraphStructure(overfull).error.code, 'AMBIGUOUS_INPUT');
const rerouted = structuredClone(normalized.data);
rerouted.nodes.r = { id: 'r', type: 'workflow', operation: 'reroute', artifactKind: 'context', phase: 'pre' };
rerouted.wires.a.to = 'r';
rerouted.wires.c = { id: 'c', route: 'wire', from: 'r', fromPort: 'out', to: 'compact', toPort: 'in' };
assert.equal(contracts.validateGraphStructure(rerouted).ok, true);
assert.equal(catalog.operationFor(rerouted.nodes.r).requestBound, 0);
assert.deepEqual(catalog.portsForNode(rerouted, rerouted.nodes.r).map(p => p.kind), ['context', 'context']);
rerouted.nodes.r.phase = 'post';
assert.equal(contracts.validateGraphStructure(rerouted).error.code, 'INVALID_STAGE_DEPENDENCY');
rerouted.nodes.r.phase = 'pre';
rerouted.nodes.r.artifactKind = 'imaginary';
assert.equal(contracts.validateGraphStructure(rerouted).ok, false);
const controls = catalog.OPERATIONS['smart-compactor'].controlDescriptors;
assert.equal(controls.targetTokens.type, 'integer');
assert.equal(controls.targetTokens.min, 1);
assert.deepEqual(controls.method.values, ['select', 'compress']);
assert.deepEqual(catalog.OPERATIONS['smart-compactor'].controls, ['targetTokens', 'purpose', 'method', 'keepRecent', 'pins', 'maxTokens']);
const ports = await import('../src/workflow/ports.js').catch(() => ({}));
assert.equal(typeof ports.prepareConnection, 'function');
const connect = (graph, from, to, replace = false) => ports.prepareConnection(graph, { from: { nodeId: from, portId: 'out' }, to: { nodeId: to, portId: 'in' }, replace });
const beforeConnection = structuredClone(normalized.data);
assert.equal(connect(normalized.data, 'other', 'compact').error.code, 'AMBIGUOUS_INPUT');
assert.deepEqual(normalized.data, beforeConnection);
const duplicate = connect(normalized.data, 'source', 'compact');
assert.equal(duplicate.data.changed, false);
assert.deepEqual(duplicate.data.candidate, normalized.data);
const replacement = connect(normalized.data, 'other', 'compact', true);
assert.equal(replacement.ok, true);
assert.equal(replacement.data.changed, true);
assert.deepEqual(replacement.data.removedEdgeIds, ['a']);
assert.equal(replacement.data.addedEdgeIds.length, 1);
assert.deepEqual(replacement.data.candidate.wires[replacement.data.addedEdgeIds[0]], { id: replacement.data.addedEdgeIds[0], route: 'wire', from: 'other', fromPort: 'out', to: 'compact', toPort: 'in' });
assert.equal(Object.values(replacement.data.candidate.wires).find(w => w.to === 'compact').from, 'other');
assert.deepEqual(normalized.data, beforeConnection);
assert.equal(connect(replacement.data.candidate, 'compact', 'other', true).error.code, 'CYCLE');
assert.equal(connect(normalized.data, 'compact', 'compact', true).error.code, 'CYCLE');
assert.equal(ports.prepareConnection(normalized.data, { from: { nodeId: 'source', portId: 'missing' }, to: { nodeId: 'compact', portId: 'in' }, replace: true }).error.code, 'INVALID_PORT');
const disconnected = ports.prepareDisconnection(normalized.data, ['a']);
assert.equal(disconnected.ok, true);
assert.equal(disconnected.data.candidate.wires.a, undefined);
assert.equal(disconnected.data.candidate.wires.b.id, 'b');
assert.deepEqual(normalized.data, beforeConnection);
assert.equal(ports.prepareDisconnection(normalized.data, ['absent']).data.changed, false);
assert.equal(ports.prepareDisconnection(normalized.data, [null]).ok, false);
assert.equal(ports.prepareConnection(normalized.data, { get from() { throw new Error('do not invoke'); } }).ok, false);
assert.equal(typeof replacement.data.baseDocumentSignature, 'string');
// Untrusted data fails without touching accessors or accepting inherited identities.
const badGraphs = [null, [], Object.assign(Object.create({ inherited: true }), normalized.data), { ...normalized.data, nodes: [] }, { ...normalized.data, wires: [] }, { ...normalized.data, get name() { throw new Error('getter invoked'); } }];
for (const bad of badGraphs) assert.equal(contracts.validateGraphStructure(bad).ok, false);
const inherited = structuredClone(normalized.data);
inherited.wires.a.from = 'toString';
assert.equal(contracts.validateGraphStructure(inherited).error.code, 'DANGLING_WIRE');
const hiddenCycle = structuredClone(normalized.data);
hiddenCycle.wires.a.from = 'other'; hiddenCycle.wires.b.from = 'compact';
assert.equal(contracts.validateGraphStructure(hiddenCycle).error.code, 'CYCLE');
const incompatible = structuredClone(normalized.data);
incompatible.nodes.plan = { id: 'plan', type: 'workflow', operation: 'response-plan' };
incompatible.wires.a.from = 'plan';
assert.equal(contracts.validateGraphStructure(incompatible).error.code, 'ARTIFACT_KIND');
const moved = structuredClone(normalized.data);
moved.nodes.source.x = -1234; moved.nodes.compact.title = 'Renamed'; moved.view = { x: 123, y: -456, zoom: 2 };
assert.deepEqual(contracts.validateGraphStructure(moved), contracts.validateGraphStructure(normalized.data));
assert.notEqual(ports.graphDocumentSignature(moved), ports.graphDocumentSignature(normalized.data), 'document precondition covers intervening aliases/layout');
const cameraOnly = { ...normalized.data, view: { x: 123, y: -456, zoom: 2 } };
assert.equal(ports.graphDocumentSignature(cameraOnly), ports.graphDocumentSignature(normalized.data));
const presentationSave = { ...normalized.data, view: { x: 500, y: 300, zoom: 0.5 }, selection: ['compact'], updatedAt: 123456 };
assert.equal(ports.graphDocumentSignature(presentationSave), ports.graphDocumentSignature(normalized.data), 'camera/selection saves and root timestamps do not stale prepared document edits');
const editedBody = structuredClone(presentationSave);
editedBody.nodes.compact.targetTokens = 2200;
assert.notEqual(ports.graphDocumentSignature(editedBody), ports.graphDocumentSignature(normalized.data), 'editable operation body remains a document precondition');
assert.notEqual(ports.graphDocumentSignature({ ...presentationSave, id: 'other-root' }), ports.graphDocumentSignature(normalized.data), 'root identity remains a precondition');
assert.notEqual(ports.graphDocumentSignature({ ...presentationSave, createdAt: 123 }), ports.graphDocumentSignature(normalized.data), 'root creation identity remains a precondition');
const malformedIdentity = structuredClone(normalized.data);
malformedIdentity.wires.a.id = 'different';
assert.equal(contracts.validateGraphStructure(malformedIdentity).error.code, 'MALFORMED_WORKFLOW');
const legacy = { schema: 1, nodes: { d: { id: 'd', type: 'decider' }, s: { id: 's', type: 'state' } }, wires: { legacy: { id: 'legacy', from: 'd', to: 's', kind: 'save', port: 'flag' } } };
const legacyBefore = structuredClone(legacy);
assert.equal(cloneWorkflowDocument(legacy).error.code, 'UNSUPPORTED_VERSION');
assert.equal(connect(legacy, 'd', 's').ok, false);
assert.deepEqual(legacy, legacyBefore, 'retired keyed endpoints and wire modes are never reinterpreted');
const { workflowSignature } = await import('../src/workflow/runtime.js');
assert.equal(typeof ports.graphSemanticSignature, 'function');
assert.equal(ports.graphSemanticSignature(original), workflowSignature(original), 'current semantic signature is shared by runtime');
assert.equal(ports.graphSemanticSignature(moved), ports.graphSemanticSignature(normalized.data), 'layout/aliases/camera do not change execution identity');
assert.notEqual(ports.graphSemanticSignature(wrongPort), ports.graphSemanticSignature(normalized.data), 'named endpoint changes invalidate execution');
const rerouteSignatureGraph = structuredClone(normalized.data);
rerouteSignatureGraph.nodes.r = { id: 'r', type: 'workflow', operation: 'reroute', artifactKind: 'context', phase: 'pre' };
const rerouteSignature = ports.graphSemanticSignature(rerouteSignatureGraph);
rerouteSignatureGraph.nodes.r.artifactKind = 'guidance';
assert.notEqual(ports.graphSemanticSignature(rerouteSignatureGraph), rerouteSignature);
assert.equal(connect(normalized.data, 'other', 'compact', true).data.baseSignature, ports.graphSemanticSignature(normalized.data));
const parity = fixture();
parity.roles = { Analysis: { profileId: 'local', model: 'model' } };
parity.groups = { g: { id: 'g', enabled: false, title: 'Label', entry: 'source', exit: 'compact', members: ['source', 'compact'] } };
parity.nodes.source.inGroup = 'g';
parity.nodes.compact.method = 'compress';
parity.nodes.note = { id: 'note', type: 'note', content: 'Presentation', inGroup: 'g' };
parity.nodes.validation = { id: 'validation', type: 'workflow', operation: 'validate-patches', protectedLiterals: ['protected'] };
assert.equal(ports.graphSemanticSignature(parity), workflowSignature(parity));
const regrouped = structuredClone(parity);
regrouped.groups.g.enabled = true; regrouped.groups.g.members = ['compact'];
delete regrouped.nodes.source.inGroup; regrouped.nodes.note.content = 'Changed presentation';
regrouped.wires.a.order = 99; regrouped.wires.a.kind = 'prepend';
assert.equal(ports.graphSemanticSignature(regrouped), ports.graphSemanticSignature(parity), 'groups, annotations and saved wire presentation metadata do not change execution');
assert.notEqual(ports.graphDocumentSignature(regrouped), ports.graphDocumentSignature(parity), 'presentation authoring edits remain in document freshness and history');
const bounded = { ...normalized.data, wires: {}, nodes: Object.fromEntries(Array.from({ length: 1000 }, (_, i) => [`n${i}`, { id: `n${i}`, type: 'note' }])) };
assert.equal(contracts.validateGraphStructure(bounded).ok, true);
bounded.nodes.excess = { id: 'excess', type: 'note' };
assert.equal(contracts.validateGraphStructure(bounded).error.code, 'MALFORMED_WORKFLOW');
console.log('workflow-ports: ok');
