import assert from 'node:assert/strict';
import {test} from 'node:test';
import {unifiedRecipeHost} from './helpers/unified-recipe-host.mjs';
import {operationFor,portsForNode} from '../src/workflow/catalog.js?v=0.27.0';
const n=(id,operation,extra={})=>({id,type:'workflow',operation,...extra}),w=(id,from,fromPort,to,toPort)=>({id,route:'wire',from,fromPort,to,toPort});
function graph(){return {id:'player-source',schema:3,runtime:2,mode:'native-unified',nodes:{source:n('source','player-event-source'),guide:n('guide','compose',{outputKind:'guidance',mode:'template',template:'Respond to the actual player action: {{data:}}'}),send:n('send','on-send'),generate:n('generate','generate-reply'),review:n('review','review-publish')},wires:{a:w('a','source','out','guide','data'),b:w('b','guide','out','generate','guidance'),c:w('c','send','activation','generate','activation'),d:w('d','generate','draft','review','draft')}};}
const target={workflowId:'player-source',instancePath:[],nodeId:'source',portId:'out'};
const source=result=>result.recording.artifacts.find(a=>a.kind==='data'&&a.value?.value?.watch==='player-message')?.value.value;
test('Player Event Source is a registered root native preparation source',()=>{const g=graph(),op=operationFor(g.nodes.source,{mode:g.mode,phase:'pre'});assert.equal(op?.hostOperation,true);assert.equal(op?.rootOnly,true);assert.equal(op?.requestBound,0);assert.deepEqual(portsForNode(g,g.nodes.source).map(p=>[p.id,p.kind,p.direction]),[['out','data','output']]);});
test('actual player source drives native guidance without auxiliary calls or persistence',async()=>{const f=unifiedRecipeHost(graph(),{playerText:'Mara uses her broken wand.'});const result=await f.generate('Violet sparks appear.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(source(result).text,'Mara uses her broken wand.');assert.equal(source(result).sceneId,'Story-2');assert.match(source(result).sourceId,/^turn:/);assert.equal(source(result).revision,source(result).sourceId);assert.equal(f.calls(),0);assert.equal(f.saves(),0);assert.equal(f.c.chat.at(-1).mes,'Violet sparks appear.');f.controller.dispose();});
test('bounded source reads retain turn identity while later identical turns get a distinct identity',async()=>{const g=graph(),f=unifiedRecipeHost(g,{playerText:'Mara uses her broken wand.'});const first=await f.controller.runTarget(g,target),again=await f.controller.runTarget(g,target);assert.equal(first.ok,true,JSON.stringify(first.error));assert.equal(again.ok,true,JSON.stringify(again.error));assert.equal(source(first).sourceId,source(again).sourceId);f.c.chat.push({mes:'An earlier result.',is_user:false,extra:{}},{mes:'Mara uses her broken wand.',is_user:true,extra:{},send_date:'later-turn'});const later=await f.controller.runTarget(g,target);assert.equal(later.ok,true,JSON.stringify(later.error));assert.notEqual(source(first).sourceId,source(later).sourceId);assert.equal(later.reviewHandles.length,0);assert.equal(f.saves(),0);f.controller.dispose();});
test('a restricted actual player message cannot be relabeled as a public event source',async()=>{const g=graph(),f=unifiedRecipeHost(g,{playerText:'Secret action.'});f.c.chat[0].visibility='hidden';const result=await f.controller.runTarget(g,target);assert.equal(result.ok,false);assert.equal(result.error.code,'PRIVATE_MATERIAL');assert.equal(JSON.stringify(result.recording).includes('Secret action.'),false);assert.equal(f.saves(),0);f.controller.dispose();});


test('a bounded player source holds downstream transport after text, privacy or actor scope changes',async()=>{
 for(const mutate of [c=>{c.chat[0].visibility='hidden';},c=>{c.chat[0].visibleTo=['character:elias.png'];},c=>{c.chat[0].mes='A changed player action.';},c=>{c.chat.push({mes:'A later action.',is_user:true,extra:{}});}]){const g=graph();g.nodes.prompt=n('prompt','text',{text:'Inspect supplied public action.'});g.nodes.model=n('model','model-call',{outputKind:'data'});g.wires.extra=w('extra','source','out','model','data');g.wires.prompt=w('prompt','prompt','out','model','prompt');let requests=0,changed=false;const f=unifiedRecipeHost(g,{playerText:'Secret action now restricted.',request:async()=>{requests++;return {ok:true,data:{text:'{}',finish:'stop'}};}});
  const result=await f.controller.runTarget(g,{workflowId:g.id,instancePath:[],nodeId:'model',portId:'out'},{onEvent:event=>{if(event.type==='node-settled'&&event.address?.nodeId==='source'&&!changed){changed=true;mutate(f.c);}}});assert.equal(changed,true);assert.equal(result.ok,false);assert.match(result.error.code,/STALE_SOURCE|STALE_ACTOR_SCOPE/);assert.equal(requests,0);assert.equal(result.actualCalls,0);f.controller.dispose();
 }
});
