import assert from 'node:assert/strict';
import {test} from 'node:test';
import {UNIFIED_WORKFLOW_EXAMPLE_DATA as entries} from '../src/workflow/unified-example-data.js';
import {unifiedRecipeHost} from './helpers/unified-recipe-host.mjs';
const graph=id=>structuredClone(entries.find(e=>e.id==='unified-'+id).packages[0].graph);
const response=value=>({ok:true,data:{text:typeof value==='string'?value:JSON.stringify(value),finish:'stop'}});
const doc=(targetId,content)=>({targetId,name:targetId,format:'json',content:JSON.stringify(content),visibility:{kind:'public'}});
test('dice stakes use a real retained face, deterministic bonus and accepted ledger',async()=>{
 const player='Mara rolls the bronze-d20 to pick the lock.';let calls=0,draws=0;
 const f=unifiedRecipeHost(graph('dice-stakes'),{playerText:player,documents:[doc('dice-outcomes',[])],random:()=>{draws++;return .6;},request:async()=>++calls===1?response({candidates:[{eventType:'item-used',actorId:'mara',itemId:'bronze-d20',position:{start:0,end:player.length},semantics:'actual'}]}):response({answers:{actual:{type:'noul',accepted:true}}})});
 const result=await f.generate('The lock opens quietly.');assert.equal(result.ok,true,JSON.stringify(result.error));const receipt=result.recording.artifacts.find(a=>a.kind==='data'&&a.value?.value===16);assert.equal(receipt.value.value,16);assert.equal(draws,1);assert.equal(calls,2);assert.equal(f.saves(),0);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));assert.equal(JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['dice-outcomes'].content)[0].selection.id,'face-13');assert.equal(f.saves(),1);await f.controller.apply(result.reviewHandles[0]);assert.equal(draws,1);f.controller.dispose();
});
test('alternate takes expose separately selectable candidates and publish only the chosen revision',async()=>{
 let calls=0;const f=unifiedRecipeHost(graph('alternate-takes'),{request:async options=>{calls++;if(options.messages[0].content.startsWith('Revise'))return response(JSON.parse(options.messages[1].content).instructions.includes('Lyrical')?'Copper light washed the pier as Mara reached it.':'Mara reached the pier.');return response({answers:{same:{type:'noul',accepted:true}}});}});
 const result=await f.generate('Mara reached the pier.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,2);assert.equal(calls,4);assert.equal(f.c.chat.at(-1).swipes.length,1);const applied=await f.controller.apply(result.reviewHandles.find(h=>h.terminal.address.nodeId==='lyrical-review'));assert.equal(applied.ok,true,JSON.stringify(applied.error));assert.equal(f.c.chat.at(-1).swipes.length,2);assert.match(f.c.chat.at(-1).mes,/Copper light/);const other=await f.controller.apply(result.reviewHandles.find(h=>h.terminal.address.nodeId==='review'));assert.equal(other.ok,false);assert.equal(f.c.chat.at(-1).swipes.length,2);f.controller.dispose();
});
test('puzzle checks the finite local solution and sends only the requested hint tier',async()=>{
 const f=unifiedRecipeHost(graph('solvable-puzzle'),{playerText:'Give me the first hint.',request:async options=>{assert.ok(!JSON.stringify(options.messages).includes('246'));return response({answer:null,hintTier:1});}});
 const result=await f.generate('Every digit is even.');assert.equal(result.ok,true,JSON.stringify(result.error));const direction=result.recording.artifacts.find(a=>a.kind==='guidance').value.text;assert.match(direction,/Every digit is even/);assert.ok(!direction.includes('Start at the smallest'));assert.ok(!direction.includes('246'));assert.equal(f.calls(),1);assert.equal(result.recording.artifacts.find(a=>a.kind==='data'&&a.value?.value===1).value.value,1);f.controller.dispose();
});
test('campaign callback preserves an existing record and fulfills it only from a quoted accepted completion',async()=>{
 const body='Mara repaid the harbor keeper.';let calls=0;const prior={id:'harbor-debt',status:'offered',text:'Mara promised to repay the harbor keeper',tags:['harbor']};
 const f=unifiedRecipeHost(graph('campaign-callback'),{playerText:'I return to the harbor.',documents:[doc('campaign-threads',[prior])],request:async()=>{calls++;if(calls===1)return response({relevant:true});if(calls===2)return response({answers:{relevant:{type:'noul',accepted:true}}});if(calls===3)return response([{eventType:'scene-action',actorId:'mara',position:{start:0,end:body.length},semantics:'actual'}]);return response({answers:{actual:{type:'noul',accepted:true}}});}});
 const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.saves(),0);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['campaign-threads'].content)[0];assert.equal(saved.status,'fulfilled');assert.equal(saved.text,prior.text);assert.deepEqual(saved.tags,prior.tags);assert.equal(saved.completionEvidence.text,body);assert.equal(calls,4);assert.equal(f.saves(),1);f.controller.dispose();
});

const clock=(absoluteMinute=400)=>doc('story-clock',{schemaVersion:1,clockId:'story-clock',calendarId:'campaign-days',dayLengthMinutes:1440,absoluteMinute,revision:1});
const extracted=(text,id='evidence',classification='observation')=>[{id,label:id,text,classification,evidence:[{start:0,end:text.length,quote:text}]}];

test('ensemble keeps observable contributions attributed and preserves the public native body',async()=>{
 const body='Mara and Elias reach the quiet pier.';const f=unifiedRecipeHost(graph('ensemble-perspectives'),{request:async options=>{const m=JSON.parse(options.messages[1].content);if(m.request?.startsWith('Return {sceneId'))return response({sceneId:m.data.sceneId,sourceId:m.data.sourceId,revision:m.data.revision,actors:[{actorId:'character:mara.png',status:'present',evidence:body},{actorId:'character:elias.png',status:'present',evidence:body}]});if(options.messages[0].content.startsWith('Evaluate'))return response({answers:{compatible:{type:'noul',accepted:true}}});if(m.request.includes('Mara notices'))return response({actorId:'character:mara.png',text:'Mara looks at the still water.'});if(m.request.includes('Elias notices'))return response({actorId:'character:elias.png',text:'Elias checks the pier boards.'});throw Error('Unexpected ensemble request');}});
 const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.calls(),4);const candidate=result.recording.artifacts.find(a=>a.kind==='candidate').value;assert.ok(candidate.text.startsWith(body));assert.match(candidate.text,/Mara looks/);assert.match(candidate.text,/Elias checks/);assert.equal(f.saves(),0);f.controller.dispose();
});

test('mystery board saves evidence as an attributed claim and keeps hypotheses generated',async()=>{
 const body='The witness says the lighthouse was empty.';const f=unifiedRecipeHost(graph('mystery-evidence-board'),{documents:[doc('evidence-board',[])],request:async options=>{if(options.messages[0].content.startsWith('Extract'))return response(extracted(body,'witness-lighthouse','claim'));if(options.messages[0].content.startsWith('Expand'))return response([{id:'witness-lighthouse',details:'The witness may have missed a late arrival; investigate the time.'}]);return response({answers:{safe:{type:'noul',accepted:true}}});}});
 const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));const candidate=result.recording.artifacts.find(a=>a.kind==='candidate').value;assert.match(candidate.text,/claim/i);assert.match(candidate.text,/Generated proposal/);assert.equal(f.saves(),0);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['evidence-board'].content);assert.equal(saved.length,1);assert.equal(saved[0].classification,'claim');assert.equal(saved[0].additions,undefined);assert.equal(saved[0].evidence[0].quote,body);assert.equal(f.calls(),3);f.controller.dispose();
});

test('downtime checks the shared wagon locally and settles one agreed clock advance',async()=>{
 const f=unifiedRecipeHost(graph('downtime-factions'),{documents:[clock(),doc('faction-developments',[])],request:async options=>{const m=JSON.parse(options.messages[1].content),watch=m.request.includes('watch');return response({id:watch?'watch-patrol':'guild-notice',faction:watch?'harbor-watch':'market-guild',text:watch?'The watch moves its patrol.':'The guild posts a notice.',wagonsUsed:watch?1:0});}});
 const result=await f.generate('At the harbor, Mara finds a new notice and patrol.');assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.calls(),2);assert.equal(f.saves(),0);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));const savedClock=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['story-clock'].content);assert.equal(savedClock.absoluteMinute,880);assert.equal(savedClock.revision,2);assert.equal(JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['faction-developments'].content).length,2);const saves=f.saves();await f.controller.apply(result.reviewHandles[0]);assert.equal(f.saves(),saves);f.controller.dispose();
});

test('map stores only the accepted quoted discovery while retaining known records',async()=>{
 const body='Mara follows the pier path to the market.';const prior={id:'pier',label:'Pier',text:'Known landing place',classification:'observation',evidence:[]};const f=unifiedRecipeHost(graph('exploration-map'),{documents:[doc('known-map',[prior])],request:async options=>options.messages[0].content.startsWith('Extract')?response(extracted(body,'pier-to-market')):response({answers:{consistent:{type:'noul',accepted:true}}})});
 const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.saves(),0);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['known-map'].content);assert.equal(saved.length,2);assert.deepEqual(saved[0],prior);assert.equal(saved[1].classification,'observation');assert.equal(saved[1].evidence[0].quote,body);assert.equal(f.calls(),2);f.controller.dispose();
});

test('crafting debits deterministic costs once and separates proposed specialist additions',async()=>{
 const body='Mara completed the potion using two herbs and one vial.';const f=unifiedRecipeHost(graph('crafting-receipt'),{documents:[doc('crafting-state',{values:[{key:'herbs',value:3},{key:'vials',value:2},{key:'potions',value:0}],ledger:[]})],request:async options=>{const system=options.messages[0].content;if(system.startsWith('Extract'))return response(extracted(body,'potion'));if(system.startsWith('Expand'))return response([{id:'potion',details:'A proposed future trial is to test one drop on a stone.'}]);if(system.startsWith('Evaluate'))return response({answers:{actual:{type:'noul',accepted:true}}});return response([{eventType:'scene-action',actorId:'mara',position:{start:0,end:body.length},semantics:'actual'}]);}});
 const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.saves(),0);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));const saved=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user']['crafting-state'].content);assert.deepEqual(saved.values,[{key:'herbs',value:1},{key:'vials',value:1},{key:'potions',value:1}]);assert.equal(saved.ledger.length,3);assert.equal(f.calls(),4);const saves=f.saves();await f.controller.apply(result.reviewHandles[0]);assert.equal(f.saves(),saves);f.controller.dispose();
});

test('in-world packet keeps author, audience and chronology as proposed attributed documents',async()=>{
 const body='A ferry arrives at the harbor.';const f=unifiedRecipeHost(graph('story-documents'),{documents:[clock()],request:async options=>{if(options.messages[0].content.startsWith('Evaluate'))return response({answers:{consistent:{type:'noul',accepted:true}}});const m=JSON.parse(options.messages[1].content),id=m.request.includes('station-clerk')?'ticket':m.request.includes('harbor-watch')?'notice':'message';return response({id,author:id==='ticket'?'station-clerk':id==='notice'?'harbor-watch':'eyewitness',audience:id==='message'?'friend':'public',format:id,storyMinute:400,text:'The ferry has arrived, according to this author.'});}});
 const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));const candidate=result.recording.artifacts.find(a=>a.kind==='candidate').value;assert.ok(candidate.text.startsWith(body));assert.match(candidate.text,/station-clerk/);assert.match(candidate.text,/harbor-watch/);assert.match(candidate.text,/eyewitness/);assert.equal(f.calls(),4);assert.equal(f.saves(),0);f.controller.dispose();
});


test('downtime refuses invented negative resource usage before native generation or persistence',async()=>{
 const f=unifiedRecipeHost(graph('downtime-factions'),{documents:[clock(),doc('faction-developments',[])],request:async()=>response({id:'invalid',faction:'watch',text:'A malformed resource proposal',wagonsUsed:-1})});try{const result=await f.generate('This must never become an accepted development.');assert.equal(result.ok,false);assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);}finally{f.controller.dispose();}
});

test('insufficient crafting inputs cannot produce a free canonical potion even when the models claim completion',async()=>{
 const body='Mara completed the potion using two herbs and one vial.';const prior={values:[{key:'herbs',value:1},{key:'vials',value:0},{key:'potions',value:0}],ledger:[]};const f=unifiedRecipeHost(graph('crafting-receipt'),{documents:[doc('crafting-state',prior)],request:async options=>{const system=options.messages[0].content;if(system.startsWith('Extract'))return response(extracted(body,'potion'));if(system.startsWith('Expand'))return response([{id:'potion',details:'A proposed trial.'}]);if(system.startsWith('Evaluate'))return response({answers:{actual:{type:'noul',accepted:true}}});return response([{eventType:'scene-action',actorId:'mara',position:{start:0,end:body.length},semantics:'actual'}]);}});try{const result=await f.generate(body);assert.equal(result.ok,true,JSON.stringify(result.error));const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));assert.equal(f.saves(),0);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);assert.equal(result.recording.artifacts.some(a=>a.value?.operation==='state'&&a.value?.value?.ledger?.length),false);}finally{f.controller.dispose();}
});
