import assert from 'node:assert/strict';
import test from 'node:test';
const api=await import('../src/workflow/native-persistence.js?v=0.26.0').catch(()=>({}));
function fixture(options={}){let user='default-user',saves=0,requests=0;const packet={scope:{userId:user,chatId:'story'},targetId:'souls.json',format:'json',content:'[{"id":"s1"}]',revision:1,receipts:[]};const c={chatId:'story',characterId:0,groupId:null,chat:[],characters:[{name:'Mara',avatar:'Mara.png',chat:'Story-2'}],chatMetadata:{latticeDocuments:{[user]:{'souls.json':packet}}},getRequestHeaders:()=>({'Content-Type':'application/json','X-CSRF-Token':'PRIVATE_CSRF'}),saveMetadata:async()=>{saves++;await options.onSave?.();}};return {c,user:value=>{user=value;},counts:()=>({saves,requests}),create:()=>api.createNativePersistenceVerifier({getContext:()=>c,getUserId:()=>user,fetch:async(url,request)=>{requests++;assert.equal(url,'/api/chats/get');assert.deepEqual(JSON.parse(request.body),{ch_name:'Mara',file_name:'Story-2',avatar_url:'Mara.png'});await options.onFetch?.();return options.response??{ok:true,text:async()=>JSON.stringify([{chat_metadata:options.savedMetadata??c.chatMetadata}])};}})};}
const selection={kind:'document',targetId:'souls.json'};
test('void native save is confirmed only after the exact persisted document is independently reread',async()=>{assert.equal(typeof api.createNativePersistenceVerifier,'function');const f=fixture(),verifier=f.create();const result=await verifier.saveAndVerify(selection);assert.equal(result.ok,true);assert.equal(result.data.acknowledged,true);assert.deepEqual(f.counts(),{saves:1,requests:1});assert.doesNotMatch(JSON.stringify(result),/PRIVATE_CSRF|s1|Mara.png/);});
test('a mismatched or missing saved document stays unverified without automatic write retry',async()=>{const f=fixture({savedMetadata:{latticeDocuments:{'default-user':{'souls.json':{revision:0,content:'[]'}}}}}),result=await f.create().saveAndVerify(selection);assert.equal(result.ok,true);assert.equal(result.data.acknowledged,false);assert.equal(result.data.saveAttempted,true);assert.deepEqual(f.counts(),{saves:1,requests:1});});
test('scope change during native save prevents verification requests and cannot infer acknowledgement',async()=>{let f;f=fixture({onSave:()=>f.user('other-user')});const result=await f.create().saveAndVerify(selection);assert.equal(result.data.acknowledged,false);assert.equal(result.data.reasonCode,'STALE_PERSISTENCE_SCOPE');assert.deepEqual(f.counts(),{saves:1,requests:0});});
test('read-only reconciliation verifies exact current content without another native save',async()=>{const f=fixture();assert.equal((await f.create().verify(selection)).data.acknowledged,true);assert.deepEqual(f.counts(),{saves:0,requests:1});});
test('private paths, malformed selections and cancellation never authorize native save or network access',async()=>{const f=fixture(),verifier=f.create();let reads=0;assert.equal((await verifier.saveAndVerify({kind:'document',targetId:'../other-user'})).ok,false);assert.equal((await verifier.saveAndVerify(Object.defineProperty({},'kind',{enumerable:true,get(){reads++;return 'document';}}))).ok,false);const signal=new AbortController();signal.abort();assert.equal((await verifier.saveAndVerify(selection,{signal:signal.signal})).error.code,'CANCELLED');assert.equal(reads,0);assert.deepEqual(f.counts(),{saves:0,requests:0});});
test('host-header mutations revoke the saved read before fetch and response overflow stays bounded',async()=>{const f=fixture();f.c.getRequestHeaders=()=>{f.user('other-user');return {};};assert.equal((await f.create().verify(selection)).data.acknowledged,false);assert.equal(f.counts().requests,0);let cancelled=0;const g=fixture({response:{ok:true,body:{getReader:()=>({read:async()=>({done:false,value:new Uint8Array(33554433)}),cancel:async()=>{cancelled++;},releaseLock(){}})}}});const result=await g.create().saveAndVerify(selection);assert.equal(result.data.acknowledged,false);assert.equal(cancelled,1);assert.equal(g.counts().requests,1);});

test('saved content, metadata pointers and cancellation must remain current after awaited server work',async()=>{let f;f=fixture({onFetch:()=>{f.c.chatMetadata.latticeDocuments['default-user']['souls.json'].content='changed';}});const result=await f.create().saveAndVerify(selection);assert.equal(result.data.acknowledged,false);assert.equal(result.data.reasonCode,'STALE_PERSISTENCE_SCOPE');assert.deepEqual(f.counts(),{saves:1,requests:1});const controller=new AbortController();let g;g=fixture({onFetch:()=>controller.abort()});assert.equal((await g.create().verify(selection,{signal:controller.signal})).data.reasonCode,'CANCELLED');assert.equal(g.counts().saves,0);});
test('actor memory verification selects its exact store packet without exporting private records',async()=>{const f=fixture();f.c.chatMetadata.latticeIntrospection={native:{mara:{state:{privateFeeling:'Introspective thought'},receipts:[{key:'kiss1'}]}}};const result=await f.create().saveAndVerify({kind:'introspection',storeId:'native',actorId:'mara'});assert.equal(result.data.acknowledged,true);assert.doesNotMatch(JSON.stringify(result),/Introspective|kiss1|privateFeeling/);});

test('host context and native save-method exceptions remain controlled before saving or reading persistence',async()=>{for(const failure of ['context','method']){const f=fixture();let contexts=0,requests=0;if(failure==='method')Object.defineProperty(f.c,'saveMetadata',{get(){throw new Error('PRIVATE SAVE DIAGNOSTIC');}});const verifier=api.createNativePersistenceVerifier({getContext:()=>{if(failure==='context'&&++contexts===2)throw new Error('PRIVATE CONTEXT DIAGNOSTIC');return f.c;},getUserId:()=> 'default-user',fetch:async()=>{requests++;throw new Error('Unexpected read');}});const result=await verifier.saveAndVerify(selection);assert.equal(result.ok,true);assert.equal(result.data.acknowledged,false);assert.equal(result.data.saveAttempted,false);assert.equal(result.data.verificationAttempted,false);assert.equal(requests,0);assert.equal(f.counts().saves,0);assert.doesNotMatch(JSON.stringify(result),/PRIVATE|DIAGNOSTIC/);}});
