import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createNativeWorkflowController } from '../src/workflow/host.js?v=0.27.0';
import { createChatDocumentCatalog } from '../src/workflow/document-catalog.js?v=0.27.0';
import { operationDefaults } from '../src/workflow/catalog.js?v=0.27.0';
const nextTurn = () => new Promise(resolve => setTimeout(resolve, 10));
function unifiedGraph({ guidance = false, revise = true } = {}) {
    const nodes = { send: { id: 'send', type: 'workflow', operation: 'on-send' }, generate: { id: 'generate', type: 'workflow', operation: 'generate-reply' }, review: { id: 'review', type: 'workflow', operation: 'review-publish' } };
    const wires = { activation: { id: 'activation', route: 'wire', from: 'send', fromPort: 'activation', to: 'generate', toPort: 'activation' } };
    if (revise) nodes.revise = { id: 'revise', type: 'workflow', operation: 'revise-draft', scope: 'whole', instructions: 'Tighten prose.' };
    wires.reply = { id: 'reply', route: 'wire', from: 'generate', fromPort: 'draft', to: revise ? 'revise' : 'review', toPort: 'draft' };
    if (revise) wires.review = { id: 'review', route: 'wire', from: 'revise', fromPort: 'out', to: 'review', toPort: 'draft' };
    if (guidance) { nodes.guide = { id: 'guide', type: 'workflow', operation: 'compose', outputKind: 'guidance', sections: [{ name: 'Style', text: 'Use vivid prose.' }] }; wires.guidance = { id: 'guidance', route: 'wire', from: 'guide', fromPort: 'out', to: 'generate', toPort: 'guidance' }; }
    return { id: 'unified', name: 'Unified test', schema: 3, runtime: 2, mode: 'native-unified', nodes, wires, portals: {}, definitions: {} };
}
function nativeFixture(graph = unifiedGraph(), options = {}) {
    const listeners = new Map(), events = [], results = [];
    const c = { chatId: 'story', characterId: 0, groupId: null, characters: [{ data: { name: 'Mara' } }], chat: [{ mes: 'I open the door.', is_user: true, extra: {} }], extensionPrompts: {}, eventTypes: Object.fromEntries(['GENERATION_STARTED', 'GENERATION_STOPPED', 'GENERATION_ENDED', 'MESSAGE_RECEIVED', 'MESSAGE_SENT', 'CHAT_CHANGED', 'MESSAGE_EDITED', 'MESSAGE_UPDATED', 'MESSAGE_DELETED', 'MESSAGE_SWIPED', 'MESSAGE_SWIPE_DELETED'].map(name => [name, name])) };
    c.eventSource = { on(name, fn) { const bucket = listeners.get(name) ?? []; bucket.push(fn); listeners.set(name, bucket); }, removeListener(name, fn) { listeners.set(name, (listeners.get(name) ?? []).filter(value => value !== fn)); }, async emit(name, ...args) { for (const listener of listeners.get(name) ?? []) await listener(...args); } };
    c.setExtensionPrompt = (key, value) => { c.extensionPrompts[key] = { value }; };
    c.saveChat = async () => {}; c.updateMessageBlock = async () => {}; c.swipe = { refresh: async () => {} };
    let busy = false, user = 'default-user', requests = 0;
    const controller = createNativeWorkflowController({ ...options.ports, context: () => c, getGraph: phase => phase === 'unified' ? graph : undefined, isEnabled: () => true, userId: () => user, isBusy: () => busy, countTokens: options.countTokens ?? (async text => ({ tokens: Math.ceil(text.length / 4) })), resolveBinding: options.resolveBinding ?? (() => ({ ok: true, data: { profileId: 'fixed', model: 'test' } })), request: options.request ?? (async () => { requests++; return { ok: true, data: { text: 'Revised reply.', finish: 'stop' } }; }), onEvent: event => events.push(event), onResult: result => results.push(result), syncMesToSwipe(index) { const m = c.chat[index]; m.swipes[m.swipe_id] = m.mes; return true; }, syncSwipeToMes(index, swipeId) { const m = c.chat[index]; m.swipe_id = swipeId; m.mes = m.swipes[swipeId]; Object.assign(m, structuredClone(m.swipe_info[swipeId])); return true; } });
    controller.subscribe();
    return { c, controller, events, results, setBusy(value) { busy = value; }, setUser(value) { user = value; }, requests: () => requests, async start(type = 'normal') { busy = true; await c.eventSource.emit('GENERATION_STARTED', type, {}, false); return controller.beforeGenerate(c.chat.map(message => ({ ...message })), 8192, options.abort ?? (() => {}), type); } };
}
function addReply(f, { normalized = true, text = 'Native reply.' } = {}) {
    const now = new Date().toISOString(), m = { mes: text, is_user: false, extra: {}, gen_started: now, gen_finished: now };
    if (normalized) Object.assign(m, { swipe_id: 0, swipes: [text], swipe_info: [{ gen_started: now, gen_finished: now, extra: {} }] });
    f.c.chat.push(m); return m;
}
async function settled(f) { for (let tries = 0; tries < 30 && !f.results.length; tries++) await nextTurn(); assert.equal(f.results.length, 1, 'Owned continuation must settle promptly'); return f.results[0]; }


import {normalizeOccurrences,confirmOccurrences,resolveItemHolders} from '../src/workflow/operations/event-data.js?v=0.27.0';
const playerText='Mara uses her broken wand.';
function playerEvents(){const source={sourceId:'player-turn',revision:'1',sceneId:'story',watch:'player-message',text:playerText,visibility:'public'};const candidates=normalizeOccurrences(source,[{eventType:'item-used',actorId:'mara',itemId:'wand',position:{start:0,end:playerText.length},semantics:'actual'}],{actorIds:['mara'],itemIds:['wand']}).data.events;return resolveItemHolders({wand:'mara'},confirmOccurrences(candidates,[{eventId:candidates[0].eventId,accepted:true}]).data.events).data.events;}
function outcomeGraph(wild=false){const g=unifiedGraph({revise:false});const node=(id,operation,extra={})=>g.nodes[id]={id,type:'workflow',...operationDefaults(operation),...extra};const wire=(id,from,fromPort,to,toPort)=>g.wires[id]={id,route:'wire',from,fromPort,to,toPort};function data(id,value){node(id+'text','text',{text:JSON.stringify(value)});node(id,'json-decode');wire(id+'parse',id+'text','out',id,'in');}
 data('events',playerEvents());data('library',{libraryId:'wand',revision:'1',itemId:'wand',effects:[wild?{id:'wild',kind:'generate',weight:1}:{id:'sparks',kind:'fixed',weight:1,description:'Blue sparks appear.'}]});node('pick','random-pick',{ledgerId:'outcomes'});wire('events','events','out','pick','events');wire('library','library','out','pick','library');node('commit','commit-outcomes',{targetId:'outcomes'});
 if(wild){node('first','select-fields',{fields:['schemaVersion','recordType','outcomeId','event','library','libraryFingerprint','selection','draw','effect','status','acceptance','rerollId','author','novelty'].map(name=>({name,path:['0',name],required:false}))});wire('first','pick','out','first','in');node('author','effect-author');wire('author','first','out','author','in');data('novelty',{accepted:true});node('resolved','stage-outcome');wire('stage','author','out','resolved','in');wire('novelty','novelty','out','resolved','novelty');wire('commit','resolved','out','commit','outcomes');}
 else wire('commit','pick','out','commit','outcomes');return g;}
function outcomeFixture(wild=false){let catalog,draws=0,saves=0,authors=0;const f=nativeFixture(outcomeGraph(wild),{request:async()=>{authors++;if(authors===1)return {ok:false,error:{code:'REQUEST_FAILED',message:'Author unavailable'}};return {ok:true,data:{finish:'stop',text:JSON.stringify({id:'moths',description:'Paper moths circle Mara.',spellOutcome:'replaced',duration:'One minute',consequence:'The target remains unharmed.'})}};},ports:{random:()=>{draws++;return .4;},documentCatalog:{capture:()=>catalog.capture()},persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}}}});f.c.chat[0].mes=playerText;f.c.chatMetadata={};catalog=createChatDocumentCatalog({getContext:()=>f.c,getUserId:()=> 'default-user'});catalog.define({targetId:'outcomes',name:'Outcomes',format:'json',content:'[]',visibility:{kind:'public'}});return {...f,catalog,draws:()=>draws,saves:()=>saves,authors:()=>authors,async finish(){addReply(f);await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'normal');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);for(let tries=0;tries<30&&f.results.at(-1)?.reviewHandles.length!==1;tries++)await nextTurn();return f.results.at(-1);}};}
test('actual native Random Pick and Outcome Commit persist one accepted draw only after final review',async()=>{const f=outcomeFixture();assert.equal((await f.start()).ok,true);const result=await f.finish();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.draws(),1);assert.equal(f.saves(),0);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');const ledger=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].outcomes.content);assert.equal(ledger.length,1);assert.equal(ledger[0].acceptance,'accepted');assert.equal(f.saves(),1);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),1);});
test('actual failed wild author retry retains the exact draw after native Generation End and reuses successful invention',async()=>{const f=outcomeFixture(true);const failed=await f.start();assert.equal(failed.ok,false);assert.equal(f.draws(),1);assert.equal(f.authors(),1);f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',1);const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));const result=await f.finish();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.draws(),1);assert.equal(f.authors(),2);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.saves(),1);assert.equal(JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].outcomes.content)[0].effect.id,'moths');});
test('editing the captured player message revokes pending random evidence before acceptance',async()=>{const f=outcomeFixture();assert.equal((await f.start()).ok,true);const result=await f.finish();f.c.chat[0].mes='Mara puts the wand away.';const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,false);assert.equal(f.saves(),0);assert.equal(f.c.chat[1].swipes.length,1);});
test('native revised final prose can reextract canonical file evidence at changed offsets',async()=>{const graph=unifiedGraph({revise:true});const node=(id,operation,extra={})=>graph.nodes[id]={id,type:'workflow',...operationDefaults(operation),...extra};const wire=(id,from,fromPort,to,toPort)=>graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};function data(id,value){node(id+'text','text',{text:JSON.stringify(value)});node(id,'json-decode');wire(id+'parse',id+'text','out',id,'in');}data('scope',{sourceId:'final-scene',revision:'1',sceneId:'story',visibility:'public'});data('entities',{actorIds:['mara'],itemIds:['wand']});node('source','draft-event-source');wire('source-draft','revise','out','source','in');wire('source-scope','scope','out','source','scope');node('mentions','item-mention-trigger',{aliases:['wand'],itemId:'wand',actorId:'mara',watch:'draft'});wire('mentions-source','source','out','mentions','source');wire('mentions-entities','entities','out','mentions','entities');node('read','read-file',{targetId:'events'});node('write','write-file',{mode:'add-unique',key:'eventId'});wire('reference','read','reference','write','reference');wire('records','mentions','out','write','records');wire('evidence','mentions','out','write','evidence');let catalog,saves=0;const f=nativeFixture(graph,{request:async()=>({ok:true,data:{text:'After a long pause, Mara raises the wand.',finish:'stop'}}),ports:{documentCatalog:{capture:()=>catalog.capture()},persistenceVerifier:{saveAndVerify:async()=>{saves++;return {ok:true,data:{acknowledged:true}};}}}});f.c.chatMetadata={};catalog=createChatDocumentCatalog({getContext:()=>f.c,getUserId:()=> 'default-user'});catalog.define({targetId:'events',name:'Events',format:'json',content:'[]',visibility:{kind:'public'}});assert.equal((await f.start()).ok,true);addReply(f,{text:'The wand glows.'});await f.c.eventSource.emit('MESSAGE_RECEIVED',1,'normal');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',2);const result=await settled(f);assert.equal(result.ok,true,JSON.stringify(result.error));const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(saves,1);const events=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].events.content);assert.equal(events[0].evidence.position.start,36);assert.equal(events[0].evidence.text,'wand');assert.equal(f.c.chat[1].swipes[0],'The wand glows.');});

test('later identical player turns produce separate accepted durable outcome identities',async()=>{const f=outcomeFixture();assert.equal((await f.start()).ok,true);let result=await f.finish();assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);f.c.chat.push({mes:playerText,is_user:true,extra:{},send_date:'second-user-turn'});await f.c.eventSource.emit('MESSAGE_SENT',2);const resultCount=f.results.length;assert.equal((await f.start()).ok,true);addReply(f);await f.c.eventSource.emit('MESSAGE_RECEIVED',3,'normal');f.setBusy(false);await f.c.eventSource.emit('GENERATION_ENDED',4);for(let tries=0;tries<30&&f.results.length===resultCount;tries++)await nextTurn();result=f.results.at(-1);assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);const ledger=JSON.parse(f.c.chatMetadata.latticeDocuments['default-user'].outcomes.content);assert.equal(ledger.length,2);assert.notEqual(ledger[0].outcomeId,ledger[1].outcomeId);assert.notEqual(ledger[0].event.source.sourceId,ledger[1].event.source.sourceId);assert.equal(f.draws(),2);});
