import assert from 'node:assert/strict';
import {test} from 'node:test';
import {registerHooks} from 'node:module';
import {createNativeWorkflowController} from '../src/workflow/host.js?v=0.26.0';
import {createChatDocumentCatalog} from '../src/workflow/document-catalog.js?v=0.26.0';
import {operationDefaults} from '../src/workflow/catalog.js?v=0.26.0';
const pause=()=>new Promise(r=>setTimeout(r,5));
const mara='character:mara.png',elias='character:elias.png';
function graphFor(mode='direction'){
 const nodes={},wires={};const node=(id,operation,settings={})=>nodes[id]={id,type:'workflow',...operationDefaults(operation),...settings};const wire=(id,from,fromPort,to,toPort)=>wires[id]={id,route:'wire',from,fromPort,to,toPort};
 node('send','on-send');node('generate','generate-reply',{budgetTokens:4096});node('review','review-publish');wire('send','send','activation','generate','activation');wire('review','generate','draft','review','draft');
 node('scene','scene-context',{visibilityMode:'public',includeCharacter:false});node('castPrompt','text',{text:'Return actual participating actors with context.source identity and exact quoted chat evidence.'});node('cast','model-call',{outputKind:'data'});wire('castPrompt','castPrompt','out','cast','prompt');wire('castContext','scene','out','cast','context');
 for(const [id,actorId]of [['mara',mara],['elias',elias]]){node(id,'scene-presence',{actorId});wire(id+'Presence','cast','out',id,'in');}
 if(mode==='direction'){
  node('direction','character-direction',{actorId:mara,systemPrompt:'Mara alone should hesitate and consider the sea.'});wire('present','mara','out','direction','presence');wire('guidance','direction','out','generate','guidance');
 }else{
  delete nodes.scene;delete wires.castContext;nodes.cast.phase='post';nodes.castPrompt.phase='post';nodes.mara.phase='post';nodes.elias.phase='post';
  node('scopeText','text',{text:JSON.stringify({sourceId:'authored',revision:'authored',sceneId:'Story-2',visibility:'public'}),phase:'post'});node('scope','json-decode',{phase:'post'});node('source','draft-event-source');wire('scopeText','scopeText','out','scope','in');wire('draft','generate','draft','source','in');wire('scope','scope','out','source','scope');wire('castSource','source','out','cast','data');
  for(const [id,actorId]of [['mara',mara],['elias',elias]]){
   node(id+'Context','actor-context',{actorId,phase:'post'});wire(id+'ContextPresence',id,'out',id+'Context','presence');
   node(id+'Read','read-file',{targetId:id+'.md',actorScope:'presence',actorId,phase:'post'});wire(id+'ReadPresence',id,'out',id+'Read','presence');
   node(id+'Prompt','text',{text:'Reflect privately for '+actorId+'.',phase:'post'});node(id+'Reflect','model-call',{instructions:'Reflect privately for '+actorId+'.',phase:'post'});wire(id+'ReflectPrompt',id+'Read','text',id+'Reflect','prompt');wire(id+'ReflectData',id+'Read','document',id+'Reflect','data');wire(id+'ActorContext',id+'Context','out',id+'Reflect','context');
   node(id+'Write','write-file',{actorScope:'presence',actorId,mode:'append'});wire(id+'WritePresence',id,'out',id+'Write','presence');wire(id+'Reference',id+'Read','reference',id+'Write','reference');wire(id+'Reflection',id+'Reflect','out',id+'Write','text');
  }
 }
 return {id:'actor-story',name:'Actor story',schema:3,runtime:2,mode:'native-unified',nodes,wires,definitions:{},portals:{}};
}
function fixture(mode='direction',options={}){
 const graph=graphFor(mode),listeners=new Map(),results=[],requests=[];let busy=false,user='default-user';
 const c={chatId:'Story-2',characterId:0,groupId:null,characters:[{avatar:'mara.png',data:{name:'Mara',description:'PRIVATE SEA memory',visibility:{kind:'actor-private',actorId:mara}}},{avatar:'elias.png',data:{name:'Elias',description:'PRIVATE FIRE memory',visibility:{kind:'actor-private',actorId:elias}}}],chat:[{mes:options.chatText??'Mara and Elias meet by the door.',is_user:true,extra:{}}],chatMetadata:{},extensionPrompts:{},eventTypes:Object.fromEntries(['GENERATION_STARTED','GENERATION_STOPPED','GENERATION_ENDED','MESSAGE_RECEIVED','MESSAGE_SENT','CHAT_CHANGED','MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED','MESSAGE_SWIPED','MESSAGE_SWIPE_DELETED'].map(n=>[n,n]))};
 c.eventSource={on(name,fn){const bucket=listeners.get(name)??[];bucket.push(fn);listeners.set(name,bucket);},removeListener(name,fn){listeners.set(name,(listeners.get(name)??[]).filter(v=>v!==fn));},async emit(name,...args){for(const fn of listeners.get(name)??[])await fn(...args);}};c.setExtensionPrompt=(key,value)=>{c.extensionPrompts[key]={value};};c.saveChat=async()=>{};c.updateMessageBlock=async()=>{};c.swipe={refresh:async()=>{}};
 const catalog=createChatDocumentCatalog({getContext:()=>c,getUserId:()=>user});for(const [id,actorId,content]of [['mara',mara,'PRIVATE SEA reflection'],['elias',elias,'PRIVATE FIRE reflection']])assert.equal(catalog.define({targetId:id+'.md',name:id,format:'markdown',content,visibility:{kind:'actor-private',actorId}}).ok,true);
 const controller=(options.controllerFactory??createNativeWorkflowController)({context:()=>{options.onContext?.(c);return c;},getGraph:phase=>phase==='unified'?graph:undefined,isEnabled:()=>true,userId:()=>user,isBusy:()=>busy,documentCatalog:catalog,countTokens:async text=>{await options.onCount?.(text,c);return {tokens:Math.ceil(text.length/4)};},resolveBinding:()=>({ok:true,data:{profileId:'fixed',model:'test'}}),request:async request=>{requests.push(request);const material=JSON.parse(request.messages.at(-1).content);await options.onRequest?.(request,material,c);const override=options.modelOutput?.(material,c);if(override!==undefined)return {ok:true,data:{text:typeof override==='string'?override:JSON.stringify(override),finish:'stop'}};if(material.context?.source?.actorId===undefined&&material.context?.source||material.data?.watch==='draft'){const s=material.context?.source??material.data;return {ok:true,data:{text:JSON.stringify({sceneId:s.sceneId,sourceId:s.sourceId,revision:s.revision,actors:[{actorId:mara,status:'present',evidence:s.watch==='draft'?s.text:c.chat[0].mes},{actorId:elias,status:'present',evidence:s.watch==='draft'?'Mara and Elias kiss by the door.':'Mara and Elias meet by the door.'}]}),finish:'stop'}};}return {ok:true,data:{text:material.request?.includes('FIRE')?'Elias considers the fire.':'Mara considers the sea.',finish:'stop'}};},persistenceVerifier:{saveAndVerify:async selection=>{await options.onVerify?.(selection,c);return {ok:true,data:{acknowledged:true}};}},onEvent:options.onEvent,onResult:value=>results.push(value),syncMesToSwipe(index){const m=c.chat[index];m.swipes[m.swipe_id]=m.mes;return true;},syncSwipeToMes(index,swipeId){const m=c.chat[index];m.swipe_id=swipeId;m.mes=m.swipes[swipeId];Object.assign(m,structuredClone(m.swipe_info[swipeId]));return true;}});controller.subscribe();
 return {c,graph,controller,catalog,requests,results,setUser:v=>user=v,async start(){busy=true;await c.eventSource.emit('GENERATION_STARTED','normal',{},false);return controller.beforeGenerate(c.chat.map(m=>({...m})),8192,()=>{},'normal');},async complete(){const now=new Date().toISOString(),reply=options.replyText??'Mara and Elias kiss by the door.';c.chat.push({mes:reply,is_user:false,extra:{},gen_started:now,gen_finished:now,swipe_id:0,swipes:[reply],swipe_info:[{gen_started:now,gen_finished:now,extra:{}}]});await c.eventSource.emit('MESSAGE_RECEIVED',c.chat.length-1,'normal');busy=false;await c.eventSource.emit('GENERATION_ENDED',c.chat.length);for(let i=0;i<100&&!results.length;i++)await pause();return results.at(-1);}};
}
test('actual native Character Direction scopes a separate system prompt to the participating selected actor',async()=>{
 const f=fixture(),ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,2);const direction=JSON.stringify(f.requests[1].messages);assert.ok(direction.includes('PRIVATE SEA'));assert.equal(direction.includes('PRIVATE FIRE'),false);assert.ok(f.requests[1].messages[0].content.includes('Mara alone'));assert.ok(Object.values(f.c.extensionPrompts).some(p=>p.value==='Mara considers the sea.'));const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);f.controller.dispose();
});
test('actual native paired actor file/model legs isolate private material and settle only after acceptance',async()=>{
 const f=fixture('files'),ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,0);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.requests.length,3);const calls=f.requests.slice(1).map(r=>JSON.stringify(r.messages));assert.ok(calls.some(s=>s.includes('PRIVATE SEA')));assert.ok(calls.some(s=>s.includes('PRIVATE FIRE')));assert.equal(calls.some(s=>s.includes('PRIVATE SEA')&&s.includes('PRIVATE FIRE')),false);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled');const saved=f.c.chatMetadata.latticeDocuments['default-user'];assert.ok(saved['mara.md'].content.includes('Mara considers the sea.'));assert.equal(saved['mara.md'].content.includes('FIRE'),false);assert.ok(saved['elias.md'].content.includes('Elias considers the fire.'));assert.equal(saved['elias.md'].content.includes('SEA'),false);assert.equal(f.c.chat[1].mes.includes('PRIVATE'),false);f.controller.dispose();
});
test('a private-card mutation during the actor request tokenizer holds before transmission',async()=>{
 const f=fixture('direction',{onCount(text,c){if(text.includes('PRIVATE SEA'))c.characters[0].data.description='Changed private source.';}}),ready=await f.start();assert.equal(ready.ok,false);assert.equal(ready.error.code,'ACTOR_CONTEXT_CHANGED');assert.equal(f.requests.length,1);assert.equal(Object.values(f.c.extensionPrompts).some(p=>p.value),false);f.controller.dispose();
});

test('paired private file consequences preserve confirmed first write across second conflict and retry without model calls',async()=>{
 let conflicted=false;const f=fixture('files',{onVerify(selection,c){if(selection.kind==='document'&&selection.targetId==='mara.md'&&!conflicted){conflicted=true;c.chatMetadata.latticeDocuments['default-user']['elias.md']={targetId:'elias.md',revision:1,format:'markdown',content:'Foreign confirmed edit',receipts:[]};}}});
 assert.equal((await f.start()).ok,true);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'partial');const saved=structuredClone(f.c.chatMetadata.latticeDocuments['default-user']['mara.md']),calls=f.requests.length;
 assert.ok(saved.content.includes('Mara considers the sea.'));assert.equal(f.c.chatMetadata.latticeDocuments['default-user']['elias.md'].content,'Foreign confirmed edit');const retried=await f.controller.apply(result.reviewHandles[0]);assert.equal(retried.ok,true,JSON.stringify(retried.error));assert.equal(retried.settlement.status,'partial');assert.equal(f.requests.length,calls);assert.deepEqual(f.c.chatMetadata.latticeDocuments['default-user']['mara.md'],saved);assert.equal(f.c.chat[1].swipes.length,2);f.controller.dispose();
});
test('native actor private-model response is discarded if its captured card changes during the request',async()=>{
 let changed=false;const f=fixture('files',{onRequest(request,material,c){if(!changed&&material.request?.includes('PRIVATE SEA')){changed=true;c.characters[0].data.description='Foreign private card edit';}}});assert.equal((await f.start()).ok,true);const result=await f.complete();assert.equal(result.ok,false);assert.equal(f.c.chatMetadata.latticeDocuments,undefined);assert.equal(result.reviewHandles.length,0);f.controller.dispose();
});
function addMemoryFlow(f){
 delete f.graph.nodes.direction;delete f.graph.wires.present;delete f.graph.wires.guidance;f.graph.nodes.cast.phase='post';f.graph.nodes.mara.phase='post';f.graph.nodes.elias.phase='post';delete f.graph.nodes.scene;delete f.graph.wires.castContext;
 const node=(id,operation,settings={})=>f.graph.nodes[id]={id,type:'workflow',...operationDefaults(operation),...settings},wire=(id,from,fromPort,to,toPort)=>f.graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};
 node('scopeText','text',{text:JSON.stringify({sourceId:'authored',revision:'authored',sceneId:'Story-2',visibility:'public'})});node('scope','json-decode');node('source','draft-event-source');wire('scopeText','scopeText','out','scope','in');wire('scope','scope','out','source','scope');wire('draftSource','generate','draft','source','in');wire('castSource','source','out','cast','data');node('entitiesText','text',{text:JSON.stringify({actorIds:[mara,elias],itemIds:['sword']})});node('entities','json-decode');wire('entities','entitiesText','out','entities','in');
 node('mention','item-mention-trigger',{actorId:mara,itemId:'sword',aliases:['Sword'],watch:'draft'});wire('source','source','out','mention','source');wire('entitySource','entities','out','mention','entities');
 node('holdersText','text',{text:JSON.stringify({sword:mara})});node('holders','json-decode');wire('holders','holdersText','out','holders','in');node('holder','current-holder');wire('holderState','holders','out','holder','holders');wire('holderEvent','mention','out','holder','events');
 node('pick','collection',{mode:'lookup',fieldPath:['holderId'],value:mara});wire('pick','holder','events','pick','in');node('single','select-fields',{fields:['schemaVersion','recordType','eventId','eventType','sceneId','source','actorId','itemId','position','evidence','semantics','status','acceptance','confirmation','holderId'].map(name=>({name,path:['value',name]}))});wire('single','pick','out','single','in');
 node('memory','prompted-memory',{actorId:mara,phase:'post',prompt:'When Sword is mentioned, recall the holder’s existing memory.'});wire('memoryEvent','single','out','memory','event');wire('memoryPresence','mara','out','memory','presence');node('memoryRead','read-file',{targetId:'triggered.json',phase:'post'});node('memoryWrite','write-file',{mode:'add'});wire('memoryReference','memoryRead','reference','memoryWrite','reference');wire('memoryRecord','memory','out','memoryWrite','records');assert.equal(f.catalog.define({targetId:'triggered.json',name:'Triggered memories',format:'json',content:'[]',visibility:{kind:'actor-private',actorId:mara}}).ok,true);
}
test('actual native Prompted Memory triggers on the ordered current holder and reads only authorized existing memories',async()=>{
 const f=fixture('direction',{replyText:'Mara and Elias kiss beside Sword.',modelOutput:material=>material.mode==='recall'?{kind:'recalled',memoryId:'mara-e1',reflection:'Mara recalls the sea.'}:undefined});addMemoryFlow(f);
 const {makeRecord}=await import('../src/workflow/introspection/contracts.js?v=0.26.0');const records={};for(const [actorId,id,text]of [[mara,'mara-e1','PRIVATE SEA episode'],[elias,'elias-e1','PRIVATE FIRE episode']]){const result=makeRecord('actor-state',{scope:{chatId:'Story-2',actorId},store:{id:'native-chat',version:0}},{episodes:[{id,text,classification:'observation',sourceRefs:[]}]},[]);assert.equal(result.ok,true);records[actorId]={state:result.data,receipts:[]};}f.c.chatMetadata.latticeIntrospection={'native-chat':records};
 const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(f.requests.length,0);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.requests.length,2);const memory=JSON.parse(f.requests[1].messages.at(-1).content);assert.equal(memory.event.holderId,mara);assert.equal(memory.memories[0].memoryId,'mara-e1');assert.ok(JSON.stringify(memory).includes('PRIVATE SEA'));assert.equal(JSON.stringify(memory).includes('PRIVATE FIRE'),false);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.deepEqual(f.c.chatMetadata.latticeIntrospection['native-chat'],records);f.controller.dispose();
});

test('actual host verifies actor presence after all private Data admission callbacks before transport',async()=>{
 const hostURL=new URL('../src/workflow/host.js?actor-data-admission-race',import.meta.url).href,recallURL=new URL('../src/workflow/native-recall.js',import.meta.url).href;
 const state={current:true,armed:false,revoked:false};globalThis.latticeActorDataAdmissionRace=state;
 // Keep the real Recall producer and source checks; this adapter can only revoke an otherwise genuine presence.
 const adapter='data:text/javascript,'+encodeURIComponent(`import {createNativeRecallController as real} from ${JSON.stringify(recallURL)};export const createNativeRecallController=ports=>{const service=real(ports);return Object.freeze({...service,authorizePresence(...args){return globalThis.latticeActorDataAdmissionRace.current?service.authorizePresence(...args):{ok:false,error:{code:'RECALL_PRESENCE_UNVERIFIED',message:'Presence authority revoked during Data admission.'}};}});};`);
 const hook=registerHooks({resolve(specifier,context,next){return context.parentURL===hostURL&&specifier.startsWith('./native-recall.js')?{url:adapter,shortCircuit:true}:next(specifier,context);}});
 let f;
 try{
  const {createNativeWorkflowController:controllerFactory}=await import(hostURL);
  f=fixture('direction',{controllerFactory,onEvent(event){if(event.type==='request-start'&&event.address.nodeId==='direction')state.armed=true;},onContext(){const priorLimit=Error.stackTraceLimit;Error.stackTraceLimit=40;const stack=new Error().stack;Error.stackTraceLimit=priorLimit;if(state.armed&&!state.revoked&&stack.includes('native-actor-context.js')&&stack.includes('authorizeModelInputs')&&stack.includes('authorizeModelScope')&&!stack.includes('authorizeEventInputs')){state.current=false;state.revoked=true;}}});
  f.graph.nodes.privateData={id:'privateData',type:'workflow',...operationDefaults('read-file'),targetId:'mara.md'};
  f.graph.wires.privateData={id:'privateData',route:'wire',from:'privateData',fromPort:'document',to:'direction',toPort:'data'};
  const result=await f.start();assert.equal(state.revoked,true,'The private Data authorization callback must revoke genuine presence');assert.equal(result.ok,false);assert.equal(result.error.code,'ACTOR_CONTEXT_CHANGED');assert.equal(f.requests.length,1,'Only the public cast request may reach the adapter');assert.equal(f.requests.some(request=>JSON.stringify(request.messages).includes('PRIVATE SEA')),false);assert.equal(Object.values(f.c.extensionPrompts).some(prompt=>prompt.value),false);
 }finally{f?.controller.dispose();hook.deregister();delete globalThis.latticeActorDataAdmissionRace;}
});
