import assert from 'node:assert/strict';
import {test} from 'node:test';
import {createNativeWorkflowController} from '../src/workflow/host.js?v=0.26.0';
import {createChatDocumentCatalog} from '../src/workflow/document-catalog.js?v=0.26.0';
import {operationDefaults} from '../src/workflow/catalog.js?v=0.26.0';
const pause=()=>new Promise(resolve=>setTimeout(resolve,10));
export function recallGraph(options={}) {
 const nodes={},wires={};const node=(id,operation,settings={})=>nodes[id]={id,type:'workflow',...operationDefaults(operation),...settings};
 const wire=(id,from,fromPort,to,toPort)=>wires[id]={id,route:'wire',from,fromPort,to,toPort};
 node('send','on-send');node('generate','generate-reply',{budgetTokens:4096});node('review','review-publish');wire('activation','send','activation','generate','activation');wire('draft','generate','draft','review','draft');
 node('hotkey','hotkey-arm',{actorId:'character:0',memorySetId:'moments',consumeOn:options.consumeOn??'accepted',target:options.target??'both',uses:options.uses??'next-match'});
 node('scene','scene-context',{includeCharacter:false,visibilityMode:'public'});node('prompt','text',{text:'Return actual participating actors with sceneId, sourceId, revision copied from context.source and evidence quoted from chat.'});node('cast','model-call',{outputKind:'data'});node('presence','scene-presence',{actorId:'character:0'});
 wire('prompt','prompt','out','cast','prompt');wire('context','scene','out','cast','context');wire('cast','cast','out','presence','in');
 node('read','read-file',{targetId:'moments.json'});node('decode','json-decode');wire('json','read','text','decode','in');
 node('recall','recall',{actorId:'character:0',memorySetId:'moments',activation:options.activation??'armed'});wire('records','decode','out','recall','records');wire('presence','presence','out','recall','presence');wire('guidance','recall','out','generate','guidance');
 return {id:'recall-story',name:'Recall story',schema:3,runtime:2,mode:'native-unified',nodes,wires,portals:{},definitions:{}};
}
export function fixture(options={}) {
 const graph=recallGraph(options),listeners=new Map(),results=[],registrations=[];let busy=false,user='default-user',requests=0;
 const c={chatId:'story',characterId:0,groupId:null,characters:[{data:{name:'Mara'}}],chat:[{mes:'Mara waits at the door.',is_user:true,extra:{}}],chatMetadata:{},extensionPrompts:{},eventTypes:Object.fromEntries(['GENERATION_STARTED','GENERATION_STOPPED','GENERATION_ENDED','MESSAGE_RECEIVED','MESSAGE_SENT','CHAT_CHANGED','MESSAGE_EDITED','MESSAGE_UPDATED','MESSAGE_DELETED','MESSAGE_SWIPED','MESSAGE_SWIPE_DELETED'].map(name=>[name,name]))};
 c.eventSource={on(name,fn){const bucket=listeners.get(name)??[];bucket.push(fn);listeners.set(name,bucket);},removeListener(name,fn){listeners.set(name,(listeners.get(name)??[]).filter(value=>value!==fn));},async emit(name,...args){for(const fn of listeners.get(name)??[])await fn(...args);}};
 c.setExtensionPrompt=(key,value)=>{c.extensionPrompts[key]={value};options.onPrompt?.(value,c);};c.saveChat=async()=>{};c.updateMessageBlock=async()=>{};c.swipe={refresh:async()=>{}};
 const catalog=createChatDocumentCatalog({getContext:()=>c,getUserId:()=>user});assert.equal(catalog.define({targetId:'moments.json',name:'Moments',format:'json',content:JSON.stringify([{id:'m1',actorId:'character:0',text:'PRIVATE harbor memory',tags:['harbor']}]),visibility:{kind:'actor-private',actorId:'character:0'}}).ok,true);
 const controller=createNativeWorkflowController({context:()=>c,getGraph:phase=>phase==='unified'?graph:undefined,isEnabled:()=>true,userId:()=>user,isBusy:()=>busy,documentCatalog:catalog,countTokens:async text=>{await options.onCount?.(text,c);return {tokens:Math.ceil(text.length/4)};},resolveBinding:()=>({ok:true,data:{profileId:'fixed',model:'test'}}),request:async request=>{requests++;const material=JSON.parse(request.messages.at(-1).content);await options.onModel?.(material,c);const s=material.context?.source??material.data;const output=options.modelOutput?.(material)??{sceneId:s.sceneId??'story',sourceId:s.sourceId??'manual-source',revision:s.revision??'manual-revision',actors:[{actorId:'character:0',status:'present',evidence:'Mara waits at the door.'}]};return {ok:true,data:{text:JSON.stringify(output),finish:'stop'}};},registerRecallHotkey:entry=>{const captured={...entry,disposed:false};registrations.push(captured);return {ok:true,data:{dispose:()=>{captured.disposed=true;}}};},persistenceVerifier:{saveAndVerify:async()=>({ok:true,data:{acknowledged:true}})},onResult:value=>results.push(value),syncMesToSwipe(index){const m=c.chat[index];m.swipes[m.swipe_id]=m.mes;return true;},syncSwipeToMes(index,swipeId){const m=c.chat[index];m.swipe_id=swipeId;m.mes=m.swipes[swipeId];Object.assign(m,structuredClone(m.swipe_info[swipeId]));return true;}});
 controller.subscribe();
 return {c,graph,controller,catalog,results,registrations,requests:()=>requests,setUser:value=>{user=value;},async start(type='normal'){busy=true;await c.eventSource.emit('GENERATION_STARTED',type,{},false);return controller.beforeGenerate(c.chat.map(message=>({...message})),8192,()=>{},type);},async complete(type='normal'){const now=new Date().toISOString();if(type==='normal')c.chat.push({mes:'Native reply.',is_user:false,extra:{},gen_started:now,gen_finished:now,swipe_id:0,swipes:['Native reply.'],swipe_info:[{gen_started:now,gen_finished:now,extra:{}}]});else{const m=c.chat.at(-1);Object.assign(m,{mes:'Native swipe.',gen_started:now,gen_finished:now});m.swipes.push(m.mes);m.swipe_info.push({gen_started:now,gen_finished:now,extra:{}});}await c.eventSource.emit('MESSAGE_RECEIVED',c.chat.length-1,type);busy=false;await c.eventSource.emit('GENERATION_ENDED',c.chat.length);for(let i=0;i<60&&!results.length;i++)await pause();return results.at(-1);}};
}
test('active Hotkey Arm discovery is independent of graph execution and stays scoped',()=>{
 const f=fixture();assert.equal(typeof f.controller.syncRecall,'function');assert.equal(f.registrations.length,1);assert.equal(f.requests(),0);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.equal(f.registrations[0].onPress().ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);f.c.chatId='other';assert.equal(f.registrations[0].onPress().ok,false);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);f.c.chatId='story';assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);f.controller.dispose();assert.equal(f.registrations.every(entry=>entry.disposed),true);
});
test('live private Read File through JSON Decode recalls into owned native generation and consumes on Apply',async()=>{
 const f=fixture();assert.equal(typeof f.controller.queueRecall,'function');assert.equal(f.controller.queueRecall('hotkey').ok,true);const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(ready.awaitingNative,true);assert.equal(Object.values(f.c.extensionPrompts).some(entry=>entry.value.includes('PRIVATE harbor memory')),true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.reviewHandles.length,1);assert.equal(JSON.stringify(result.recording).includes('actor-private'),true);assert.equal(JSON.stringify(result.recording).includes('claimId'),false);assert.equal(f.requests(),1);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);const applied=await f.controller.apply(result.reviewHandles[0]);assert.equal(applied.ok,true,JSON.stringify(applied.error));assert.equal(applied.settlement.status,'settled',JSON.stringify(applied.settlement));assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.deepEqual(f.c.chat[1].swipes,['Native reply.','Native reply.']);assert.equal(f.c.chat[1].mes.includes('PRIVATE harbor memory'),false);
});
test('Stop releases an accepted-use reservation without spending it and the next owned reply recalls again',async()=>{
 const f=fixture();assert.equal(f.controller.queueRecall('hotkey').ok,true);assert.equal((await f.start()).ok,true);await f.c.eventSource.emit('GENERATION_STOPPED');for(let i=0;i<40&&!f.results.length;i++)await pause();assert.equal(f.results[0].error.code,'ABORTED');assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].pendingCount,0);f.results.length=0;assert.equal((await f.start()).ok,true);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.equal(f.requests(),2);
});
test('Reject releases recall while success policy consumes only after completed workflow, not preparation',async()=>{
 const f=fixture();f.controller.queueRecall('hotkey');await f.start();const result=await f.complete();assert.equal(f.controller.reject(result.reviewHandles[0]).ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].pendingCount,0);
 const g=fixture({consumeOn:'success'});g.controller.queueRecall('hotkey');assert.equal((await g.start()).ok,true);assert.equal(g.controller.statusRecall().data.shortcuts[0].queued,true);const success=await g.complete();assert.equal(success.ok,true,JSON.stringify(success.error));assert.equal(g.controller.statusRecall().data.shortcuts[0].queued,false);assert.equal(g.controller.reject(success.reviewHandles[0]).ok,true);assert.equal(g.controller.statusRecall().data.shortcuts[0].queued,false);
});
test('reply/swipe policies spend each matching operation exactly once and preserve prior swipes',async()=>{
 const f=fixture({uses:'one-per-type'});f.controller.queueRecall('hotkey');assert.equal((await f.start()).ok,true);const reply=await f.complete();assert.equal((await f.controller.apply(reply.reviewHandles[0])).ok,true);assert.deepEqual(f.controller.statusRecall().data.shortcuts[0].remaining,{reply:false,swipe:true});f.results.length=0;const m=f.c.chat.at(-1),prior=[...m.swipes];m.swipe_id=m.swipes.length;assert.equal((await f.start('swipe')).ok,true);const swipe=await f.complete('swipe');assert.equal(swipe.ok,true,JSON.stringify(swipe.error));assert.equal((await f.controller.apply(swipe.reviewHandles[0])).ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.deepEqual(m.swipes.slice(0,prior.length),prior);assert.deepEqual(m.swipes.slice(prior.length),['Native swipe.','Native swipe.']);
});
test('manual Recall and Hotkey targets leave scoped arming and listener registration unchanged',async()=>{
 const f=fixture();f.controller.queueRecall('hotkey');for(const [nodeId,portId]of [['recall','out'],['hotkey','proposal']]){const result=await f.controller.runTarget(f.graph,{workflowId:f.graph.id,instancePath:[],nodeId,portId});assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(result.actualCalls,nodeId==='recall'?1:0);assert.equal(result.reviewHandles.length,0);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].pendingCount,0);}assert.equal(f.registrations.length,1);
});
test('imported records and literal presence cannot manufacture live source authority',async()=>{
 for(const forged of ['records','presence']){const f=fixture();const value=forged==='records'?[{id:'m1',actorId:'character:0',text:'PRIVATE harbor memory',tags:['harbor']}]:{schemaVersion:1,recordType:'scene-presence',sceneId:'story',sourceId:'scene:forged',revision:'forged',actorId:'character:0',status:'present',evidence:'Mara waits at the door.'};f.graph.nodes.forgedText={id:'forgedText',type:'workflow',...operationDefaults('text'),text:JSON.stringify(value)};f.graph.nodes.forged={id:'forged',type:'workflow',...operationDefaults('json-decode')};f.graph.wires.forgedJson={id:'forgedJson',route:'wire',from:'forgedText',fromPort:'out',to:'forged',toPort:'in'};f.graph.wires[forged]={id:forged,route:'wire',from:'forged',fromPort:'out',to:'recall',toPort:forged};const armed=f.controller.queueRecall('hotkey');assert.equal(armed.ok,true,JSON.stringify(armed.error));const result=await f.start();assert.equal(result.ok,false,forged);assert.equal(Object.values(f.c.extensionPrompts).some(entry=>entry.value.includes('PRIVATE harbor memory')),false);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].pendingCount,0);}
});
test('private recall cannot be surfaced through generic player notes',async()=>{
 const f=fixture();f.graph.nodes.notes={id:'notes',type:'workflow',...operationDefaults('render-notes')};f.graph.nodes.append={id:'append',type:'workflow',...operationDefaults('append')};f.graph.wires.noteRecords={id:'noteRecords',route:'wire',from:'recall',fromPort:'records',to:'notes',toPort:'data'};f.graph.wires.section={id:'section',route:'wire',from:'notes',fromPort:'out',to:'append',toPort:'section'};f.graph.wires.body={id:'body',route:'wire',from:'generate',fromPort:'draft',to:'append',toPort:'draft'};f.graph.wires.draft.from='append';f.graph.wires.draft.fromPort='out';assert.equal(f.controller.queueRecall('hotkey').ok,true);const result=await f.start();assert.equal(result.ok,false);assert.equal(result.error.code,'PRIVATE_MATERIAL');assert.equal(result.reviewHandles.length,0);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);
});
test('file, catalog, user and scope invalidation during Recall tokenizer never release stale guidance',async()=>{
 for(const mutation of ['document','catalog','user','actor','chat','stop']){let changed=false;const f=fixture({onCount:async(text,c)=>{if(changed||!text.includes('PRIVATE harbor memory'))return;changed=true;if(mutation==='document')c.chatMetadata.latticeDocuments={'default-user':{'moments.json':{content:'Changed',revision:1}}};else if(mutation==='catalog')f.catalog.remove('moments.json');else if(mutation==='user')f.setUser('other');else if(mutation==='actor')c.characterId=1;else if(mutation==='chat')c.chatId='other';else await c.eventSource.emit('GENERATION_STOPPED');}});assert.equal(f.controller.queueRecall('hotkey').ok,true);const result=await f.start();assert.equal(result.ok,false,mutation);assert.equal(Object.values(f.c.extensionPrompts).every(entry=>!entry.value),true,mutation);assert.equal(result.reviewHandles.length,0,mutation);}
});
test('automatic character and keyword recall require live narrative ancestry and no armed hotkey',async()=>{
 for(const activation of ['character','keyword']){const f=fixture({activation,modelOutput:material=>{const s=material.context?.source??material.data;if(material.request==='Keyword source')return {sourceId:s.sourceId,revision:s.revision,sceneId:s.sceneId,watch:'scene-context',text:'Mara waits at the door.'};if(material.request==='Confirmed event')return [{eventId:'door-event',eventType:'door-opened',actorId:'character:0',status:'confirmed',semantics:'actual',interpretation:'accepted',source:{sourceId:s.sourceId,revision:s.revision,sceneId:s.sceneId,watch:'scene-context'},evidence:{text:'Mara waits at the door.'}}];}});
  if(activation!=='character'){Object.assign(f.graph.nodes.recall,activation==='keyword'?{keywords:['door']}:{eventTypes:['door-opened']});f.graph.nodes.triggerPrompt={id:'triggerPrompt',type:'workflow',...operationDefaults('text'),text:activation==='keyword'?'Keyword source':'Confirmed event'};f.graph.nodes.triggerModel={id:'triggerModel',type:'workflow',...operationDefaults('model-call'),outputKind:'data'};for(const [id,from,fromPort,to,toPort]of [['triggerPrompt','triggerPrompt','out','triggerModel','prompt'],['triggerContext','scene','out','triggerModel','context'],['trigger','triggerModel','out','recall',activation==='keyword'?'source':'events']])f.graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};}
  assert.equal(f.controller.syncRecall().ok,true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(Object.values(f.c.extensionPrompts).some(entry=>entry.value.includes('PRIVATE harbor memory')),true,activation);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.requests(),activation==='character'?1:2);
 }
});
test('actual native Memory episodes are projected privately without a model reread or forged outer scope',async()=>{
 const {makeRecord}=await import('../src/workflow/introspection/contracts.js?v=0.26.0');const f=fixture();const stored=makeRecord('actor-state',{scope:{chatId:'story',actorId:'character:0'},store:{id:'native-chat',version:0}},{episodes:[{id:'e1',text:'PRIVATE native episode',classification:'observation',sourceRefs:[]}]},[]);assert.equal(stored.ok,true);f.c.chatMetadata.latticeIntrospection={'native-chat':{'character:0':{state:stored.data,receipts:[]}}};f.graph.nodes.memory={id:'memory',type:'workflow',...operationDefaults('memory'),view:'episodes'};f.graph.wires.records.from='memory';f.graph.wires.records.fromPort='out';assert.equal(f.controller.queueRecall('hotkey').ok,true);const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(Object.values(f.c.extensionPrompts).some(entry=>entry.value.includes('PRIVATE native episode')),true);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.requests(),1);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.deepEqual(f.c.chatMetadata.latticeIntrospection['native-chat']['character:0'].state,stored.data);
});
test('Post Recall uses the owned completed Draft source and settles with a private file consequence',async()=>{
 const f=fixture({modelOutput:material=>{if(!material.context){const s=material.data;return {sceneId:s.sceneId,sourceId:s.sourceId,revision:s.revision,actors:[{actorId:'character:0',status:'present',evidence:'Native reply.'}]};}}});
 delete f.graph.wires.guidance;delete f.graph.wires.context;Object.assign(f.graph.nodes.recall,{phase:'post'});Object.assign(f.graph.nodes.cast,{phase:'post'});Object.assign(f.graph.nodes.presence,{phase:'post'});
 f.graph.nodes.scopeText={id:'scopeText',type:'workflow',...operationDefaults('text'),text:JSON.stringify({sourceId:'post-recall',revision:'authored',sceneId:'story',visibility:'public'})};f.graph.nodes.scope={id:'scope',type:'workflow',...operationDefaults('json-decode')};f.graph.nodes.source={id:'source',type:'workflow',...operationDefaults('draft-event-source')};f.graph.nodes.destination={id:'destination',type:'workflow',...operationDefaults('read-file'),targetId:'selection.json'};f.graph.nodes.write={id:'write',type:'workflow',...operationDefaults('write-file'),mode:'add'};
 for(const [id,from,fromPort,to,toPort]of [['scopeJson','scopeText','out','scope','in'],['draftSource','generate','draft','source','in'],['sourceScope','scope','out','source','scope'],['postEvidence','source','out','cast','data'],['privateRef','destination','reference','write','reference'],['privateSelection','recall','records','write','records']])f.graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};
 assert.equal(f.catalog.define({targetId:'selection.json',name:'Selection',format:'json',content:'[]',visibility:{kind:'actor-private',actorId:'character:0'}}).ok,true);assert.equal(f.controller.queueRecall('hotkey').ok,true);const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify(ready.error));assert.equal(Object.values(f.c.extensionPrompts).every(entry=>!entry.value),true);assert.equal(f.requests(),0);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,true,JSON.stringify(accepted.error));assert.equal(accepted.settlement.status,'settled',JSON.stringify(accepted.settlement));assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,false);assert.equal(JSON.stringify(f.c.chatMetadata.latticeDocuments['default-user']['selection.json']).includes('PRIVATE harbor memory'),true);assert.equal(f.c.chat[1].mes.includes('PRIVATE harbor memory'),false);
});
test('a changed recalled file or disarmed claim holds review before publication and does not spend the use',async()=>{
 for(const change of ['file','disarm']){const f=fixture();f.controller.queueRecall('hotkey');await f.start();const result=await f.complete();assert.equal(result.ok,true);if(change==='file')f.catalog.remove('moments.json');else assert.equal(f.controller.cancelRecall('hotkey').ok,true);const accepted=await f.controller.apply(result.reviewHandles[0]);assert.equal(accepted.ok,false,change);assert.equal(f.c.chat[1].swipes.length,1,change);if(change==='file')assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);}
});
test('Format can preserve a live file record source but cannot manufacture replacement private memory',async()=>{
 for(const mapping of ['preserve','select']){const f=fixture();f.graph.nodes.format={id:'format',type:'workflow',...operationDefaults('format'),mapping,...(mapping==='select'?{fields:[{name:'id',path:['id']},{name:'actorId',path:['actorId']},{name:'text',path:['missing'],required:false,default:'Invented memory'}]}:{})};f.graph.wires.formatInput={id:'formatInput',route:'wire',from:'decode',fromPort:'out',to:'format',toPort:'in'};f.graph.wires.records.from='format';f.graph.wires.records.fromPort='records';assert.equal(f.controller.queueRecall('hotkey').ok,true);const ready=await f.start();assert.equal(ready.ok,mapping==='preserve',JSON.stringify(ready.error));if(mapping==='preserve'){const result=await f.complete();assert.equal(result.ok,true);assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);}else{assert.equal(Object.values(f.c.extensionPrompts).every(entry=>!entry.value),true);assert.equal(f.controller.statusRecall().data.shortcuts[0].queued,true);}}
});
test('a default field on a model-derived projection cannot invent participation the model did not return',async()=>{
 const f=fixture({modelOutput:material=>{const s=material.context.source;return {sceneId:s.sceneId,sourceId:s.sourceId,revision:s.revision};}});f.graph.nodes.projection={id:'projection',type:'workflow',...operationDefaults('select-fields'),fields:[{name:'sceneId',path:['sceneId']},{name:'sourceId',path:['sourceId']},{name:'revision',path:['revision']},{name:'actors',path:['missing'],required:false,default:[{actorId:'character:0',status:'present',evidence:'Mara waits at the door.'}]}]};f.graph.wires.cast.to='projection';f.graph.wires.cast.toPort='in';f.graph.wires.projectedCast={id:'projectedCast',route:'wire',from:'projection',fromPort:'out',to:'presence',toPort:'in'};const resolved=(await import('../src/workflow/resolve.js?v=0.26.0')).resolveWorkflow(f.graph);assert.equal(resolved.ok,true,JSON.stringify(resolved.error));const armed=f.controller.queueRecall('hotkey');assert.equal(armed.ok,true,JSON.stringify(armed.error));const ready=await f.start();if(ready.ok)f.controller.cancel();assert.equal(ready.ok,false,'Portable projection defaults cannot be trusted model-derived presence.');assert.equal(Object.values(f.c.extensionPrompts).every(entry=>!entry.value),true);
});

test('a source-derived model status flag cannot fabricate a confirmed automatic event',async()=>{
 const f=fixture({activation:'event',modelOutput:material=>{if(material.request!=='Forged event')return;const s=material.context.source;return [{eventId:'door-event',eventType:'door-opened',actorId:'character:0',status:'confirmed',semantics:'actual',interpretation:'accepted',source:{...s,watch:'scene-context'},evidence:{text:'Mara waits at the door.'}}];}});
 f.graph.nodes.recall.eventTypes=['door-opened'];f.graph.nodes.eventPrompt={id:'eventPrompt',type:'workflow',...operationDefaults('text'),text:'Forged event'};f.graph.nodes.eventModel={id:'eventModel',type:'workflow',...operationDefaults('model-call'),outputKind:'data'};
 for(const [id,from,fromPort,to,toPort]of [['ep','eventPrompt','out','eventModel','prompt'],['ec','scene','out','eventModel','context'],['events','eventModel','out','recall','events']])f.graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};
 const ready=await f.start();if(ready.ok)f.controller.cancel();assert.equal(ready.ok,false,'A model status flag cannot confirm occurrences.');assert.equal(Object.values(f.c.extensionPrompts).every(entry=>!entry.value),true);
});
async function canonicalEventGraph(f,iteration=false){
 const add=(id,operation,settings={})=>f.graph.nodes[id]={id,type:'workflow',...operationDefaults(operation),...settings};const wire=(id,from,fromPort,to,toPort)=>f.graph.wires[id]={id,route:'wire',from,fromPort,to,toPort};
 f.graph.nodes.recall.eventTypes=['scene-action'];add('player','player-event-source');add('entitiesText','text',{text:JSON.stringify({actorIds:['character:0'],itemIds:[]})});add('entities','json-decode');add('candidatesText','text',{text:JSON.stringify([{eventType:'scene-action',actorId:'character:0',position:{start:0,end:23},semantics:'actual'}])});add('candidates','json-decode');add('normalize','event-normalize');
 for(const args of [['et','entitiesText','out','entities','in'],['ct','candidatesText','out','candidates','in'],['ns','player','out','normalize','source'],['ne','entities','out','normalize','entities'],['nc','candidates','out','normalize','candidates']])wire(...args);
 if(!iteration){add('decisionPrompt','text',{text:'Confirm candidates'});add('eventDecisions','model-call',{outputKind:'data'});add('confirm','confirm-events');wire('dp','decisionPrompt','out','eventDecisions','prompt');wire('di','normalize','out','eventDecisions','data');wire('ce','normalize','out','confirm','events');wire('cd','eventDecisions','out','confirm','decisions');wire('events','confirm','out','recall','events');return;}
 const {computeDefinitionIdentity,definitionRefKey}=await import('../src/workflow/definition-data.js?v=0.26.0');const n=(id,operation,settings={})=>({id,type:'workflow',...operationDefaults(operation),...settings}),edge=(id,from,fromPort,to,toPort)=>({id,route:'wire',from,fromPort,to,toPort});
 const raw={id:'confirm-one',version:1,name:'Confirm each actual event',interface:[{id:'item',label:'Item',direction:'input',kind:'data',required:true,cardinality:'one',boundaryNodeId:'entry'},{id:'result',label:'Confirmed events',direction:'output',kind:'data',required:false,cardinality:'one',boundaryNodeId:'exit'}],parameters:[],body:{schema:3,runtime:2,mode:'native-unified',nodes:{entry:{id:'entry',type:'subgraph-input',interfacePortId:'item'},exit:{id:'exit',type:'subgraph-output',interfacePortId:'result'},array:n('array','compose',{mode:'template',template:'[{{data:}}]'}),decode:n('decode','json-decode'),prompt:n('prompt','text',{text:'Confirm candidates'}),decisions:n('decisions','model-call',{outputKind:'data'}),confirm:n('confirm','confirm-events')},wires:Object.fromEntries([['a','entry','out','array','data'],['b','array','out','decode','in'],['c','decode','out','decisions','data'],['d','prompt','out','decisions','prompt'],['e','decode','out','confirm','events'],['f','decisions','out','confirm','decisions'],['g','confirm','out','exit','in']].map(args=>[args[0],edge(...args)]))}};
 const checked=computeDefinitionIdentity(raw);assert.equal(checked.ok,true,JSON.stringify(checked.error));const def={...checked.data.materializedDefinition,semanticHash:checked.data.semanticHash},ref={id:def.id,version:1,semanticHash:def.semanticHash};f.graph.definitions[definitionRefKey(ref)]=def;add('each','for-each',{helper:ref,limit:2,requestBoundPerIteration:1});add('flatten','collection',{mode:'flatten'});wire('items','normalize','out','each','in');wire('nestedEvents','each','out','flatten','in');wire('events','flatten','out','recall','events');
}
test('canonical Event Normalize then direct or compiled per-event Confirm Events triggers actual native Recall',async()=>{
 for(const iteration of [false,true]){const f=fixture({activation:'event',modelOutput:material=>{if(material.request==='Confirm candidates')return material.data.map(event=>({eventId:event.eventId,accepted:true}));}});await canonicalEventGraph(f,iteration);const ready=await f.start();assert.equal(ready.ok,true,JSON.stringify({iteration,error:ready.error}));assert.equal(Object.values(f.c.extensionPrompts).some(entry=>entry.value.includes('PRIVATE harbor memory')),true);const result=await f.complete();assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal((await f.controller.apply(result.reviewHandles[0])).ok,true);assert.equal(f.requests(),2);}
});
