import assert from 'node:assert/strict';
import test from 'node:test';
import { runWorkflowForHost } from '../src/workflow/runtime.js?v=0.27.0';
import { readDraftBody } from '../src/workflow/draft-revisions.js?v=0.27.0';
const native={kind:'draft',text:'Accepted narrative body.',source:{token:'native-token',originalText:'Accepted narrative body.'}};
const node=(id,operation,settings={})=>({id,type:'workflow',operation,...settings});
const wire=(id,from,fromPort,to,toPort)=>({id,route:'wire',from,fromPort,to,toPort});
const graph={id:'terminal-authority',schema:3,runtime:2,mode:'native-unified',nodes:{send:node('send','on-send'),generate:node('generate','generate-reply'),notes:node('notes','text',{text:'Descriptive notes are not story evidence.'}),append:node('append','append',{sectionId:'details'}),review:node('review','review-publish')},wires:Object.fromEntries([wire('activation','send','activation','generate','activation'),wire('draft','generate','draft','append','draft'),wire('notes','notes','out','append','section'),wire('review','append','out','review','draft')].map(edge=>[edge.id,edge])),definitions:{},portals:{}};
test('only private terminal transport retains the exact authentic final Draft with narrative body separate from notes',async()=>{let transport;const result=await runWorkflowForHost(graph,{runId:'terminal-auth-run'}, {executeHostOperation(operation){if(operation.operation==='on-send')return {ok:true,outputs:{activation:{kind:'data',value:{}}}};if(operation.operation==='generate-reply')return {ok:true,outputs:{draft:native,metadata:{kind:'data',value:{}}}};throw new Error('Unexpected host operation');},settle(value){transport={...value,terminals:[...value.terminals]};return {ok:true};}});assert.equal(result.ok,true,JSON.stringify(result.error));assert.equal(transport.terminals.length,1);const terminal=transport.terminals[0];assert.equal(terminal.inputDraft.kind,'draft');assert.equal(terminal.inputDraft.text,terminal.artifact.text);assert.equal(readDraftBody(terminal.inputDraft).data.text,'Accepted narrative body.');assert.match(terminal.artifact.text,/Descriptive notes/);assert.equal(JSON.stringify(result).includes('inputDraft'),false,'authentic terminal inputs never become public authority');});
