const info = (id, title, message) => ({ id, severity: 'info', title, message });
const warning = (id, title, message) => ({ id, severity: 'warning', title, message });
const error = (id, title, message) => ({ id, severity: 'error', title, message });
const nativeMessage = 'This step starts when you send a message. Enable Lattice, then send a message in SillyTavern to run this workflow.';
const recordingLimit = info('recording-size-limit', 'Preview was not retained', 'The preview recording reached its size limit, so this output was not retained. This does not mean the model stopped early.');
const invalidRecording = info('recording-invalid', 'Recorded preview is unavailable', 'The recorded preview could not be read safely. This does not establish whether the step succeeded. Choose a current output to inspect.');

// Preview states are supplied by projection; they never infer execution or save authority.
export const stateCopy = {
    PREVIEW_NOT_RUN: info('not-run', 'Not run yet', 'This step has not run yet. Use Run to here when it is available.'),
    PREVIEW_RUNNING: info('running', 'Running', 'This step is running. Its output will appear when it finishes.'),
    PREVIEW_WORKFLOW_RUNNING: info('workflow-running', 'Workflow is running', 'The workflow is running. This output is not available yet.'),
    PREVIEW_WAITING: info('waiting', 'Waiting for input', 'This step is waiting for an earlier step to finish.'),
    PREVIEW_UNRESOLVED: info('unresolved', 'No input for this branch', 'An earlier step did not produce the input this branch needs. Check that step’s output and branch conditions.'),
    PREVIEW_SKIPPED: info('skipped', 'Step skipped', 'This branch was intentionally skipped for this run.'),
    OUTPUT_NOT_RETAINED: info('not-retained', 'Output is not retained', 'No saved preview is available for this output.'),
    OUTPUT_REMOVED: info('output-removed', 'Output is no longer available', 'The selected output was removed or changed. Choose a current output.'),
    EARLIER_OUTPUT: info('earlier-output', 'Earlier output', 'This is output from an earlier run. It does not describe the current run.'),
    PREVIEW_TRUNCATED: info('preview-truncated', 'Preview shortened', 'Only the displayed preview was shortened. This does not mean the model stopped early.'),
    MANUAL_NATIVE_TRIGGER_REQUIRED: info('send-required', 'Starts with a message', nativeMessage),
    NATIVE_SEND_REQUIRED: info('send-required', 'Starts with a message', nativeMessage),
    RECALL_PREVIEW_NO_ACTIVATION: info('recall-preview', 'Recall waits for generation', 'Recall runs during a normal SillyTavern message or generated swipe. A manual preview does not activate it.'),
    ABORTED: info('stopped', 'Stopped', 'This action was stopped. Late output will not be used.'),
    CANCELLED: info('cancelled', 'Cancelled', 'This action was cancelled.'),
    WORKFLOW_CANCELLED: info('workflow-cancelled', 'Workflow stopped', 'The workflow was stopped.'),
    FILE_CANCELLED: info('file-cancelled', 'File action cancelled', 'The file action was cancelled. The open draft is still available.'),
    NODE_CONFIGURATION_CANCELLED: info('node-cancelled', 'Node creation cancelled', 'Node creation was cancelled.'),
    BUSY: info('busy', 'Another action is running', 'Wait for generation or reply application to finish before continuing.'),
    ALREADY_APPLIED: info('already-applied', 'Already applied', 'This revision has already been applied.'),
    COMMIT_DISABLED: info('commit-preview', 'Preview does not save memory', 'Preview and dry-run execution do not commit memory.'),
    RECALL_REGISTRATION_PENDING: info('recall-registering', 'Shortcut is being prepared', 'The Recall Shortcut is still being registered.'),
    CONTEXT_PRESERVATION: info('context-preserved', 'Original context retained', 'The original context is retained alongside the compacted output.'),
    COMPRESSION_INPUT_OMITTED: warning('compression-omitted', 'Some context was left out', 'Some older messages did not fit the compression input. The originals are retained.'),
    PERSISTENCE_PARTIAL: warning('save-partial', 'Some changes are not saved', 'The accepted reply is retained. Some associated changes could not be saved. Review each target’s save status.'),
    RECENT_STORAGE_FAILED: warning('recent-storage', 'Recent files could not be remembered', 'The browser could not remember recent workflow files. Your open workflow is still available.'),
    VIEW_PERSISTENCE: warning('view-persistence', 'View layout was reset', 'The saved graph layout could not be restored. The workflow is available with a fresh view layout.'),
};
for (const code of ['PERSISTENCE_UNKNOWN', 'PERSISTENCE_UNVERIFIED', 'SAVE_UNVERIFIED', 'APPLY_SAVE_UNVERIFIED']) {
    stateCopy[code] = warning('save-unverified', 'Saving is not confirmed', 'The save outcome could not be verified. Confirm the stored data before making another write.');
}

export const knownTextCopy = new Map([
    ['Enter valid JSON before saving.', { id: 'json-setting', severity: 'error', title: 'Check the JSON', message: 'Enter valid JSON before saving.' }],
    ['Enter a finite number before saving.', { id: 'number-setting', severity: 'error', title: 'Check the number', message: 'Enter a finite number before saving.' }],
    ['Enter a number within the allowed range and step.', { id: 'range-setting', severity: 'error', title: 'Check the number', message: 'Enter a number within the allowed range and step.' }],
    ['Enter a model identifier before saving an override.', { id: 'model-override-empty', severity: 'error', title: 'Enter a model identifier', message: 'Enter a model identifier before saving an override.' }],
    ['Enter a model identifier of 1–256 characters.', { id: 'model-override-length', severity: 'error', title: 'Check the model identifier', message: 'Enter a model identifier of 1–256 characters.' }],
    ['Choose a connection to run.', { id: 'connection-required', severity: 'error', title: 'Choose a connection', message: 'Choose a connection to run.' }],
    ['Assign a fixed connection to this node or its model role.', { id: 'fixed-connection', severity: 'error', title: 'Choose a connection', message: 'Assign a fixed connection to this node or its model role.' }],
    ['Use a JSON object before selecting a configured value.', { id: 'configuration-json', severity: 'error', title: 'Check the controls JSON', message: 'Use a JSON object before selecting a configured value.' }],
    ['Use a positive starting day, a time within the day, and a day length in whole minutes.', error('clock-starting-values', 'Check the clock’s starting values', 'Set Starting day to a positive whole number, Starting time to a time within the day, and Hours per day to a positive duration in whole minutes. Enter a Calendar name.')],
    ['Load a valid clock template before changing its starting values.', error('clock-template-needed', 'Load a valid clock template', 'Use Load initial values to load a valid clock template before changing its starting values.')],
    ['Load the initial template before saving.', error('initial-template-needed', 'Load initial values first', 'Use Load initial values before changing the initial template with Save settings.')],
    ['Choose an actor for private data.', error('private-actor-needed', 'Choose the private actor', 'Enter Actor ID when Visibility is Actor private.')],
    ['The initial template could not be loaded.', error('initial-template-load', 'Initial template could not be loaded', 'The initial template could not be loaded. Check the source document and its authorization in Workflow Data.')],
    ['Check the initial settings.', error('initial-settings', 'Check the initial settings', 'Check the initial template and settings in Workflow Data.')],
    ['Check the new data settings.', error('new-data-settings', 'Check the new data settings', 'Check Name, Format, Visibility, and the required initial values in Workflow Data.')],
    ['Workflow data could not be updated.', warning('workflow-data-update-unverified', 'Workflow Data update is not confirmed', 'The Workflow Data update could not be confirmed. Inspect the current data and initial settings before making another change.')],
    ['Workflow Data setup could not be applied.', warning('workflow-data-setup-unverified', 'Workflow Data setup is not confirmed', 'The Workflow Data setup change could not be confirmed. Inspect the current configuration before making another change.')],
    ['The subgraph could not be saved. Check the current settings before trying the edit again.', warning('subgraph-save-unverified', 'Subgraph saving is not confirmed', 'The subgraph save could not be confirmed. Inspect the saved subgraph and current settings before making another change.')],
    ['The edit could not be accepted. Check the current settings before trying the edit again.', error('edit-not-accepted', 'Edit could not be accepted', 'The edit could not be accepted. Check the current settings and selection before preparing another edit.')],
    ['The node could not be prepared.', error('node-not-prepared', 'Node could not be prepared', 'The node could not be prepared. Check the required controls in node configuration.')],
    ['Memory recall could not be updated.', error('recall-not-updated', 'Recall could not be updated', 'Recall could not be updated. Reopen the Recall controls and inspect the current scope and queue status.')],
    ['Memory recall is unavailable.', info('recall-unavailable', 'Recall is unavailable', 'Recall is unavailable. Check the active chat, character, and enabled workflow.')],
    ['The portal change could not be accepted.', error('portal-not-accepted', 'Portal change could not be accepted', 'The portal change could not be accepted. Check the current graph view and portal settings.')],
    ['Could not change connection profile', error('profile-not-changed', 'Connection profile could not be changed', 'The Connection profile could not be changed. Select a current node and check the available profiles.')],
    ['Lattice disabled', info('lattice-disabled', 'Lattice is disabled', 'Enable Lattice to use this feature.')],
    ['This Recall uses automatic triggers.', info('recall-automatic', 'Recall uses automatic triggers', 'This Recall uses automatic triggers. Queue recall is available for manual activation settings.')],
    ['Recall is already queued.', info('recall-queued', 'Recall is already queued', 'Recall is already queued. Use Cancel recall to remove the queued request.')],
    ['Memory recall is available in the root workflow.', info('recall-root', 'Open the root workflow', 'Memory recall is available in the root workflow.')],
    ['Memory recall requires an active user, chat, and character.', info('recall-active-scope', 'Recall needs an active chat', 'Open an active user, chat, and character to use Recall.')],
    ['This node belongs to another character.', info('recall-character', 'Select the matching character', 'This node belongs to another character. Select the matching character to use its Recall controls.')],
    ['Add a matching Recall Shortcut to queue this memory set.', info('recall-shortcut-needed', 'Add a Recall Shortcut', 'Add a matching Recall Shortcut to queue this memory set.')],
    ['The Recall and Shortcut generation targets do not overlap.', info('recall-targets', 'Recall targets do not match', 'Choose overlapping generation targets for the Recall and matching Shortcut in Details.')],
    ['No manual recall is queued for these nodes.', info('recall-cancel-empty', 'No Recall request to cancel', 'No manual recall is queued for these nodes.')],
    ['Select an eligible Recall or Recall Shortcut node.', info('recall-selection', 'Select a Recall node', 'Select an eligible Recall or Recall Shortcut node.')],
    ['Library definitions are read-only.', info('read-only-library', 'Library definition', 'Library definitions are read-only. Make a local copy to edit this definition.')],
    ['Library inspection is read-only and has no runtime output.', info('library-preview', 'Library definition preview', 'Library definitions do not run here. Open a workflow that uses this definition to inspect its output.')],
    ['The previous workspace presentation is unreadable.', warning('recovered-layout', 'Saved view could not be restored', 'The workflow can be opened, but its saved view layout could not be restored.')],
    ['The previous recovery draft workspace presentation is unreadable.', warning('recovered-layout', 'Saved view could not be restored', 'The recovery draft can be opened, but its saved view layout could not be restored.')],
    ['No output recorded yet.', stateCopy.PREVIEW_NOT_RUN],
    ['Artifact omitted: recording-byte-limit', recordingLimit],
    ['Artifact omitted: recording-metadata-limit', recordingLimit],
    ['Artifact omitted: canonical-prefix-limit', recordingLimit],
    ['Artifact omitted: invalid-diagnostic-data', invalidRecording],
    ['Artifact omitted: invalid diagnostic data', invalidRecording],
    ['Artifact omitted: unavailable', info('recording-unavailable', 'Recorded preview is unavailable', 'No recorded preview is available for this output. Choose a current output to inspect.')],
    ['Artifact omitted: historical wrapper mapping unavailable', info('historical-mapping', 'Earlier output cannot be located', 'This earlier output cannot be matched to the current subgraph. Choose a current output to inspect.')],
    ['Workflow Data setup is unavailable.', info('data-setup', 'Workflow Data needs setup', 'Open an active chat to configure Workflow Data.')],
]);
