export type Failure = {ok:false;error:{code:string;message:string}};
export type Result<T> = {ok:true;data:T}|Failure;
export type Scope = {chatId:string;actorId:string};
export type Store = {id:string;version:number};
export type SourceRef = {id:string;revision:string};
export type Item = {id:string;text:string;classification:'observation'|'interpretation'|'possibility';sourceRefs:SourceRef[]};
export type Curve = {phase:'onset'|'peak'|'plateau'|'decline'|'aftermath'|'baseline';value:number;elapsed:number};
export type Track = {eventIds:string[];count:number};
export type StateMaps = {values:Record<string,number>;curves:Record<string,Curve>;tracks:Record<string,Track>};
export type ActorState = StateMaps & {traits:Item[];beliefs:Item[];goals:Item[];relationships:Item[];conflicts:Item[];conditions:Item[];episodes:Item[]};
export type Change = {op:'upsert';collection:'beliefs'|'goals'|'relationships'|'conflicts'|'conditions'|'episodes';item:Item}|{op:'remove';collection:'beliefs'|'goals'|'relationships'|'conflicts'|'conditions'|'episodes';id:string};
export type StateProposal = StateMaps & {changes:Change[]};
export type Reflection = {brief:string;appraisals:string[];conflicts:string[];recalls:string[];sceneChanges:string[];behaviorHints:string[];attentionHints:string[];recalledEpisodeIds:string[]};
export type SettledEvent = {id:string;revision:string;text:string;settled:true};
export type RecordType = 'actor-state'|'state-proposal'|'reflection'|'events'|'episodes'|'commit-intent';
export interface IntrospectionRecord<P=unknown> {schemaVersion:1;recordType:RecordType;scope:Scope;store:Store;sourceRefs:SourceRef[];payload:P}
export type Data<P=unknown> = {kind:'data';value:IntrospectionRecord<P>};
export type OperationResult<A=unknown> = {ok:true;artifact:A;reports:unknown[]}|Failure;
export const COLLECTIONS:readonly string[];
export function fail(code:string,message:string):Failure;
export function freeze<T>(value:T):T;
export function ownData(value:unknown):Result<unknown>;
export function inspectCapabilities(value:unknown):Result<Record<string,unknown>>;
export function validateEvidence(refs:unknown,allowed:unknown):Result<void>;
export function parseRecord<P=unknown>(artifact:unknown,expectedType?:RecordType):Result<IntrospectionRecord<P>>;
export function makeRecord<P=unknown>(recordType:RecordType,base:{scope:Scope;store:Store;sourceRefs?:SourceRef[]},payload:P,sourceRefs?:SourceRef[]):Result<Data<P>>;
export function createActorState(scope:Scope,store?:Store,initial?:Partial<ActorState>):Result<Data<ActorState>>;
export function sameIdentity(a:IntrospectionRecord,b:IntrospectionRecord):boolean;
export function applyStateProposal(state:unknown,proposal:unknown):Result<Data<ActorState>>;
