<script lang="ts">
    import DiagnosticMessage from './DiagnosticMessage.svelte';
 import {onMount,tick} from 'svelte';
 import type {ConfigureNodeView,ConfigureNodeActions} from './storage-setup-types';
 let {view,actions}:{view:ConfigureNodeView;actions?:ConfigureNodeActions}=$props();
 let dialog:HTMLDivElement,controls=$state(''),phase=$state<'pre'|'post'>('pre'),target=$state(''),helper=$state(''),pending=$state(false),failure=$state('');let capture='',generation=0;
 const usesDocument=$derived(view.operation==='read-file'||view.operation==='story-clock'||view.operation==='commit-outcomes');
 $effect(()=>{if(view.key===capture)return;capture=view.key;generation++;controls=view.controls;phase=view.phase;pending=false;failure='';try{const data=JSON.parse(controls);target=data.targetId??data.clockId??'';helper=view.helpers.find(choice=>JSON.stringify(choice.ref)===JSON.stringify(data.helper))?.key??'';}catch{target='';helper='';}const key=capture;void tick().then(()=>{if(view.key===key)dialog?.querySelector<HTMLElement>('select,textarea,input')?.focus({preventScroll:true});});});
 onMount(()=>{const anchor=document.activeElement as HTMLElement;return ()=>anchor?.focus({preventScroll:true});});
 function setControl(key:string,value:unknown){try{const data=JSON.parse(controls);if(!data||Array.isArray(data)||typeof data!=='object')throw Error();data[key]=value;controls=JSON.stringify(data,null,2);failure='';}catch{failure='Use a JSON object before selecting a configured value.';}}
 async function apply(event:SubmitEvent){event.preventDefault();if(!actions||pending)return;const key=view.key,request=++generation;pending=true;failure='';try{const result:any=await actions.apply(key,controls,phase);if(key===view.key&&request===generation&&!result?.ok)failure=(result?.error ? result.error.code + ': ' + result.error.message : undefined)??'The node could not be prepared.';}catch{if(key===view.key&&request===generation)failure='The node could not be prepared.';}finally{if(key===view.key&&request===generation)pending=false;}}
 function keys(event:KeyboardEvent){event.stopPropagation();if(event.key==='Escape'){event.preventDefault();actions?.cancel(view.key);}if(event.key==='Tab'){const elements=[...dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled)')],first=elements[0],last=elements.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last?.focus();}if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first?.focus();}}}
</script>
<div class="pc-workspace-overlay"><div class="pc-workspace-dialog pc-configure-node" role="dialog" aria-modal="true" aria-label="Configure node" tabindex="-1" bind:this={dialog} onkeydowncapture={keys} onpaste={event=>event.stopPropagation()}>
 <header><h2>Configure {view.title}</h2><button type="button" aria-label="Close node configuration" onclick={()=>actions?.cancel(view.key)}>×</button></header>
 <p>Complete the required settings before creating the node. Cancel leaves the graph unchanged.</p>
 <form onsubmit={apply}>
  <label>Stage<select aria-label="Node stage" bind:value={phase} disabled={view.phaseLocked||pending}><option value="pre">Preparation</option><option value="post">Response</option></select></label>
  {#if usesDocument}<label>Workflow data document<select aria-label="Workflow data document" bind:value={target} onchange={()=>setControl(view.operation==='story-clock'?'clockId':'targetId',target)} disabled={pending}><option value="">Choose an authorized target</option>{#each view.targets.filter(doc=>!['story-clock','commit-outcomes'].includes(view.operation)||doc.format==='json') as doc (doc.targetId)}<option value={doc.targetId}>{doc.name} ({doc.targetId})</option>{/each}</select></label>{#if !view.targets.length}<p>Authorize a document in Workflow › Configure › Workflow Data, then reopen node creation.</p>{/if}{/if}
  {#if view.operation==='for-each'}<label>Pinned Data helper<select aria-label="Pinned Data helper" bind:value={helper} onchange={()=>{const choice=view.helpers.find(choice=>choice.key===helper);if(choice)setControl('helper',choice.ref);}} disabled={pending}><option value="">Choose an existing item/result helper</option>{#each view.helpers as choice (choice.key)}<option value={choice.key}>{choice.label}{choice.stateful?' (projected state)':''}</option>{/each}</select></label><p>Helpers use exact pinned versions with Data item and result ports. Set iteration mode and requestBoundPerIteration in the controls below.</p>{/if}
  <label>Declared node controls<textarea aria-label="Node controls JSON" rows="14" maxlength="200000" bind:value={controls} disabled={pending}></textarea></label>
  {#if failure}<div><DiagnosticMessage issue={failure} /></div>{/if}
  <footer><button type="button" onclick={()=>actions?.cancel(view.key)}>Cancel</button><button type="submit" disabled={!actions||pending}>{pending?'Preparing…':'Create node'}</button></footer>
 </form>
</div></div>
<style>
 .pc-configure-node {width:min(540px,calc(100% - 28px));max-height:calc(100% - 28px);overflow:auto;box-sizing:border-box;padding:16px;font-size:12px;} header,footer {display:flex;gap:8px;align-items:center;} h2 {flex:1;margin:0;font-size:16px;} p {line-height:1.5;color:var(--pc-muted,#aeb7ba);} label {display:block;margin:12px 0;} select,textarea {display:block;width:100%;box-sizing:border-box;margin-top:4px;padding:6px;border:1px solid var(--pc-border,#ffffff30);background:var(--pc-canvas,#141516);color:inherit;font:inherit;} textarea {resize:vertical;font-family:monospace;} button {padding:5px 8px;background:var(--pc-block,#2a2c2e);color:inherit;border:1px solid var(--pc-border,#ffffff30);font:inherit;} footer {justify-content:flex-end;} :disabled {opacity:.5;} :is(select,textarea,button):focus-visible {outline:2px solid var(--pc-flow,#e18a24);outline-offset:1px;}
</style>
